-- Migration V13: Create Tu Vi Cycle Interpretation Table
-- Purpose: Store Đại hạn/Tiểu vận interpretations generated by Grok AI
-- This table caches cycle interpretations separately from full interpretations

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================
-- tuvi_cycle_interpretation table
-- Stores cycle (Đại hạn/Tiểu vận) interpretations
-- ============================
DROP TABLE IF EXISTS tuvi_cycle_interpretation;
CREATE TABLE tuvi_cycle_interpretation (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    -- Reference to natal chart
    chart_hash VARCHAR(64) NOT NULL COMMENT 'SHA-256 hash of chart structure',
    gender ENUM('male', 'female') NOT NULL,
    
    -- User info for display
    name VARCHAR(128) COMMENT 'Chart owner name',
    birth_date DATE COMMENT 'Birth date',
    
    -- Cycle interpretation content (JSON)
    cycle_interpretation_data JSON NOT NULL COMMENT 'Complete cycle interpretation as JSON',
    
    -- Metadata
    ai_model VARCHAR(64) COMMENT 'Grok model used for generation',
    generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    -- Indexes
    UNIQUE KEY uk_chart_hash_gender (chart_hash, gender),
    INDEX idx_chart_hash (chart_hash),
    INDEX idx_gender (gender),
    INDEX idx_generated_at (generated_at)
    
    -- Note: Foreign key to natal_chart is optional
    -- We don't enforce it to allow flexibility in data management
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Cache for Đại hạn/Tiểu vận interpretations generated by Grok AI';

SET FOREIGN_KEY_CHECKS = 1;

