# Analysis options for Lịch Vạn Niên Flutter app
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat missing returns as errors
    missing_return: error
    # Treat unused locals as warnings
    unused_local_variable: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"

linter:
  rules:
    # Error prevention
    avoid_print: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_duplicate_case_values: true
    throw_in_finally: true
    unnecessary_statements: true

    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sort_constructors_first: true
    use_key_in_widget_constructors: true

    # Documentation
    slash_for_doc_comments: true

    # Avoid
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true

    # Prefer
    prefer_const_constructors_in_immutables: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true

    # Type safety
    always_declare_return_types: true
    avoid_types_as_parameter_names: true
    prefer_typing_uninitialized_variables: true
