-- ============================================================
-- DETAILED INTERPRETATION FRAGMENTS: CHỦ THÂN (Body Master Star)
-- Giải luận chi tiết về hình thể, thần thái, hành vi biểu hiện ra bên ngoài
-- Format: {STAR_CODE}_CHU_THAN_{BRIGHTNESS}
-- Priority: 2
-- ============================================================

INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES

-- ============================
-- TỬ VI (TU_VI)
-- ============================

('TU_VI_CHU_THAN_MIEU', 'Tử Vi miếu địa làm Chủ Thân tạo nên hình thể và thần thái có vẻ quyền uy, tự chủ và đầy tự tin. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực trong cách thể hiện bên ngoài, tạo nên phong thái lãnh đạo tự nhiên. Người có Tử Vi miếu địa làm Chủ Thân thường có hình thể đầy đặn, chắc chắn, với thần thái tự tin và có khả năng thu hút sự chú ý của người xung quanh. Cách đi đứng và giao tiếp thể hiện sự cương nghị, quyết đoán, với xu hướng nắm giữ vai trò chủ đạo trong các tình huống xã hội. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng ra quyết định nhanh chóng và chịu trách nhiệm, tạo được ảnh hưởng tích cực đến môi trường xung quanh. Cách tương tác với xã hội thể hiện sự tự chủ cao, có khả năng định hướng và dẫn dắt, với phong thái hành xử thể hiện quyền uy một cách tự nhiên và chính đáng.', 'positive', 2),

('TU_VI_CHU_THAN_VUONG', 'Tử Vi vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ, có khả năng biểu hiện quyền uy và tự chủ một cách rõ ràng. Vượng địa là trạng thái tốt, cho phép Tử Vi phát huy các đặc tính tích cực trong cách thể hiện, tạo nên phong thái lãnh đạo nổi bật. Hình thể có xu hướng chắc chắn, cân đối, với thần thái tự tin và có khả năng tạo ấn tượng mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự cương nghị, với khả năng thu hút sự chú ý và tạo được ảnh hưởng đến người xung quanh. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng ra quyết định và chịu trách nhiệm, với xu hướng nắm giữ vai trò quan trọng trong các hoạt động xã hội. Cách tương tác với xã hội thể hiện sự tự chủ, có khả năng định hướng và dẫn dắt, với phong thái hành xử thể hiện quyền uy và khả năng kiểm soát tình huống một cách hiệu quả.', 'positive', 2),

('TU_VI_CHU_THAN_DAC', 'Tử Vi đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định, có khả năng biểu hiện quyền uy và tự chủ một cách vừa phải. Đắc địa là trạng thái tốt, cho phép Tử Vi phát huy các đặc tính tích cực trong cách thể hiện, tạo nên phong thái lãnh đạo ổn định. Hình thể có xu hướng cân đối, với thần thái tự tin và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự cương nghị vừa phải, với khả năng thu hút sự chú ý và tạo được ảnh hưởng đến môi trường xung quanh. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng ra quyết định và chịu trách nhiệm, với xu hướng đóng vai trò quan trọng trong các tình huống xã hội. Cách tương tác với xã hội thể hiện sự tự chủ, có khả năng định hướng và dẫn dắt, với phong thái hành xử thể hiện quyền uy một cách chính đáng và hiệu quả.', 'positive', 2),

('TU_VI_CHU_THAN_BINH', 'Tử Vi bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình, có khả năng biểu hiện quyền uy và tự chủ một cách vừa phải. Bình địa là trạng thái trung tính, cho phép Tử Vi thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái tự tin ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự cương nghị ở mức vừa phải, với khả năng tạo ảnh hưởng đến môi trường xung quanh nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập ở mức trung bình, có khả năng ra quyết định và chịu trách nhiệm, nhưng cần có sự hỗ trợ hoặc điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự tự chủ ở mức vừa phải, có khả năng định hướng và dẫn dắt khi có điều kiện, với phong thái hành xử thể hiện quyền uy một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('TU_VI_CHU_THAN_HAM', 'Tử Vi hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về quyền uy và tự chủ. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu tự tin hoặc không thể hiện được quyền uy một cách hiệu quả. Hình thể có thể không đầy đặn hoặc thiếu sự chắc chắn, với thần thái có thể thiếu tự tin hoặc không tạo được ấn tượng mạnh mẽ. Cách đi đứng và giao tiếp có thể thiếu sự cương nghị, với khả năng tạo ảnh hưởng đến môi trường xung quanh bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất độc lập, khó khăn trong việc ra quyết định hoặc chịu trách nhiệm một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự tự chủ, khó khăn trong việc định hướng và dẫn dắt, với phong thái hành xử có thể không thể hiện được quyền uy một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THIÊN CƠ (THIEN_CO)
-- ============================

('THIEN_CO_CHU_THAN_MIEU', 'Thiên Cơ miếu địa làm Chủ Thân tạo nên hình thể và thần thái linh hoạt, thông minh và có khả năng thích ứng cao. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về trí tuệ trong cách thể hiện bên ngoài, tạo nên phong thái thông minh và nhạy bén. Người có Thiên Cơ miếu địa làm Chủ Thân thường có hình thể linh hoạt, nhanh nhẹn, với thần thái thông minh và có khả năng quan sát tinh tế. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn, linh hoạt, với xu hướng phản ứng nhanh chóng và có khả năng thích ứng tốt với các tình huống khác nhau. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng suy nghĩ và hành động một cách nhanh chóng, với xu hướng tìm kiếm các giải pháp và cách tiếp cận mới trong các tình huống. Cách tương tác với xã hội thể hiện sự thông minh và linh hoạt, có khả năng nắm bắt cơ hội và tận dụng tốt các tình huống, với phong thái hành xử thể hiện trí tuệ và khả năng thích ứng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_CO_CHU_THAN_VUONG', 'Thiên Cơ vượng địa làm Chủ Thân tạo nên hình thể và thần thái thông minh, linh hoạt và có khả năng phản ứng nhanh chóng. Vượng địa là trạng thái tốt, cho phép Thiên Cơ phát huy các đặc tính tích cực về trí tuệ trong cách thể hiện, tạo nên phong thái thông minh nổi bật. Hình thể có xu hướng linh hoạt, với thần thái thông minh và có khả năng quan sát sâu sắc. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn, với khả năng phản ứng nhanh chóng và có khả năng thích ứng tốt với các tình huống. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng suy nghĩ và hành động một cách nhanh chóng, với xu hướng tìm kiếm các giải pháp hiệu quả. Cách tương tác với xã hội thể hiện sự thông minh và linh hoạt, có khả năng nắm bắt cơ hội và tận dụng tốt các tình huống, với phong thái hành xử thể hiện trí tuệ một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_CO_CHU_THAN_DAC', 'Thiên Cơ đắc địa làm Chủ Thân tạo nên hình thể và thần thái linh hoạt, thông minh và có khả năng thích ứng ở mức tốt. Đắc địa là trạng thái tốt, cho phép Thiên Cơ phát huy các đặc tính tích cực về trí tuệ trong cách thể hiện, tạo nên phong thái thông minh ổn định. Hình thể có xu hướng linh hoạt, với thần thái thông minh và có khả năng quan sát tốt. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn, với khả năng phản ứng và có khả năng thích ứng với các tình huống. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng suy nghĩ và hành động một cách nhanh chóng, với xu hướng tìm kiếm các giải pháp. Cách tương tác với xã hội thể hiện sự thông minh và linh hoạt, có khả năng nắm bắt cơ hội, với phong thái hành xử thể hiện trí tuệ một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_CO_CHU_THAN_BINH', 'Thiên Cơ bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính linh hoạt và thông minh. Bình địa là trạng thái trung tính, cho phép Thiên Cơ thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái thông minh ở mức trung bình, có khả năng quan sát nhưng không quá sâu sắc. Cách đi đứng và giao tiếp thể hiện sự linh hoạt ở mức vừa phải, với khả năng phản ứng và thích ứng với các tình huống nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất năng động ở mức trung bình, có khả năng suy nghĩ và hành động, nhưng cần có thời gian và điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự thông minh và linh hoạt ở mức vừa phải, có khả năng nắm bắt cơ hội khi có điều kiện, với phong thái hành xử thể hiện trí tuệ một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THIEN_CO_CHU_THAN_HAM', 'Thiên Cơ hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về trí tuệ và linh hoạt. Hãm địa là trạng thái bất lợi, khiến Thiên Cơ không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu linh hoạt hoặc không thể hiện được trí tuệ một cách hiệu quả. Hình thể có thể thiếu sự linh hoạt, với thần thái có thể thiếu thông minh hoặc không tạo được ấn tượng về trí tuệ. Cách đi đứng và giao tiếp có thể thiếu sự nhanh nhẹn, với khả năng phản ứng và thích ứng với các tình huống bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất năng động, khó khăn trong việc suy nghĩ và hành động một cách nhanh chóng và hiệu quả. Cách tương tác với xã hội có thể thiếu sự thông minh và linh hoạt, khó khăn trong việc nắm bắt cơ hội, với phong thái hành xử có thể không thể hiện được trí tuệ một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THÁI DƯƠNG (THAI_DUONG)
-- ============================

('THAI_DUONG_CHU_THAN_MIEU', 'Thái Dương miếu địa làm Chủ Thân tạo nên hình thể và thần thái nhiệt tình, quảng đại và có khả năng truyền cảm hứng. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự nhiệt tình trong cách thể hiện bên ngoài, tạo nên phong thái năng động và tích cực. Người có Thái Dương miếu địa làm Chủ Thân thường có hình thể khỏe mạnh, đầy sức sống, với thần thái nhiệt tình và có khả năng tỏa sáng. Cách đi đứng và giao tiếp thể hiện sự tự tin, nhiệt tình, với xu hướng tạo được không khí tích cực và có khả năng truyền cảm hứng đến người xung quanh. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng tạo được ảnh hưởng tích cực đến môi trường xung quanh, với xu hướng đóng vai trò lãnh đạo hoặc có ảnh hưởng trong các hoạt động. Cách tương tác với xã hội thể hiện sự nhiệt tình và quảng đại, có khả năng tạo được sự ngưỡng mộ và ảnh hưởng tích cực, với phong thái hành xử thể hiện sự tỏa sáng và khả năng truyền cảm hứng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_DUONG_CHU_THAN_VUONG', 'Thái Dương vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính nhiệt tình và quảng đại. Vượng địa là trạng thái tốt, cho phép Thái Dương phát huy các đặc tính tích cực về sự nhiệt tình trong cách thể hiện, tạo nên phong thái năng động nổi bật. Hình thể có xu hướng khỏe mạnh, với thần thái nhiệt tình và có khả năng tỏa sáng mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự tự tin, với khả năng tạo được không khí tích cực và có khả năng truyền cảm hứng. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng tạo được ảnh hưởng tích cực đến môi trường xung quanh, với xu hướng có ảnh hưởng trong các hoạt động. Cách tương tác với xã hội thể hiện sự nhiệt tình và quảng đại, có khả năng tạo được sự ngưỡng mộ, với phong thái hành xử thể hiện sự tỏa sáng và khả năng truyền cảm hứng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_DUONG_CHU_THAN_DAC', 'Thái Dương đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính nhiệt tình và quảng đại. Đắc địa là trạng thái tốt, cho phép Thái Dương phát huy các đặc tính tích cực về sự nhiệt tình trong cách thể hiện, tạo nên phong thái năng động ổn định. Hình thể có xu hướng khỏe mạnh, với thần thái nhiệt tình và có khả năng tỏa sáng. Cách đi đứng và giao tiếp thể hiện sự tự tin, với khả năng tạo được không khí tích cực. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng tạo được ảnh hưởng tích cực đến môi trường xung quanh. Cách tương tác với xã hội thể hiện sự nhiệt tình và quảng đại, có khả năng tạo được sự ngưỡng mộ, với phong thái hành xử thể hiện sự tỏa sáng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_DUONG_CHU_THAN_BINH', 'Thái Dương bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính nhiệt tình và quảng đại. Bình địa là trạng thái trung tính, cho phép Thái Dương thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái nhiệt tình ở mức trung bình, có khả năng tỏa sáng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự tự tin ở mức vừa phải, với khả năng tạo được không khí tích cực nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất năng động ở mức trung bình, có khả năng tạo được ảnh hưởng tích cực nhưng cần có điều kiện. Cách tương tác với xã hội thể hiện sự nhiệt tình và quảng đại ở mức vừa phải, có khả năng tạo được sự ngưỡng mộ khi có điều kiện, với phong thái hành xử thể hiện sự tỏa sáng một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THAI_DUONG_CHU_THAN_HAM', 'Thái Dương hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về sự nhiệt tình và quảng đại. Hãm địa là trạng thái bất lợi, khiến Thái Dương không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu nhiệt tình hoặc không thể hiện được sự tỏa sáng một cách hiệu quả. Hình thể có thể thiếu sự khỏe mạnh, với thần thái có thể thiếu nhiệt tình hoặc không tạo được ấn tượng về sự tỏa sáng. Cách đi đứng và giao tiếp có thể thiếu sự tự tin, với khả năng tạo được không khí tích cực bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất năng động, khó khăn trong việc tạo được ảnh hưởng tích cực đến môi trường xung quanh một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự nhiệt tình và quảng đại, khó khăn trong việc tạo được sự ngưỡng mộ, với phong thái hành xử có thể không thể hiện được sự tỏa sáng một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- VŨ KHÚC (VU_KHUC)
-- ============================

('VU_KHUC_CHU_THAN_MIEU', 'Vũ Khúc miếu địa làm Chủ Thân tạo nên hình thể và thần thái thể hiện khả năng quản lý tài chính và tính toán một cách hiệu quả. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về tài chính trong cách thể hiện bên ngoài, tạo nên phong thái cẩn trọng và có tính toán. Người có Vũ Khúc miếu địa làm Chủ Thân thường có hình thể chắc chắn, cân đối, với thần thái tự tin và có khả năng tạo ấn tượng về sự ổn định tài chính. Cách đi đứng và giao tiếp thể hiện sự cẩn thận, có tính toán, với xu hướng đưa ra quyết định một cách thận trọng và có kế hoạch. Hành vi biểu hiện ra bên ngoài mang tính chất quản lý tốt, có khả năng tích lũy và quản lý tài sản một cách hiệu quả, với xu hướng thể hiện sự ổn định về mặt tài chính trong các hoạt động. Cách tương tác với xã hội thể hiện sự cẩn trọng và có tính toán, có khả năng tạo được ấn tượng về sự ổn định và khả năng quản lý tài chính, với phong thái hành xử thể hiện sự tích lũy và quản lý tài sản một cách tự nhiên và hiệu quả.', 'positive', 2),

('VU_KHUC_CHU_THAN_VUONG', 'Vũ Khúc vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về khả năng quản lý tài chính và tính toán. Vượng địa là trạng thái tốt, cho phép Vũ Khúc phát huy các đặc tính tích cực về tài chính trong cách thể hiện, tạo nên phong thái quản lý tài chính nổi bật. Hình thể có xu hướng chắc chắn, với thần thái tự tin và có khả năng tạo ấn tượng về sự ổn định. Cách đi đứng và giao tiếp thể hiện sự cẩn thận, với khả năng đưa ra quyết định một cách thận trọng. Hành vi biểu hiện ra bên ngoài mang tính chất quản lý tốt, có khả năng tích lũy và quản lý tài sản, với xu hướng thể hiện sự ổn định về mặt tài chính. Cách tương tác với xã hội thể hiện sự cẩn trọng và có tính toán, có khả năng tạo được ấn tượng về sự ổn định, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên và hiệu quả.', 'positive', 2),

('VU_KHUC_CHU_THAN_DAC', 'Vũ Khúc đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về khả năng quản lý tài chính và tính toán. Đắc địa là trạng thái tốt, cho phép Vũ Khúc phát huy các đặc tính tích cực về tài chính trong cách thể hiện, tạo nên phong thái quản lý tài chính ổn định. Hình thể có xu hướng cân đối, với thần thái tự tin và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự cẩn thận vừa phải, với khả năng đưa ra quyết định một cách cân nhắc. Hành vi biểu hiện ra bên ngoài mang tính chất quản lý tốt, có khả năng tích lũy và quản lý tài sản, với xu hướng thể hiện sự ổn định. Cách tương tác với xã hội thể hiện sự cẩn trọng, có khả năng tạo được ấn tượng về sự ổn định, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên và hiệu quả.', 'positive', 2),

('VU_KHUC_CHU_THAN_BINH', 'Vũ Khúc bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về khả năng quản lý tài chính và tính toán. Bình địa là trạng thái trung tính, cho phép Vũ Khúc thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái tự tin ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự cẩn thận ở mức vừa phải, với khả năng đưa ra quyết định nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất quản lý ở mức trung bình, có khả năng tích lũy và quản lý tài sản, nhưng cần có sự hỗ trợ hoặc điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự cẩn trọng ở mức vừa phải, có khả năng tạo được ấn tượng về sự ổn định khi có điều kiện, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('VU_KHUC_CHU_THAN_HAM', 'Vũ Khúc hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về khả năng quản lý tài chính và tính toán. Hãm địa là trạng thái bất lợi, khiến Vũ Khúc không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu cẩn trọng hoặc không thể hiện được khả năng quản lý tài chính một cách hiệu quả. Hình thể có thể thiếu sự chắc chắn, với thần thái có thể thiếu tự tin hoặc không tạo được ấn tượng về sự ổn định tài chính. Cách đi đứng và giao tiếp có thể thiếu sự cẩn thận, với khả năng đưa ra quyết định tài chính không đủ thận trọng. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất quản lý tốt, khó khăn trong việc tích lũy và quản lý tài sản một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự cẩn trọng, khó khăn trong việc tạo được ấn tượng về sự ổn định tài chính, với phong thái hành xử có thể không thể hiện được khả năng quản lý tài chính một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THIÊN ĐỒNG (THIEN_DONG)
-- ============================

('THIEN_DONG_CHU_THAN_MIEU', 'Thiên Đồng miếu địa làm Chủ Thân tạo nên hình thể và thần thái vui vẻ, hòa đồng và có khả năng tạo được mối quan hệ tốt một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự vui vẻ trong cách thể hiện bên ngoài, tạo nên phong thái lạc quan và hòa đồng. Người có Thiên Đồng miếu địa làm Chủ Thân thường có hình thể cân đối, dễ thương, với thần thái vui vẻ và có khả năng tạo ấn tượng tích cực với người xung quanh. Cách đi đứng và giao tiếp thể hiện sự thân thiện, vui vẻ, với xu hướng tạo được không khí tích cực và thu hút người khác. Hành vi biểu hiện ra bên ngoài mang tính chất cởi mở, có khả năng giao tiếp và kết nối tốt, với xu hướng tạo được sự hòa hợp và vui vẻ trong các mối quan hệ. Cách tương tác với xã hội thể hiện sự vui vẻ và hòa đồng, có khả năng tạo được mối quan hệ tốt và tạo được sự vui vẻ cho môi trường xung quanh, với phong thái hành xử thể hiện sự lạc quan và khả năng kết nối một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_DONG_CHU_THAN_VUONG', 'Thiên Đồng vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính vui vẻ và hòa đồng. Vượng địa là trạng thái tốt, cho phép Thiên Đồng phát huy các đặc tính tích cực về sự vui vẻ trong cách thể hiện, tạo nên phong thái lạc quan nổi bật. Hình thể có xu hướng cân đối, với thần thái vui vẻ và có khả năng tạo ấn tượng tích cực mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự thân thiện, với khả năng tạo được không khí tích cực và thu hút người khác. Hành vi biểu hiện ra bên ngoài mang tính chất cởi mở, có khả năng giao tiếp và kết nối, với xu hướng tạo được sự hòa hợp. Cách tương tác với xã hội thể hiện sự vui vẻ và hòa đồng, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự lạc quan một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_DONG_CHU_THAN_DAC', 'Thiên Đồng đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính vui vẻ và hòa đồng. Đắc địa là trạng thái tốt, cho phép Thiên Đồng phát huy các đặc tính tích cực về sự vui vẻ trong cách thể hiện, tạo nên phong thái lạc quan ổn định. Hình thể có xu hướng cân đối, với thần thái vui vẻ và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự thân thiện, với khả năng tạo được không khí tích cực. Hành vi biểu hiện ra bên ngoài mang tính chất cởi mở, có khả năng giao tiếp và kết nối, với xu hướng tạo được sự hòa hợp. Cách tương tác với xã hội thể hiện sự vui vẻ và hòa đồng, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự lạc quan một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_DONG_CHU_THAN_BINH', 'Thiên Đồng bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính vui vẻ và hòa đồng. Bình địa là trạng thái trung tính, cho phép Thiên Đồng thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái vui vẻ ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự thân thiện ở mức vừa phải, với khả năng tạo được không khí tích cực nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất cởi mở ở mức trung bình, có khả năng giao tiếp và kết nối, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự vui vẻ và hòa đồng ở mức vừa phải, có khả năng tạo được mối quan hệ tốt khi có điều kiện, với phong thái hành xử thể hiện sự lạc quan một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THIEN_DONG_CHU_THAN_HAM', 'Thiên Đồng hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính vui vẻ và hòa đồng. Hãm địa là trạng thái bất lợi, khiến Thiên Đồng không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu vui vẻ hoặc không thể hiện được sự hòa đồng một cách hiệu quả. Hình thể có thể thiếu sự cân đối, với thần thái có thể thiếu vui vẻ hoặc không tạo được ấn tượng tích cực. Cách đi đứng và giao tiếp có thể thiếu sự thân thiện, với khả năng tạo được không khí tích cực bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất cởi mở, khó khăn trong việc giao tiếp và kết nối một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự vui vẻ và hòa đồng, khó khăn trong việc tạo được mối quan hệ tốt, với phong thái hành xử có thể không thể hiện được sự lạc quan một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- LIÊM TRINH (LIEM_TRINH)
-- ============================

('LIEM_TRINH_CHU_THAN_MIEU', 'Liêm Trinh miếu địa làm Chủ Thân tạo nên hình thể và thần thái thanh cao, trung thực và có khả năng giữ gìn danh dự một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự thanh cao trong cách thể hiện bên ngoài, tạo nên phong thái chính trực và đáng kính. Người có Liêm Trinh miếu địa làm Chủ Thân thường có hình thể thanh tú, cao quý, với thần thái chính trực và có khả năng tạo ấn tượng về sự đáng tin cậy. Cách đi đứng và giao tiếp thể hiện sự cứng rắn trong các nguyên tắc, chính trực, với xu hướng giữ gìn đạo đức và danh dự một cách nghiêm túc. Hành vi biểu hiện ra bên ngoài mang tính chất thanh cao, có khả năng đứng lên cho những gì tin tưởng, với xu hướng không dễ dàng thỏa hiệp với những gì trái với nguyên tắc. Cách tương tác với xã hội thể hiện sự thanh cao và trung thực, có khả năng tạo được sự tôn trọng từ người khác, với phong thái hành xử thể hiện sự chính trực và khả năng giữ gìn đạo đức một cách tự nhiên và hiệu quả.', 'positive', 2),

('LIEM_TRINH_CHU_THAN_VUONG', 'Liêm Trinh vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính thanh cao và trung thực. Vượng địa là trạng thái tốt, cho phép Liêm Trinh phát huy các đặc tính tích cực về sự thanh cao trong cách thể hiện, tạo nên phong thái chính trực nổi bật. Hình thể có xu hướng thanh tú, với thần thái chính trực và có khả năng tạo ấn tượng mạnh mẽ về sự đáng tin cậy. Cách đi đứng và giao tiếp thể hiện sự cứng rắn, với khả năng giữ gìn đạo đức và danh dự. Hành vi biểu hiện ra bên ngoài mang tính chất thanh cao, có khả năng đứng lên cho những gì tin tưởng, với xu hướng không thỏa hiệp với những gì trái với nguyên tắc. Cách tương tác với xã hội thể hiện sự thanh cao và trung thực, có khả năng tạo được sự tôn trọng, với phong thái hành xử thể hiện sự chính trực một cách tự nhiên và hiệu quả.', 'positive', 2),

('LIEM_TRINH_CHU_THAN_DAC', 'Liêm Trinh đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính thanh cao và trung thực. Đắc địa là trạng thái tốt, cho phép Liêm Trinh phát huy các đặc tính tích cực về sự thanh cao trong cách thể hiện, tạo nên phong thái chính trực ổn định. Hình thể có xu hướng thanh tú, với thần thái chính trực và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự cứng rắn vừa phải, với khả năng giữ gìn đạo đức và danh dự. Hành vi biểu hiện ra bên ngoài mang tính chất thanh cao, có khả năng đứng lên cho những gì tin tưởng, với xu hướng giữ gìn nguyên tắc. Cách tương tác với xã hội thể hiện sự thanh cao và trung thực, có khả năng tạo được sự tôn trọng, với phong thái hành xử thể hiện sự chính trực một cách tự nhiên và hiệu quả.', 'positive', 2),

('LIEM_TRINH_CHU_THAN_BINH', 'Liêm Trinh bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính thanh cao và trung thực. Bình địa là trạng thái trung tính, cho phép Liêm Trinh thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái chính trực ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự cứng rắn ở mức vừa phải, với khả năng giữ gìn đạo đức nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất thanh cao ở mức trung bình, có khả năng đứng lên cho những gì tin tưởng, nhưng cần có sự hỗ trợ hoặc điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự thanh cao và trung thực ở mức vừa phải, có khả năng tạo được sự tôn trọng khi có điều kiện, với phong thái hành xử thể hiện sự chính trực một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('LIEM_TRINH_CHU_THAN_HAM', 'Liêm Trinh hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính thanh cao và trung thực. Hãm địa là trạng thái bất lợi, khiến Liêm Trinh không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu thanh cao hoặc không thể hiện được sự chính trực một cách hiệu quả. Hình thể có thể thiếu sự thanh tú, với thần thái có thể thiếu chính trực hoặc không tạo được ấn tượng về sự đáng tin cậy. Cách đi đứng và giao tiếp có thể thiếu sự cứng rắn, với khả năng giữ gìn đạo đức và danh dự bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất thanh cao, khó khăn trong việc đứng lên cho những gì tin tưởng một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự thanh cao và trung thực, khó khăn trong việc tạo được sự tôn trọng, với phong thái hành xử có thể không thể hiện được sự chính trực một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THIÊN PHỦ (THIEN_PHU)
-- ============================

('THIEN_PHU_CHU_THAN_MIEU', 'Thiên Phủ miếu địa làm Chủ Thân tạo nên hình thể và thần thái phú có, tích trữ và có khả năng quản lý một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự tích lũy trong cách thể hiện bên ngoài, tạo nên phong thái ổn định và có tổ chức. Người có Thiên Phủ miếu địa làm Chủ Thân thường có hình thể đầy đặn, ổn định, với thần thái tự tin và có khả năng tạo ấn tượng về sự phú có và tích lũy. Cách đi đứng và giao tiếp thể hiện sự khoan hòa, ổn định, với xu hướng tổ chức và quản lý một cách có hệ thống. Hành vi biểu hiện ra bên ngoài mang tính chất tích lũy tốt, có khả năng xây dựng nền tảng vững chắc, với xu hướng tạo được mối quan hệ tốt và tạo dựng sự ổn định. Cách tương tác với xã hội thể hiện sự khoan hòa và có khả năng quản lý, có khả năng tạo được sự tin cậy và nền tảng vững chắc, với phong thái hành xử thể hiện sự tích lũy và quản lý tài sản một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_PHU_CHU_THAN_VUONG', 'Thiên Phủ vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính phú có và tích trữ. Vượng địa là trạng thái tốt, cho phép Thiên Phủ phát huy các đặc tính tích cực về sự tích lũy trong cách thể hiện, tạo nên phong thái ổn định nổi bật. Hình thể có xu hướng đầy đặn, với thần thái tự tin và có khả năng tạo ấn tượng mạnh mẽ về sự phú có. Cách đi đứng và giao tiếp thể hiện sự khoan hòa, với khả năng tổ chức và quản lý. Hành vi biểu hiện ra bên ngoài mang tính chất tích lũy tốt, có khả năng xây dựng nền tảng vững chắc, với xu hướng tạo được mối quan hệ tốt. Cách tương tác với xã hội thể hiện sự khoan hòa và có khả năng quản lý, có khả năng tạo được sự tin cậy, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_PHU_CHU_THAN_DAC', 'Thiên Phủ đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính phú có và tích trữ. Đắc địa là trạng thái tốt, cho phép Thiên Phủ phát huy các đặc tính tích cực về sự tích lũy trong cách thể hiện, tạo nên phong thái ổn định ổn định. Hình thể có xu hướng đầy đặn, với thần thái tự tin và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự khoan hòa vừa phải, với khả năng tổ chức và quản lý. Hành vi biểu hiện ra bên ngoài mang tính chất tích lũy tốt, có khả năng xây dựng nền tảng vững chắc, với xu hướng tạo được mối quan hệ tốt. Cách tương tác với xã hội thể hiện sự khoan hòa và có khả năng quản lý, có khả năng tạo được sự tin cậy, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_PHU_CHU_THAN_BINH', 'Thiên Phủ bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính phú có và tích trữ. Bình địa là trạng thái trung tính, cho phép Thiên Phủ thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái tự tin ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự khoan hòa ở mức vừa phải, với khả năng tổ chức và quản lý nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất tích lũy ở mức trung bình, có khả năng xây dựng nền tảng, nhưng cần có sự hỗ trợ hoặc điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự khoan hòa và có khả năng quản lý ở mức vừa phải, có khả năng tạo được sự tin cậy khi có điều kiện, với phong thái hành xử thể hiện sự tích lũy một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THIEN_PHU_CHU_THAN_HAM', 'Thiên Phủ hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính phú có và tích trữ. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu tích lũy hoặc không thể hiện được khả năng quản lý một cách hiệu quả. Hình thể có thể thiếu sự đầy đặn, với thần thái có thể thiếu tự tin hoặc không tạo được ấn tượng về sự phú có. Cách đi đứng và giao tiếp có thể thiếu sự khoan hòa, với khả năng tổ chức và quản lý bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất tích lũy tốt, khó khăn trong việc xây dựng nền tảng vững chắc một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự khoan hòa và có khả năng quản lý, khó khăn trong việc tạo được sự tin cậy, với phong thái hành xử có thể không thể hiện được khả năng tích lũy một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THÁI ÂM (THAI_AM)
-- ============================

('THAI_AM_CHU_THAN_MIEU', 'Thái Âm miếu địa làm Chủ Thân tạo nên hình thể và thần thái nhân từ, hòa nhã và có khả năng cảm thông một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự nhân từ trong cách thể hiện bên ngoài, tạo nên phong thái dịu dàng và hòa hợp. Người có Thái Âm miếu địa làm Chủ Thân thường có hình thể mềm mại, dịu dàng, với thần thái nhân từ và có khả năng tạo ấn tượng về sự hòa nhã và cảm thông. Cách đi đứng và giao tiếp thể hiện sự dịu dàng, hòa nhã, với xu hướng lắng nghe và thấu hiểu người khác một cách tự nhiên. Hành vi biểu hiện ra bên ngoài mang tính chất mềm mỏng, có khả năng tạo được sự hòa hợp trong các mối quan hệ, với xu hướng giải quyết xung đột một cách nhẹ nhàng và hiệu quả. Cách tương tác với xã hội thể hiện sự nhân từ và hòa nhã, có khả năng tạo được mối quan hệ tốt và tạo được sự tin cậy từ người khác, với phong thái hành xử thể hiện sự dịu dàng và khả năng cảm thông một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_AM_CHU_THAN_VUONG', 'Thái Âm vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính nhân từ và hòa nhã. Vượng địa là trạng thái tốt, cho phép Thái Âm phát huy các đặc tính tích cực về sự nhân từ trong cách thể hiện, tạo nên phong thái dịu dàng nổi bật. Hình thể có xu hướng mềm mại, với thần thái nhân từ và có khả năng tạo ấn tượng mạnh mẽ về sự hòa nhã. Cách đi đứng và giao tiếp thể hiện sự dịu dàng, với khả năng lắng nghe và thấu hiểu. Hành vi biểu hiện ra bên ngoài mang tính chất mềm mỏng, có khả năng tạo được sự hòa hợp, với xu hướng giải quyết xung đột một cách hiệu quả. Cách tương tác với xã hội thể hiện sự nhân từ và hòa nhã, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự dịu dàng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_AM_CHU_THAN_DAC', 'Thái Âm đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính nhân từ và hòa nhã. Đắc địa là trạng thái tốt, cho phép Thái Âm phát huy các đặc tính tích cực về sự nhân từ trong cách thể hiện, tạo nên phong thái dịu dàng ổn định. Hình thể có xu hướng mềm mại, với thần thái nhân từ và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự dịu dàng vừa phải, với khả năng lắng nghe và thấu hiểu. Hành vi biểu hiện ra bên ngoài mang tính chất mềm mỏng, có khả năng tạo được sự hòa hợp, với xu hướng giải quyết xung đột. Cách tương tác với xã hội thể hiện sự nhân từ và hòa nhã, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự dịu dàng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAI_AM_CHU_THAN_BINH', 'Thái Âm bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính nhân từ và hòa nhã. Bình địa là trạng thái trung tính, cho phép Thái Âm thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái nhân từ ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự dịu dàng ở mức vừa phải, với khả năng lắng nghe và thấu hiểu nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất mềm mỏng ở mức trung bình, có khả năng tạo được sự hòa hợp, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự nhân từ và hòa nhã ở mức vừa phải, có khả năng tạo được mối quan hệ tốt khi có điều kiện, với phong thái hành xử thể hiện sự dịu dàng một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THAI_AM_CHU_THAN_HAM', 'Thái Âm hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính nhân từ và hòa nhã. Hãm địa là trạng thái bất lợi, khiến Thái Âm không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu nhân từ hoặc không thể hiện được sự hòa nhã một cách hiệu quả. Hình thể có thể thiếu sự mềm mại, với thần thái có thể thiếu nhân từ hoặc không tạo được ấn tượng về sự hòa nhã. Cách đi đứng và giao tiếp có thể thiếu sự dịu dàng, với khả năng lắng nghe và thấu hiểu bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất mềm mỏng, khó khăn trong việc tạo được sự hòa hợp một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự nhân từ và hòa nhã, khó khăn trong việc tạo được mối quan hệ tốt, với phong thái hành xử có thể không thể hiện được sự dịu dàng một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THAM LANG (THAM_LANG)
-- ============================

('THAM_LANG_CHU_THAN_MIEU', 'Tham Lang miếu địa làm Chủ Thân tạo nên hình thể và thần thái thông minh, tài trí và có khả năng kinh doanh một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về trí tuệ trong cách thể hiện bên ngoài, tạo nên phong thái thông minh và tính toán. Người có Tham Lang miếu địa làm Chủ Thân thường có hình thể linh hoạt, thông minh, với thần thái lanh lợi và có khả năng tạo ấn tượng về sự tài trí và khả năng tính toán. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn, tính toán, với xu hướng nắm bắt cơ hội và tận dụng tốt các tình huống một cách tự nhiên. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng giao tiếp và đàm phán tốt, với xu hướng tìm kiếm cơ hội và phát triển trong các lĩnh vực liên quan đến kinh doanh và thương mại. Cách tương tác với xã hội thể hiện sự thông minh và tài trí, có khả năng tạo được mối quan hệ tốt và tận dụng tốt các cơ hội, với phong thái hành xử thể hiện sự lanh lợi và khả năng tính toán một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAM_LANG_CHU_THAN_VUONG', 'Tham Lang vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính thông minh và tài trí. Vượng địa là trạng thái tốt, cho phép Tham Lang phát huy các đặc tính tích cực về trí tuệ trong cách thể hiện, tạo nên phong thái thông minh nổi bật. Hình thể có xu hướng linh hoạt, với thần thái lanh lợi và có khả năng tạo ấn tượng mạnh mẽ về sự tài trí. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn, với khả năng nắm bắt cơ hội và tính toán. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng giao tiếp và đàm phán, với xu hướng tìm kiếm cơ hội. Cách tương tác với xã hội thể hiện sự thông minh và tài trí, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự lanh lợi một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAM_LANG_CHU_THAN_DAC', 'Tham Lang đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính thông minh và tài trí. Đắc địa là trạng thái tốt, cho phép Tham Lang phát huy các đặc tính tích cực về trí tuệ trong cách thể hiện, tạo nên phong thái thông minh ổn định. Hình thể có xu hướng linh hoạt, với thần thái lanh lợi và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn vừa phải, với khả năng nắm bắt cơ hội và tính toán. Hành vi biểu hiện ra bên ngoài mang tính chất năng động, có khả năng giao tiếp và đàm phán, với xu hướng tìm kiếm cơ hội. Cách tương tác với xã hội thể hiện sự thông minh và tài trí, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự lanh lợi một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAM_LANG_CHU_THAN_BINH', 'Tham Lang bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính thông minh và tài trí. Bình địa là trạng thái trung tính, cho phép Tham Lang thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái lanh lợi ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự nhanh nhẹn ở mức vừa phải, với khả năng nắm bắt cơ hội và tính toán nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất năng động ở mức trung bình, có khả năng giao tiếp và đàm phán, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự thông minh và tài trí ở mức vừa phải, có khả năng tạo được mối quan hệ tốt khi có điều kiện, với phong thái hành xử thể hiện sự lanh lợi một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THAM_LANG_CHU_THAN_HAM', 'Tham Lang hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính thông minh và tài trí. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu thông minh hoặc không thể hiện được tài trí một cách hiệu quả. Hình thể có thể thiếu sự linh hoạt, với thần thái có thể thiếu lanh lợi hoặc không tạo được ấn tượng về sự tài trí. Cách đi đứng và giao tiếp có thể thiếu sự nhanh nhẹn, với khả năng nắm bắt cơ hội và tính toán bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất năng động, khó khăn trong việc giao tiếp và đàm phán một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự thông minh và tài trí, khó khăn trong việc tạo được mối quan hệ tốt, với phong thái hành xử có thể không thể hiện được sự lanh lợi một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- CỰ MÔN (CU_MON)
-- ============================

('CU_MON_CHU_THAN_MIEU', 'Cự Môn miếu địa làm Chủ Thân tạo nên hình thể và thần thái thể hiện khả năng giao tiếp, học hỏi và kiến thức một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về giao tiếp trong cách thể hiện bên ngoài, tạo nên phong thái biểu cảm và truyền đạt tốt. Người có Cự Môn miếu địa làm Chủ Thân thường có hình thể rõ ràng, biểu cảm, với thần thái thông minh và có khả năng tạo ấn tượng về sự học hỏi và kiến thức. Cách đi đứng và giao tiếp thể hiện sự nói nhiều, giao tiếp tốt, với xu hướng truyền đạt ý tưởng và kiến thức một cách rõ ràng và hiệu quả. Hành vi biểu hiện ra bên ngoài mang tính chất giao tiếp tốt, có khả năng học hỏi và tích lũy kiến thức, với xu hướng thể hiện sự hiểu biết và khả năng truyền đạt trong các hoạt động. Cách tương tác với xã hội thể hiện sự giao tiếp và học hỏi, có khả năng tạo được mối quan hệ tốt thông qua khả năng truyền đạt, với phong thái hành xử thể hiện sự biểu cảm và khả năng giao tiếp một cách tự nhiên và hiệu quả.', 'positive', 2),

('CU_MON_CHU_THAN_VUONG', 'Cự Môn vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về khả năng giao tiếp và học hỏi. Vượng địa là trạng thái tốt, cho phép Cự Môn phát huy các đặc tính tích cực về giao tiếp trong cách thể hiện, tạo nên phong thái biểu cảm nổi bật. Hình thể có xu hướng rõ ràng, với thần thái thông minh và có khả năng tạo ấn tượng mạnh mẽ về sự học hỏi. Cách đi đứng và giao tiếp thể hiện sự giao tiếp tốt, với khả năng truyền đạt ý tưởng một cách hiệu quả. Hành vi biểu hiện ra bên ngoài mang tính chất giao tiếp tốt, có khả năng học hỏi và tích lũy kiến thức, với xu hướng thể hiện sự hiểu biết. Cách tương tác với xã hội thể hiện sự giao tiếp và học hỏi, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự biểu cảm một cách tự nhiên và hiệu quả.', 'positive', 2),

('CU_MON_CHU_THAN_DAC', 'Cự Môn đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về khả năng giao tiếp và học hỏi. Đắc địa là trạng thái tốt, cho phép Cự Môn phát huy các đặc tính tích cực về giao tiếp trong cách thể hiện, tạo nên phong thái biểu cảm ổn định. Hình thể có xu hướng rõ ràng, với thần thái thông minh và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự giao tiếp vừa phải, với khả năng truyền đạt ý tưởng. Hành vi biểu hiện ra bên ngoài mang tính chất giao tiếp tốt, có khả năng học hỏi và tích lũy kiến thức, với xu hướng thể hiện sự hiểu biết. Cách tương tác với xã hội thể hiện sự giao tiếp và học hỏi, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự biểu cảm một cách tự nhiên và hiệu quả.', 'positive', 2),

('CU_MON_CHU_THAN_BINH', 'Cự Môn bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về khả năng giao tiếp và học hỏi. Bình địa là trạng thái trung tính, cho phép Cự Môn thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái thông minh ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự giao tiếp ở mức vừa phải, với khả năng truyền đạt ý tưởng nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất giao tiếp ở mức trung bình, có khả năng học hỏi và tích lũy kiến thức, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự giao tiếp và học hỏi ở mức vừa phải, có khả năng tạo được mối quan hệ tốt khi có điều kiện, với phong thái hành xử thể hiện sự biểu cảm một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('CU_MON_CHU_THAN_HAM', 'Cự Môn hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về khả năng giao tiếp và học hỏi. Hãm địa là trạng thái bất lợi, khiến Cự Môn không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu giao tiếp hoặc không thể hiện được khả năng học hỏi một cách hiệu quả. Hình thể có thể thiếu sự rõ ràng, với thần thái có thể thiếu thông minh hoặc không tạo được ấn tượng về sự học hỏi. Cách đi đứng và giao tiếp có thể thiếu sự giao tiếp tốt, với khả năng truyền đạt ý tưởng bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất giao tiếp tốt, khó khăn trong việc học hỏi và tích lũy kiến thức một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự giao tiếp và học hỏi, khó khăn trong việc tạo được mối quan hệ tốt, với phong thái hành xử có thể không thể hiện được khả năng biểu cảm một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THIÊN TƯỚNG (THIEN_TUONG)
-- ============================

('THIEN_TUONG_CHU_THAN_MIEU', 'Thiên Tướng miếu địa làm Chủ Thân tạo nên hình thể và thần thái hỗ trợ, bảo vệ và có khả năng tạo nền tảng vững chắc một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự hỗ trợ trong cách thể hiện bên ngoài, tạo nên phong thái ổn định và đáng tin cậy. Người có Thiên Tướng miếu địa làm Chủ Thân thường có hình thể vững chắc, đáng tin, với thần thái ổn định và có khả năng tạo ấn tượng về sự hỗ trợ và bảo vệ. Cách đi đứng và giao tiếp thể hiện sự ổn định, đáng tin cậy, với xu hướng tạo được sự yên tâm và nền tảng vững chắc cho người xung quanh. Hành vi biểu hiện ra bên ngoài mang tính chất hỗ trợ tốt, có khả năng tạo được sự tin cậy và nền tảng vững chắc, với xu hướng đóng vai trò hỗ trợ hoặc tạo nền tảng cho các hoạt động. Cách tương tác với xã hội thể hiện sự ổn định và đáng tin cậy, có khả năng tạo được sự yên tâm và nền tảng vững chắc, với phong thái hành xử thể hiện sự hỗ trợ và khả năng tạo nền tảng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_TUONG_CHU_THAN_VUONG', 'Thiên Tướng vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính hỗ trợ và bảo vệ. Vượng địa là trạng thái tốt, cho phép Thiên Tướng phát huy các đặc tính tích cực về sự hỗ trợ trong cách thể hiện, tạo nên phong thái ổn định nổi bật. Hình thể có xu hướng vững chắc, với thần thái ổn định và có khả năng tạo ấn tượng mạnh mẽ về sự đáng tin cậy. Cách đi đứng và giao tiếp thể hiện sự ổn định, với khả năng tạo được sự yên tâm. Hành vi biểu hiện ra bên ngoài mang tính chất hỗ trợ tốt, có khả năng tạo được sự tin cậy và nền tảng vững chắc, với xu hướng đóng vai trò hỗ trợ. Cách tương tác với xã hội thể hiện sự ổn định và đáng tin cậy, có khả năng tạo được sự yên tâm, với phong thái hành xử thể hiện sự hỗ trợ một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_TUONG_CHU_THAN_DAC', 'Thiên Tướng đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính hỗ trợ và bảo vệ. Đắc địa là trạng thái tốt, cho phép Thiên Tướng phát huy các đặc tính tích cực về sự hỗ trợ trong cách thể hiện, tạo nên phong thái ổn định ổn định. Hình thể có xu hướng vững chắc, với thần thái ổn định và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự ổn định vừa phải, với khả năng tạo được sự yên tâm. Hành vi biểu hiện ra bên ngoài mang tính chất hỗ trợ tốt, có khả năng tạo được sự tin cậy và nền tảng vững chắc, với xu hướng đóng vai trò hỗ trợ. Cách tương tác với xã hội thể hiện sự ổn định và đáng tin cậy, có khả năng tạo được sự yên tâm, với phong thái hành xử thể hiện sự hỗ trợ một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_TUONG_CHU_THAN_BINH', 'Thiên Tướng bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính hỗ trợ và bảo vệ. Bình địa là trạng thái trung tính, cho phép Thiên Tướng thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái ổn định ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự ổn định ở mức vừa phải, với khả năng tạo được sự yên tâm nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất hỗ trợ ở mức trung bình, có khả năng tạo được sự tin cậy, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự ổn định và đáng tin cậy ở mức vừa phải, có khả năng tạo được sự yên tâm khi có điều kiện, với phong thái hành xử thể hiện sự hỗ trợ một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THIEN_TUONG_CHU_THAN_HAM', 'Thiên Tướng hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính hỗ trợ và bảo vệ. Hãm địa là trạng thái bất lợi, khiến Thiên Tướng không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu ổn định hoặc không thể hiện được khả năng hỗ trợ một cách hiệu quả. Hình thể có thể thiếu sự vững chắc, với thần thái có thể thiếu ổn định hoặc không tạo được ấn tượng về sự đáng tin cậy. Cách đi đứng và giao tiếp có thể thiếu sự ổn định, với khả năng tạo được sự yên tâm bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất hỗ trợ tốt, khó khăn trong việc tạo được sự tin cậy và nền tảng vững chắc một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự ổn định và đáng tin cậy, khó khăn trong việc tạo được sự yên tâm, với phong thái hành xử có thể không thể hiện được khả năng hỗ trợ một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THIÊN LƯƠNG (THIEN_LUONG)
-- ============================

('THIEN_LUONG_CHU_THAN_MIEU', 'Thiên Lương miếu địa làm Chủ Thân tạo nên hình thể và thần thái nhân từ, từ thiện và có khả năng giúp đỡ người khác một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự nhân từ trong cách thể hiện bên ngoài, tạo nên phong thái tốt bụng và từ thiện. Người có Thiên Lương miếu địa làm Chủ Thân thường có hình thể hòa nhã, dễ gần, với thần thái nhân từ và có khả năng tạo ấn tượng về sự từ thiện và khả năng giúp đỡ. Cách đi đứng và giao tiếp thể hiện sự dịu dàng, tốt bụng, với xu hướng lắng nghe và hỗ trợ người khác một cách tự nhiên và chân thành. Hành vi biểu hiện ra bên ngoài mang tính chất nhân từ, có khả năng giúp đỡ và hỗ trợ người khác, với xu hướng tạo được sự hòa hợp và tin cậy trong các mối quan hệ. Cách tương tác với xã hội thể hiện sự nhân từ và từ thiện, có khả năng tạo được mối quan hệ tốt và ảnh hưởng tích cực, với phong thái hành xử thể hiện sự tốt bụng và khả năng giúp đỡ một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_LUONG_CHU_THAN_VUONG', 'Thiên Lương vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính nhân từ và từ thiện. Vượng địa là trạng thái tốt, cho phép Thiên Lương phát huy các đặc tính tích cực về sự nhân từ trong cách thể hiện, tạo nên phong thái tốt bụng nổi bật. Hình thể có xu hướng hòa nhã, với thần thái nhân từ và có khả năng tạo ấn tượng mạnh mẽ về sự từ thiện. Cách đi đứng và giao tiếp thể hiện sự dịu dàng, với khả năng lắng nghe và hỗ trợ. Hành vi biểu hiện ra bên ngoài mang tính chất nhân từ, có khả năng giúp đỡ và hỗ trợ người khác, với xu hướng tạo được sự hòa hợp. Cách tương tác với xã hội thể hiện sự nhân từ và từ thiện, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự tốt bụng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_LUONG_CHU_THAN_DAC', 'Thiên Lương đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính nhân từ và từ thiện. Đắc địa là trạng thái tốt, cho phép Thiên Lương phát huy các đặc tính tích cực về sự nhân từ trong cách thể hiện, tạo nên phong thái tốt bụng ổn định. Hình thể có xu hướng hòa nhã, với thần thái nhân từ và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự dịu dàng vừa phải, với khả năng lắng nghe và hỗ trợ. Hành vi biểu hiện ra bên ngoài mang tính chất nhân từ, có khả năng giúp đỡ và hỗ trợ người khác, với xu hướng tạo được sự hòa hợp. Cách tương tác với xã hội thể hiện sự nhân từ và từ thiện, có khả năng tạo được mối quan hệ tốt, với phong thái hành xử thể hiện sự tốt bụng một cách tự nhiên và hiệu quả.', 'positive', 2),

('THIEN_LUONG_CHU_THAN_BINH', 'Thiên Lương bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính nhân từ và từ thiện. Bình địa là trạng thái trung tính, cho phép Thiên Lương thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái nhân từ ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự dịu dàng ở mức vừa phải, với khả năng lắng nghe và hỗ trợ nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất nhân từ ở mức trung bình, có khả năng giúp đỡ và hỗ trợ người khác, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự nhân từ và từ thiện ở mức vừa phải, có khả năng tạo được mối quan hệ tốt khi có điều kiện, với phong thái hành xử thể hiện sự tốt bụng một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THIEN_LUONG_CHU_THAN_HAM', 'Thiên Lương hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính nhân từ và từ thiện. Hãm địa là trạng thái bất lợi, khiến Thiên Lương không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu nhân từ hoặc không thể hiện được sự từ thiện một cách hiệu quả. Hình thể có thể thiếu sự hòa nhã, với thần thái có thể thiếu nhân từ hoặc không tạo được ấn tượng về sự từ thiện. Cách đi đứng và giao tiếp có thể thiếu sự dịu dàng, với khả năng lắng nghe và hỗ trợ bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất nhân từ, khó khăn trong việc giúp đỡ và hỗ trợ người khác một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự nhân từ và từ thiện, khó khăn trong việc tạo được mối quan hệ tốt, với phong thái hành xử có thể không thể hiện được sự tốt bụng một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- THẤT SÁT (THAT_SAT)
-- ============================

('THAT_SAT_CHU_THAN_MIEU', 'Thất Sát miếu địa làm Chủ Thân tạo nên hình thể và thần thái quyết đoán, mạnh mẽ và có khả năng đối mặt với thách thức một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự quyết đoán trong cách thể hiện bên ngoài, tạo nên phong thái cương nghị và mạnh mẽ. Người có Thất Sát miếu địa làm Chủ Thân thường có hình thể chắc chắn, mạnh mẽ, với thần thái quyết đoán và có khả năng tạo ấn tượng về sự cương nghị và khả năng xử lý tình huống. Cách đi đứng và giao tiếp thể hiện sự quyết đoán, cương nghị, với xu hướng ra quyết định nhanh chóng và đối mặt với các thách thức một cách mạnh mẽ. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng xử lý các tình huống phức tạp, với xu hướng nắm giữ quyền lực và ảnh hưởng trong các hoạt động. Cách tương tác với xã hội thể hiện sự quyết đoán và mạnh mẽ, có khả năng đối mặt với khó khăn và vượt qua thách thức, với phong thái hành xử thể hiện sự cương nghị và khả năng xử lý tình huống một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAT_SAT_CHU_THAN_VUONG', 'Thất Sát vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính quyết đoán và cương nghị. Vượng địa là trạng thái tốt, cho phép Thất Sát phát huy các đặc tính tích cực về sự quyết đoán trong cách thể hiện, tạo nên phong thái cương nghị nổi bật. Hình thể có xu hướng chắc chắn, với thần thái quyết đoán và có khả năng tạo ấn tượng mạnh mẽ về sự mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự quyết đoán, với khả năng ra quyết định nhanh chóng. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng xử lý các tình huống, với xu hướng có ảnh hưởng trong các hoạt động. Cách tương tác với xã hội thể hiện sự quyết đoán và mạnh mẽ, có khả năng đối mặt với khó khăn, với phong thái hành xử thể hiện sự cương nghị một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAT_SAT_CHU_THAN_DAC', 'Thất Sát đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính quyết đoán và cương nghị. Đắc địa là trạng thái tốt, cho phép Thất Sát phát huy các đặc tính tích cực về sự quyết đoán trong cách thể hiện, tạo nên phong thái cương nghị ổn định. Hình thể có xu hướng chắc chắn, với thần thái quyết đoán và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự quyết đoán vừa phải, với khả năng ra quyết định. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng xử lý các tình huống, với xu hướng có ảnh hưởng. Cách tương tác với xã hội thể hiện sự quyết đoán và mạnh mẽ, có khả năng đối mặt với khó khăn, với phong thái hành xử thể hiện sự cương nghị một cách tự nhiên và hiệu quả.', 'positive', 2),

('THAT_SAT_CHU_THAN_BINH', 'Thất Sát bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính quyết đoán và cương nghị. Bình địa là trạng thái trung tính, cho phép Thất Sát thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái quyết đoán ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự quyết đoán ở mức vừa phải, với khả năng ra quyết định nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập ở mức trung bình, có khả năng xử lý các tình huống, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự quyết đoán và mạnh mẽ ở mức vừa phải, có khả năng đối mặt với khó khăn khi có điều kiện, với phong thái hành xử thể hiện sự cương nghị một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('THAT_SAT_CHU_THAN_HAM', 'Thất Sát hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính quyết đoán và cương nghị. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu quyết đoán hoặc không thể hiện được sự cương nghị một cách hiệu quả. Hình thể có thể thiếu sự chắc chắn, với thần thái có thể thiếu quyết đoán hoặc không tạo được ấn tượng về sự mạnh mẽ. Cách đi đứng và giao tiếp có thể thiếu sự quyết đoán, với khả năng ra quyết định bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất độc lập, khó khăn trong việc xử lý các tình huống một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự quyết đoán và mạnh mẽ, khó khăn trong việc đối mặt với khó khăn, với phong thái hành xử có thể không thể hiện được sự cương nghị một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2),

-- ============================
-- PHÁ QUÂN (PHA_QUAN)
-- ============================

('PHA_QUAN_CHU_THAN_MIEU', 'Phá Quân miếu địa làm Chủ Thân tạo nên hình thể và thần thái thay đổi, đổi mới và có khả năng phá vỡ các quy tắc cũ một cách tự nhiên. Sao này khi ở miếu địa thể hiện khả năng phát huy đầy đủ các đặc tính tích cực về sự đổi mới trong cách thể hiện bên ngoài, tạo nên phong thái sáng tạo và năng động. Người có Phá Quân miếu địa làm Chủ Thân thường có hình thể linh hoạt, năng động, với thần thái sáng tạo và có khả năng tạo ấn tượng về sự đổi mới và khả năng tạo ra những thay đổi. Cách đi đứng và giao tiếp thể hiện sự sáng tạo, đổi mới, với xu hướng không tuân theo các quy tắc cũ và tạo ra những cách làm mới. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng tạo ra những thay đổi và đổi mới, với xu hướng tạo ra những đột phá và đạt được thành tựu mới. Cách tương tác với xã hội thể hiện sự sáng tạo và đổi mới, có khả năng tạo ra những thay đổi và phá vỡ các quy tắc cũ, với phong thái hành xử thể hiện sự đổi mới và khả năng tạo ra thay đổi một cách tự nhiên và hiệu quả.', 'positive', 2),

('PHA_QUAN_CHU_THAN_VUONG', 'Phá Quân vượng địa làm Chủ Thân tạo nên hình thể và thần thái mạnh mẽ về tính thay đổi và đổi mới. Vượng địa là trạng thái tốt, cho phép Phá Quân phát huy các đặc tính tích cực về sự đổi mới trong cách thể hiện, tạo nên phong thái sáng tạo nổi bật. Hình thể có xu hướng linh hoạt, với thần thái sáng tạo và có khả năng tạo ấn tượng mạnh mẽ về sự đổi mới. Cách đi đứng và giao tiếp thể hiện sự sáng tạo, với khả năng tạo ra những thay đổi. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng tạo ra những thay đổi, với xu hướng tạo ra những đột phá. Cách tương tác với xã hội thể hiện sự sáng tạo và đổi mới, có khả năng tạo ra những thay đổi, với phong thái hành xử thể hiện sự đổi mới một cách tự nhiên và hiệu quả.', 'positive', 2),

('PHA_QUAN_CHU_THAN_DAC', 'Phá Quân đắc địa làm Chủ Thân tạo nên hình thể và thần thái ổn định về tính thay đổi và đổi mới. Đắc địa là trạng thái tốt, cho phép Phá Quân phát huy các đặc tính tích cực về sự đổi mới trong cách thể hiện, tạo nên phong thái sáng tạo ổn định. Hình thể có xu hướng linh hoạt, với thần thái sáng tạo và có khả năng tạo ấn tượng tích cực. Cách đi đứng và giao tiếp thể hiện sự sáng tạo vừa phải, với khả năng tạo ra những thay đổi. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập, có khả năng tạo ra những thay đổi, với xu hướng tạo ra những đột phá. Cách tương tác với xã hội thể hiện sự sáng tạo và đổi mới, có khả năng tạo ra những thay đổi, với phong thái hành xử thể hiện sự đổi mới một cách tự nhiên và hiệu quả.', 'positive', 2),

('PHA_QUAN_CHU_THAN_BINH', 'Phá Quân bình địa làm Chủ Thân tạo nên hình thể và thần thái ở mức trung bình về tính thay đổi và đổi mới. Bình địa là trạng thái trung tính, cho phép Phá Quân thể hiện các đặc tính của mình ở mức độ vừa phải, không quá nổi bật cũng không quá yếu. Hình thể có xu hướng bình thường, với thần thái sáng tạo ở mức trung bình, có khả năng tạo ấn tượng nhưng không quá mạnh mẽ. Cách đi đứng và giao tiếp thể hiện sự sáng tạo ở mức vừa phải, với khả năng tạo ra những thay đổi nhưng cần có điều kiện phù hợp. Hành vi biểu hiện ra bên ngoài mang tính chất độc lập ở mức trung bình, có khả năng tạo ra những thay đổi, nhưng cần có điều kiện phù hợp. Cách tương tác với xã hội thể hiện sự sáng tạo và đổi mới ở mức vừa phải, có khả năng tạo ra những thay đổi khi có điều kiện, với phong thái hành xử thể hiện sự đổi mới một cách tự nhiên nhưng không quá nổi bật.', 'neutral', 2),

('PHA_QUAN_CHU_THAN_HAM', 'Phá Quân hãm địa làm Chủ Thân tạo nên hình thể và thần thái có thể không phát huy được đầy đủ các đặc tính tích cực về tính thay đổi và đổi mới. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong cách thể hiện, có thể tạo nên phong thái thiếu sáng tạo hoặc không thể hiện được sự đổi mới một cách hiệu quả. Hình thể có thể thiếu sự linh hoạt, với thần thái có thể thiếu sáng tạo hoặc không tạo được ấn tượng về sự đổi mới. Cách đi đứng và giao tiếp có thể thiếu sự sáng tạo, với khả năng tạo ra những thay đổi bị hạn chế. Hành vi biểu hiện ra bên ngoài có thể thiếu tính chất độc lập, khó khăn trong việc tạo ra những thay đổi và đổi mới một cách hiệu quả. Cách tương tác với xã hội có thể thiếu sự sáng tạo và đổi mới, khó khăn trong việc tạo ra những thay đổi, với phong thái hành xử có thể không thể hiện được sự đổi mới một cách rõ ràng và hiệu quả, cần nhiều nỗ lực để phát huy.', 'negative', 2);
