-- ============================================================
-- DETAILED INTERPRETATION FRAGMENTS: CÁC CUNG (PHẦN 2)
-- Giải luận dài, chi tiết (180-300 từ) cho các cung còn lại
-- Dựa trên Tử Vi Đẩu Số Bắc phái truyền thống
-- Format: {STAR_CODE}_{PALACE_CODE}_{BRIGHTNESS}
-- Priority: 0 (long detailed fragments)
-- ============================================================

-- ============================
-- TU_TUC (Tử Tức - Children Palace)
-- ============================

-- TỬ VI tại Tử Tức
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_TU_TUC_MIEU', 
'Tử Vi miếu địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Tử Tức tạo nên xu hướng nổi bật về khả năng giáo dưỡng và ảnh hưởng đến con cái. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc nuôi dạy con cái. Người có Tử Vi miếu địa tại Tử Tức thường có xu hướng đóng vai trò chủ đạo trong việc giáo dưỡng con cái, với khả năng tạo được ảnh hưởng và định hướng cho con cái. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc nuôi dạy, có xu hướng tạo dựng và duy trì cấu trúc trong quan hệ với con cái. Họ có khả năng tạo được vị thế và ảnh hưởng đến con cái, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến con cái. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng định hướng và giáo dưỡng con cái một cách hiệu quả.', 
'positive', 0),

('TU_VI_TU_TUC_VUONG', 
'Tử Vi vượng địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Tử Tức tạo nên xu hướng tích cực về khả năng giáo dưỡng và ảnh hưởng đến con cái. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc nuôi dạy con cái. Người có Tử Vi vượng địa tại Tử Tức thường có xu hướng phát triển tốt trong vai trò giáo dưỡng, với khả năng tạo được ảnh hưởng và định hướng cho con cái. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc nuôi dạy, với xu hướng tạo dựng và duy trì cấu trúc trong quan hệ với con cái. Họ có khả năng tạo được vị thế và ảnh hưởng đến con cái, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng định hướng và giáo dưỡng con cái một cách hiệu quả.', 
'positive', 0),

('TU_VI_TU_TUC_DAC', 
'Tử Vi đắc địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Tử Tức tạo nên xu hướng thuận lợi về khả năng giáo dưỡng và ảnh hưởng đến con cái. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong việc nuôi dạy con cái. Người có Tử Vi đắc địa tại Tử Tức thường có xu hướng thể hiện tính cách tự chủ, có khả năng giáo dưỡng và định hướng cho con cái một cách hiệu quả. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc nuôi dạy, với xu hướng tạo dựng và duy trì cấu trúc trong quan hệ với con cái. Họ có xu hướng đạt được vị thế trung bình đến tốt trong vai trò giáo dưỡng, với khả năng tạo được ảnh hưởng đến con cái. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng định hướng và giáo dưỡng con cái một cách hiệu quả.', 
'positive', 0),

('TU_VI_TU_TUC_BINH', 
'Tử Vi bình địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Tử Tức tạo nên xu hướng trung hòa về khả năng giáo dưỡng và ảnh hưởng đến con cái. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong việc nuôi dạy con cái. Người có Tử Vi bình địa tại Tử Tức thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về quyền uy hay tự chủ trong việc giáo dưỡng nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể đảm nhận các trách nhiệm cơ bản trong việc nuôi dạy nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đóng vai trò chủ đạo. Họ có xu hướng duy trì cấu trúc trong quan hệ với con cái ở mức độ cơ bản, với khả năng ra quyết định và chịu trách nhiệm ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về quyền uy hay tự chủ trong việc giáo dưỡng.', 
'neutral', 0),

('TU_VI_TU_TUC_HAM', 
'Tử Vi hãm địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Tử Tức tạo nên xu hướng khó khăn về khả năng giáo dưỡng và ảnh hưởng đến con cái. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong việc nuôi dạy con cái. Người có Tử Vi hãm địa tại Tử Tức thường gặp khó khăn trong việc đóng vai trò chủ đạo trong việc giáo dưỡng, khó khăn trong việc tạo được ảnh hưởng và định hướng cho con cái. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc ra quyết định hoặc đảm nhận trách nhiệm trong việc nuôi dạy, với xu hướng dễ bị chi phối hoặc ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong quan hệ với con cái, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng giáo dưỡng và ảnh hưởng đến con cái.', 
'negative', 0);

-- THIÊN PHỦ tại Tử Tức
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_TU_TUC_MIEU', 
'Thiên Phủ miếu địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Tử Tức tạo nên xu hướng nổi bật về khả năng tạo dựng và duy trì sự ổn định trong quan hệ với con cái. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong việc nuôi dạy con cái. Người có Thiên Phủ miếu địa tại Tử Tức thường có xu hướng tạo dựng mối quan hệ bền vững với con cái, với khả năng tích lũy và duy trì các giá trị tinh thần và vật chất trong việc nuôi dạy. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong quan hệ với con cái. Họ có xu hướng xây dựng nền tảng vững chắc cho con cái, với khả năng quản lý và tổ chức các hoạt động giáo dưỡng một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng tạo dựng và duy trì môi trường nuôi dạy ổn định cho con cái.', 
'positive', 0),

('THIEN_PHU_TU_TUC_VUONG', 
'Thiên Phủ vượng địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Tử Tức tạo nên xu hướng tích cực về khả năng tạo dựng và duy trì sự ổn định trong quan hệ với con cái. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong việc nuôi dạy con cái. Người có Thiên Phủ vượng địa tại Tử Tức thường có xu hướng phát triển tốt trong vai trò nuôi dạy, với khả năng tạo dựng mối quan hệ bền vững và tích lũy các giá trị. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong quan hệ với con cái. Họ có xu hướng xây dựng nền tảng vững chắc cho con cái, với khả năng quản lý và tổ chức các hoạt động giáo dưỡng một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng tạo dựng và duy trì môi trường nuôi dạy ổn định cho con cái.', 
'positive', 0),

('THIEN_PHU_TU_TUC_DAC', 
'Thiên Phủ đắc địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái và cách thể hiện trong đời sống gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Tử Tức tạo nên xu hướng thuận lợi về khả năng tạo dựng và duy trì sự ổn định trong quan hệ với con cái. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong việc nuôi dạy con cái. Người có Thiên Phủ đắc địa tại Tử Tức thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tạo dựng mối quan hệ ổn định và tích lũy các giá trị. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong quan hệ với con cái. Họ có xu hướng xây dựng nền tảng vững chắc cho con cái, với khả năng quản lý và tổ chức các hoạt động giáo dưỡng một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị ở mức độ phù hợp, đồng thời có khả năng tạo dựng và duy trì môi trường nuôi dạy ổn định cho con cái.', 
'positive', 0),

('THIEN_PHU_TU_TUC_BINH', 
'Thiên Phủ bình địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Tử Tức tạo nên xu hướng trung hòa về khả năng tạo dựng và duy trì sự ổn định trong quan hệ với con cái. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong việc nuôi dạy con cái. Người có Thiên Phủ bình địa tại Tử Tức thường có xu hướng thể hiện tính cách trung hòa, có thể tạo dựng mối quan hệ ổn định ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động giáo dưỡng cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Họ có xu hướng duy trì sự ổn định ở mức độ vừa phải, với khả năng tạo được sự hòa hợp cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo dựng ổn định trong việc nuôi dạy.', 
'neutral', 0),

('THIEN_PHU_TU_TUC_HAM', 
'Thiên Phủ hãm địa tại cung Tử Tức thể hiện vai trò của sao này trong việc định hình quan hệ với con cái, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Tử Tức tạo nên xu hướng khó khăn về khả năng tạo dựng và duy trì sự ổn định trong quan hệ với con cái. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong việc nuôi dạy con cái. Người có Thiên Phủ hãm địa tại Tử Tức thường gặp khó khăn trong việc tạo dựng mối quan hệ bền vững với con cái, khó khăn trong việc tích lũy và duy trì các giá trị trong việc nuôi dạy. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong quan hệ với con cái. Họ có xu hướng gặp trở ngại trong việc xây dựng nền tảng vững chắc cho con cái, với khả năng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Tính cách này thể hiện qua cách họ đối xử với con cái, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và quản lý trong việc nuôi dạy con cái.', 
'negative', 0);

-- ============================
-- PHUC_DUC (Phúc Đức - Fortune Palace)
-- ============================

-- TỬ VI tại Phúc Đức
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_PHUC_DUC_MIEU', 
'Tử Vi miếu địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Phúc Đức tạo nên xu hướng nổi bật về khả năng tích lũy phúc đức và tạo được ảnh hưởng tích cực từ tổ tiên, tâm linh. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc xây dựng và duy trì phúc đức. Người có Tử Vi miếu địa tại Phúc Đức thường có xu hướng tích lũy phúc đức tốt, với khả năng tạo được ảnh hưởng tích cực từ tổ tiên và tâm linh, đồng thời có khả năng truyền lại phúc đức cho thế hệ sau. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc xây dựng phúc đức, có xu hướng tạo dựng và duy trì các giá trị tinh thần và đạo đức trong gia đình. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc xây dựng phúc đức, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến phúc đức gia đình. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tích lũy và duy trì phúc đức một cách hiệu quả.', 
'positive', 0),

('TU_VI_PHUC_DUC_VUONG', 
'Tử Vi vượng địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Phúc Đức tạo nên xu hướng tích cực về khả năng tích lũy phúc đức và tạo được ảnh hưởng tích cực từ tổ tiên, tâm linh. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc xây dựng và duy trì phúc đức. Người có Tử Vi vượng địa tại Phúc Đức thường có xu hướng phát triển tốt trong việc tích lũy phúc đức, với khả năng tạo được ảnh hưởng tích cực và truyền lại phúc đức cho thế hệ sau. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc xây dựng phúc đức, với xu hướng tạo dựng và duy trì các giá trị tinh thần. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc xây dựng phúc đức, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tích lũy và duy trì phúc đức một cách hiệu quả.', 
'positive', 0),

('TU_VI_PHUC_DUC_DAC', 
'Tử Vi đắc địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Phúc Đức tạo nên xu hướng thuận lợi về khả năng tích lũy phúc đức và tạo được ảnh hưởng tích cực từ tổ tiên, tâm linh. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong việc xây dựng và duy trì phúc đức. Người có Tử Vi đắc địa tại Phúc Đức thường có xu hướng thể hiện tính cách tự chủ, có khả năng tích lũy phúc đức và tạo được ảnh hưởng tích cực. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xây dựng và duy trì các giá trị tinh thần, với xu hướng tạo dựng và duy trì phúc đức gia đình. Họ có xu hướng đạt được vị thế trung bình đến tốt trong việc xây dựng phúc đức, với khả năng tạo được ảnh hưởng đến gia đình và thế hệ sau. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng tích lũy và duy trì phúc đức một cách hiệu quả.', 
'positive', 0),

('TU_VI_PHUC_DUC_BINH', 
'Tử Vi bình địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Phúc Đức tạo nên xu hướng trung hòa về khả năng tích lũy phúc đức và tạo được ảnh hưởng từ tổ tiên, tâm linh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong việc xây dựng phúc đức. Người có Tử Vi bình địa tại Phúc Đức thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về khả năng tích lũy phúc đức hay tạo được ảnh hưởng đặc biệt nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể duy trì các giá trị tinh thần cơ bản nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc tích lũy phúc đức đáng kể. Họ có xu hướng duy trì phúc đức ở mức độ cơ bản, với khả năng xây dựng và duy trì các giá trị tinh thần ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo ảnh hưởng phúc đức.', 
'neutral', 0),

('TU_VI_PHUC_DUC_HAM', 
'Tử Vi hãm địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Phúc Đức tạo nên xu hướng khó khăn về khả năng tích lũy phúc đức và tạo được ảnh hưởng từ tổ tiên, tâm linh. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong việc xây dựng phúc đức. Người có Tử Vi hãm địa tại Phúc Đức thường gặp khó khăn trong việc tích lũy phúc đức, khó khăn trong việc tạo được ảnh hưởng tích cực từ tổ tiên hoặc tâm linh. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xây dựng và duy trì các giá trị tinh thần, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì phúc đức gia đình, với khả năng bị hao tán phúc đức hoặc không thể tích lũy được các giá trị cần thiết. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng thiếu khả năng tạo được sự tôn trọng và ảnh hưởng, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và duy trì phúc đức.', 
'negative', 0);

-- THIÊN PHỦ tại Phúc Đức
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_PHUC_DUC_MIEU', 
'Thiên Phủ miếu địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Phúc Đức tạo nên xu hướng nổi bật về khả năng tích lũy phúc đức và tạo được sự ổn định lâu dài từ tổ tiên, tâm linh. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý phúc đức một cách có hệ thống. Người có Thiên Phủ miếu địa tại Phúc Đức thường có xu hướng tích lũy phúc đức tốt, với khả năng tạo được sự ổn định và bền vững từ tổ tiên, đồng thời có khả năng truyền lại và duy trì phúc đức cho thế hệ sau. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong việc xây dựng phúc đức gia đình. Họ có xu hướng xây dựng nền tảng vững chắc cho phúc đức, với khả năng quản lý và tổ chức các hoạt động tâm linh một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy phúc đức, đồng thời có khả năng tạo dựng và duy trì các giá trị tinh thần một cách bền vững.', 
'positive', 0),

('THIEN_PHU_PHUC_DUC_VUONG', 
'Thiên Phủ vượng địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Phúc Đức tạo nên xu hướng tích cực về khả năng tích lũy phúc đức và tạo được sự ổn định lâu dài từ tổ tiên, tâm linh. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý phúc đức một cách hiệu quả. Người có Thiên Phủ vượng địa tại Phúc Đức thường có xu hướng phát triển tốt trong việc tích lũy phúc đức, với khả năng tạo được sự ổn định và bền vững, đồng thời có khả năng truyền lại và duy trì phúc đức cho thế hệ sau. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong việc xây dựng phúc đức gia đình. Họ có xu hướng xây dựng nền tảng vững chắc cho phúc đức, với khả năng quản lý và tổ chức các hoạt động tâm linh một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy phúc đức, đồng thời có khả năng tạo dựng và duy trì các giá trị tinh thần một cách bền vững.', 
'positive', 0),

('THIEN_PHU_PHUC_DUC_DAC', 
'Thiên Phủ đắc địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức và cách thể hiện trong đời sống tinh thần, tâm linh. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Phúc Đức tạo nên xu hướng thuận lợi về khả năng tích lũy phúc đức và tạo được sự ổn định từ tổ tiên, tâm linh. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý phúc đức ở mức độ tốt. Người có Thiên Phủ đắc địa tại Phúc Đức thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tích lũy phúc đức và tạo được sự ổn định. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng xây dựng và duy trì các giá trị tinh thần, với xu hướng tạo dựng và duy trì phúc đức gia đình một cách có hệ thống. Họ có xu hướng đạt được vị thế trung bình đến tốt trong việc xây dựng phúc đức, với khả năng tạo được ảnh hưởng đến gia đình và thế hệ sau. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng tích lũy và duy trì phúc đức một cách hiệu quả.', 
'positive', 0),

('THIEN_PHU_PHUC_DUC_BINH', 
'Thiên Phủ bình địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Phúc Đức tạo nên xu hướng trung hòa về khả năng tích lũy phúc đức và tạo được sự ổn định từ tổ tiên, tâm linh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý phúc đức ở mức độ trung bình. Người có Thiên Phủ bình địa tại Phúc Đức thường có xu hướng thể hiện tính cách trung hòa, có thể duy trì các giá trị tinh thần cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động tâm linh cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy phúc đức đáng kể. Họ có xu hướng duy trì phúc đức ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo ảnh hưởng phúc đức.', 
'neutral', 0),

('THIEN_PHU_PHUC_DUC_HAM', 
'Thiên Phủ hãm địa tại cung Phúc Đức thể hiện vai trò của sao này trong việc định hình phúc đức, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Phúc Đức tạo nên xu hướng khó khăn về khả năng tích lũy phúc đức và tạo được sự ổn định từ tổ tiên, tâm linh. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý phúc đức. Người có Thiên Phủ hãm địa tại Phúc Đức thường gặp khó khăn trong việc tích lũy phúc đức, khó khăn trong việc tạo được sự ổn định hoặc ảnh hưởng từ tổ tiên, tâm linh. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc xây dựng và duy trì các giá trị tinh thần, với xu hướng dễ bị hao tán phúc đức hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì phúc đức gia đình, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ đối xử với tổ tiên và tâm linh, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và duy trì phúc đức.', 
'negative', 0);
