-- ============================================================
-- DETAILED INTERPRETATION FRAGMENTS: CÁC CUNG (PHẦN 3)
-- Giải luận dài, chi tiết (180-300 từ) cho các cung còn lại
-- Dựa trên Tử Vi Đẩu Số Bắc phái truyền thống
-- Format: {STAR_CODE}_{PALACE_CODE}_{BRIGHTNESS}
-- Priority: 0 (long detailed fragments)
-- ============================================================

-- ============================
-- THIEN_DI (Thiên Di - Travel Palace)
-- ============================

-- TỬ VI tại Thiên Di
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_THIEN_DI_MIEU', 
'Tử Vi miếu địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Thiên Di tạo nên xu hướng nổi bật về khả năng di chuyển với địa vị và ảnh hưởng, có khả năng tạo được vị thế trong các hoạt động di động. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc di chuyển và du lịch. Người có Tử Vi miếu địa tại Thiên Di thường có xu hướng di chuyển với địa vị và ảnh hưởng, với khả năng tạo được vị thế trong các hoạt động di động và du lịch. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc di chuyển, có xu hướng tạo dựng và duy trì cấu trúc trong các hoạt động di động. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc di chuyển, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến di chuyển và du lịch. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tạo dựng và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('TU_VI_THIEN_DI_VUONG', 
'Tử Vi vượng địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Thiên Di tạo nên xu hướng tích cực về khả năng di chuyển với địa vị và ảnh hưởng, có khả năng tạo được vị thế trong các hoạt động di động. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc di chuyển và du lịch. Người có Tử Vi vượng địa tại Thiên Di thường có xu hướng phát triển tốt trong các hoạt động di động, với khả năng di chuyển với địa vị và ảnh hưởng. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc di chuyển, với xu hướng tạo dựng và duy trì cấu trúc trong các hoạt động di động. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc di chuyển, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tạo dựng và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('TU_VI_THIEN_DI_DAC', 
'Tử Vi đắc địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Thiên Di tạo nên xu hướng thuận lợi về khả năng di chuyển với địa vị và ảnh hưởng. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong việc di chuyển và du lịch. Người có Tử Vi đắc địa tại Thiên Di thường có xu hướng thể hiện tính cách tự chủ, có khả năng di chuyển với địa vị và ảnh hưởng ở mức độ phù hợp. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xử lý các hoạt động di động một cách hiệu quả, với xu hướng tạo dựng và duy trì cấu trúc trong các hoạt động di động. Họ có xu hướng đạt được vị thế trung bình đến tốt trong các hoạt động di động, với khả năng tạo được ảnh hưởng đến môi trường xung quanh. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng tạo dựng và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('TU_VI_THIEN_DI_BINH', 
'Tử Vi bình địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Thiên Di tạo nên xu hướng trung hòa về khả năng di chuyển với địa vị và ảnh hưởng. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong việc di chuyển. Người có Tử Vi bình địa tại Thiên Di thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về địa vị hay ảnh hưởng trong các hoạt động di động nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể thực hiện các hoạt động di chuyển cơ bản nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đạt được vị thế đặc biệt. Họ có xu hướng duy trì các hoạt động di động ở mức độ cơ bản, với khả năng xử lý các tình huống di chuyển ở mức độ vừa phải. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về địa vị hay ảnh hưởng trong việc di chuyển.', 
'neutral', 0),

('TU_VI_THIEN_DI_HAM', 
'Tử Vi hãm địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Thiên Di tạo nên xu hướng khó khăn về khả năng di chuyển với địa vị và ảnh hưởng. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong việc di chuyển. Người có Tử Vi hãm địa tại Thiên Di thường gặp khó khăn trong việc di chuyển với địa vị, khó khăn trong việc tạo được vị thế hoặc ảnh hưởng trong các hoạt động di động. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xử lý các hoạt động di chuyển một cách hiệu quả, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong các hoạt động di động, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng di chuyển và tạo ảnh hưởng.', 
'negative', 0);

-- THIÊN PHỦ tại Thiên Di
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_THIEN_DI_MIEU', 
'Thiên Phủ miếu địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Thiên Di tạo nên xu hướng nổi bật về khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm, có khả năng tạo được nền tảng vững chắc trong các hoạt động di động. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong quá trình di chuyển. Người có Thiên Phủ miếu địa tại Thiên Di thường có xu hướng di chuyển với sự ổn định, với khả năng tích lũy kinh nghiệm và tạo được nền tảng vững chắc trong các hoạt động du lịch và di động. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong quá trình di chuyển. Họ có xu hướng xây dựng và duy trì các mối quan hệ trong quá trình di động, với khả năng quản lý và tổ chức các hoạt động di chuyển một cách có hệ thống. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy kinh nghiệm, đồng thời có khả năng tạo dựng và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('THIEN_PHU_THIEN_DI_VUONG', 
'Thiên Phủ vượng địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Thiên Di tạo nên xu hướng tích cực về khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm, có khả năng tạo được nền tảng vững chắc trong các hoạt động di động. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong quá trình di chuyển một cách hiệu quả. Người có Thiên Phủ vượng địa tại Thiên Di thường có xu hướng phát triển tốt trong các hoạt động di động, với khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong quá trình di chuyển. Họ có xu hướng xây dựng và duy trì các mối quan hệ trong quá trình di động, với khả năng quản lý và tổ chức các hoạt động di chuyển một cách hiệu quả. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy kinh nghiệm, đồng thời có khả năng tạo dựng và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('THIEN_PHU_THIEN_DI_DAC', 
'Thiên Phủ đắc địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch và cách thể hiện trong các hoạt động di động. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Thiên Di tạo nên xu hướng thuận lợi về khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong quá trình di chuyển. Người có Thiên Phủ đắc địa tại Thiên Di thường có xu hướng thể hiện tính cách hòa nhã, có khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong quá trình di chuyển, với xu hướng xây dựng và duy trì các mối quan hệ trong quá trình di động. Họ có xu hướng đạt được vị thế trung bình đến tốt trong các hoạt động di động, với khả năng quản lý và tổ chức các hoạt động di chuyển một cách có hệ thống. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng tích lũy và duy trì các mối quan hệ trong quá trình di chuyển.', 
'positive', 0),

('THIEN_PHU_THIEN_DI_BINH', 
'Thiên Phủ bình địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Thiên Di tạo nên xu hướng trung hòa về khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong quá trình di chuyển. Người có Thiên Phủ bình địa tại Thiên Di thường có xu hướng thể hiện tính cách trung hòa, có thể thực hiện các hoạt động di chuyển cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động di chuyển cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy kinh nghiệm đáng kể. Họ có xu hướng duy trì các hoạt động di động ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo ảnh hưởng trong việc di chuyển.', 
'neutral', 0),

('THIEN_PHU_THIEN_DI_HAM', 
'Thiên Phủ hãm địa tại cung Thiên Di thể hiện vai trò của sao này trong việc định hình di chuyển, du lịch, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Thiên Di tạo nên xu hướng khó khăn về khả năng di chuyển với sự ổn định và tích lũy kinh nghiệm. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong quá trình di chuyển. Người có Thiên Phủ hãm địa tại Thiên Di thường gặp khó khăn trong việc di chuyển với sự ổn định, khó khăn trong việc tích lũy kinh nghiệm hoặc tạo được nền tảng vững chắc trong các hoạt động di động. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong quá trình di chuyển, với xu hướng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc xây dựng và duy trì các mối quan hệ trong quá trình di động, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ tiếp cận các hoạt động di động, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng di chuyển và tích lũy kinh nghiệm.', 
'negative', 0);

-- ============================
-- NO_BOC (Nô Bộc - Servants/Employees Palace)
-- ============================

-- TỬ VI tại Nô Bộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_NO_BOC_MIEU', 
'Tử Vi miếu địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Nô Bộc tạo nên xu hướng nổi bật về khả năng quản lý và lãnh đạo nhân viên, có khả năng tạo được vị thế và ảnh hưởng trong việc quản lý cấp dưới. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc quản lý nhân viên. Người có Tử Vi miếu địa tại Nô Bộc thường có xu hướng quản lý nhân viên hiệu quả, với khả năng tạo được vị thế và ảnh hưởng, có khả năng chỉ đạo và điều phối cấp dưới một cách tự chủ. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc quản lý, có xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với nhân viên. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến nhân viên, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến quản lý. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng quản lý và điều phối nhân viên một cách hiệu quả.', 
'positive', 0),

('TU_VI_NO_BOC_VUONG', 
'Tử Vi vượng địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Nô Bộc tạo nên xu hướng tích cực về khả năng quản lý và lãnh đạo nhân viên, có khả năng tạo được vị thế và ảnh hưởng trong việc quản lý cấp dưới. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc quản lý nhân viên. Người có Tử Vi vượng địa tại Nô Bộc thường có xu hướng phát triển tốt trong vai trò quản lý, với khả năng quản lý nhân viên hiệu quả và tạo được vị thế. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc quản lý, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với nhân viên. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến nhân viên, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng quản lý và điều phối nhân viên một cách hiệu quả.', 
'positive', 0),

('TU_VI_NO_BOC_DAC', 
'Tử Vi đắc địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Nô Bộc tạo nên xu hướng thuận lợi về khả năng quản lý và lãnh đạo nhân viên. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong việc quản lý nhân viên. Người có Tử Vi đắc địa tại Nô Bộc thường có xu hướng thể hiện tính cách tự chủ, có khả năng quản lý nhân viên và tạo được vị thế ở mức độ phù hợp. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xử lý các vấn đề quản lý một cách hiệu quả, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với nhân viên. Họ có xu hướng đạt được vị thế trung bình đến tốt trong vai trò quản lý, với khả năng tạo được ảnh hưởng đến nhân viên. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng quản lý và điều phối nhân viên một cách hiệu quả.', 
'positive', 0),

('TU_VI_NO_BOC_BINH', 
'Tử Vi bình địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Nô Bộc tạo nên xu hướng trung hòa về khả năng quản lý và lãnh đạo nhân viên. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong việc quản lý nhân viên. Người có Tử Vi bình địa tại Nô Bộc thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về khả năng quản lý hay lãnh đạo nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể quản lý nhân viên ở mức độ cơ bản nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đạt được vị thế đặc biệt. Họ có xu hướng duy trì mối quan hệ với nhân viên ở mức độ cơ bản, với khả năng xử lý các vấn đề quản lý ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng quản lý hay lãnh đạo.', 
'neutral', 0),

('TU_VI_NO_BOC_HAM', 
'Tử Vi hãm địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Nô Bộc tạo nên xu hướng khó khăn về khả năng quản lý và lãnh đạo nhân viên. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong việc quản lý nhân viên. Người có Tử Vi hãm địa tại Nô Bộc thường gặp khó khăn trong việc quản lý nhân viên hiệu quả, khó khăn trong việc tạo được vị thế hoặc ảnh hưởng trong việc quản lý cấp dưới. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xử lý các vấn đề quản lý một cách hiệu quả, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong mối quan hệ với nhân viên, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng quản lý và lãnh đạo nhân viên.', 
'negative', 0);

-- THIÊN PHỦ tại Nô Bộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_NO_BOC_MIEU', 
'Thiên Phủ miếu địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Nô Bộc tạo nên xu hướng nổi bật về khả năng quản lý và tổ chức nhân viên một cách có hệ thống, có khả năng tạo được sự ổn định và tin cậy trong việc quản lý cấp dưới. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong việc quản lý nhân viên. Người có Thiên Phủ miếu địa tại Nô Bộc thường có xu hướng quản lý nhân viên một cách có hệ thống, với khả năng tạo được sự ổn định và tin cậy, có khả năng xây dựng và duy trì nền tảng vững chắc trong mối quan hệ với cấp dưới. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong môi trường làm việc. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với nhân viên, với khả năng quản lý và tổ chức công việc một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng quản lý, đồng thời có khả năng xây dựng và duy trì môi trường làm việc ổn định cho nhân viên.', 
'positive', 0),

('THIEN_PHU_NO_BOC_VUONG', 
'Thiên Phủ vượng địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Nô Bộc tạo nên xu hướng tích cực về khả năng quản lý và tổ chức nhân viên một cách có hệ thống, có khả năng tạo được sự ổn định và tin cậy trong việc quản lý cấp dưới. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong việc quản lý nhân viên một cách hiệu quả. Người có Thiên Phủ vượng địa tại Nô Bộc thường có xu hướng phát triển tốt trong vai trò quản lý, với khả năng quản lý nhân viên một cách có hệ thống và tạo được sự ổn định. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong môi trường làm việc. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với nhân viên, với khả năng quản lý và tổ chức công việc một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng quản lý, đồng thời có khả năng xây dựng và duy trì môi trường làm việc ổn định cho nhân viên.', 
'positive', 0),

('THIEN_PHU_NO_BOC_DAC', 
'Thiên Phủ đắc địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới và cách thể hiện trong môi trường làm việc. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Nô Bộc tạo nên xu hướng thuận lợi về khả năng quản lý và tổ chức nhân viên một cách có hệ thống. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong việc quản lý nhân viên. Người có Thiên Phủ đắc địa tại Nô Bộc thường có xu hướng thể hiện tính cách hòa nhã, có khả năng quản lý nhân viên một cách có hệ thống và tạo được sự ổn định. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong môi trường làm việc, với xu hướng xây dựng và duy trì các mối quan hệ tốt với nhân viên. Họ có xu hướng đạt được vị thế trung bình đến tốt trong vai trò quản lý, với khả năng quản lý và tổ chức công việc một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng xây dựng và duy trì môi trường làm việc ổn định cho nhân viên.', 
'positive', 0),

('THIEN_PHU_NO_BOC_BINH', 
'Thiên Phủ bình địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Nô Bộc tạo nên xu hướng trung hòa về khả năng quản lý và tổ chức nhân viên. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong việc quản lý nhân viên. Người có Thiên Phủ bình địa tại Nô Bộc thường có xu hướng thể hiện tính cách trung hòa, có thể quản lý nhân viên ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý công việc cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể trong mối quan hệ với nhân viên. Họ có xu hướng duy trì mối quan hệ với nhân viên ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng quản lý hay tạo ảnh hưởng.', 
'neutral', 0),

('THIEN_PHU_NO_BOC_HAM', 
'Thiên Phủ hãm địa tại cung Nô Bộc thể hiện vai trò của sao này trong việc định hình quan hệ với nhân viên, cấp dưới, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Nô Bộc tạo nên xu hướng khó khăn về khả năng quản lý và tổ chức nhân viên. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong việc quản lý nhân viên. Người có Thiên Phủ hãm địa tại Nô Bộc thường gặp khó khăn trong việc quản lý nhân viên một cách có hệ thống, khó khăn trong việc tạo được sự ổn định hoặc tin cậy trong việc quản lý cấp dưới. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong môi trường làm việc, với xu hướng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc xây dựng và duy trì mối quan hệ tốt với nhân viên, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ đối xử với nhân viên, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng quản lý và tổ chức nhân viên.', 
'negative', 0);

-- ============================
-- DIEN_TRACH (Điền Trạch - Property Palace)
-- ============================

-- TỬ VI tại Điền Trạch
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_DIEN_TRACH_MIEU', 
'Tử Vi miếu địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Điền Trạch tạo nên xu hướng nổi bật về khả năng tích lũy và quản lý tài sản bất động sản một cách có quyền uy và địa vị. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc tích lũy và quản lý tài sản. Người có Tử Vi miếu địa tại Điền Trạch thường có xu hướng tích lũy tài sản bất động sản tốt, với khả năng tạo được vị thế và ảnh hưởng trong việc quản lý tài sản. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc tích lũy và quản lý tài sản, có xu hướng tạo dựng và duy trì cấu trúc trong việc quản lý bất động sản. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc tích lũy tài sản, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến tài sản. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tích lũy và duy trì tài sản bất động sản một cách hiệu quả.', 
'positive', 0),

('TU_VI_DIEN_TRACH_VUONG', 
'Tử Vi vượng địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Điền Trạch tạo nên xu hướng tích cực về khả năng tích lũy và quản lý tài sản bất động sản một cách có quyền uy và địa vị. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong việc tích lũy và quản lý tài sản. Người có Tử Vi vượng địa tại Điền Trạch thường có xu hướng phát triển tốt trong việc tích lũy tài sản, với khả năng tạo được vị thế và ảnh hưởng trong việc quản lý tài sản. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc tích lũy và quản lý tài sản, với xu hướng tạo dựng và duy trì cấu trúc trong việc quản lý bất động sản. Họ có khả năng tạo được vị thế và ảnh hưởng trong việc tích lũy tài sản, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng tích lũy và duy trì tài sản bất động sản một cách hiệu quả.', 
'positive', 0),

('TU_VI_DIEN_TRACH_DAC', 
'Tử Vi đắc địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Điền Trạch tạo nên xu hướng thuận lợi về khả năng tích lũy và quản lý tài sản bất động sản. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong việc tích lũy và quản lý tài sản. Người có Tử Vi đắc địa tại Điền Trạch thường có xu hướng thể hiện tính cách tự chủ, có khả năng tích lũy và quản lý tài sản bất động sản một cách hiệu quả. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xử lý các vấn đề liên quan đến tài sản một cách hiệu quả, với xu hướng tạo dựng và duy trì cấu trúc trong việc quản lý bất động sản. Họ có xu hướng đạt được vị thế trung bình đến tốt trong việc tích lũy tài sản, với khả năng tạo được ảnh hưởng đến việc quản lý tài sản. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng tích lũy và duy trì tài sản bất động sản một cách hiệu quả.', 
'positive', 0),

('TU_VI_DIEN_TRACH_BINH', 
'Tử Vi bình địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Điền Trạch tạo nên xu hướng trung hòa về khả năng tích lũy và quản lý tài sản bất động sản. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong việc tích lũy và quản lý tài sản. Người có Tử Vi bình địa tại Điền Trạch thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về khả năng tích lũy hay quản lý tài sản nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể quản lý tài sản ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Họ có xu hướng duy trì tài sản ở mức độ cơ bản, với khả năng xử lý các vấn đề liên quan đến tài sản ở mức độ vừa phải. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay quản lý tài sản bất động sản.', 
'neutral', 0),

('TU_VI_DIEN_TRACH_HAM', 
'Tử Vi hãm địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Điền Trạch tạo nên xu hướng khó khăn về khả năng tích lũy và quản lý tài sản bất động sản. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong việc tích lũy và quản lý tài sản. Người có Tử Vi hãm địa tại Điền Trạch thường gặp khó khăn trong việc tích lũy tài sản bất động sản, khó khăn trong việc tạo được vị thế hoặc ảnh hưởng trong việc quản lý tài sản. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xử lý các vấn đề liên quan đến tài sản một cách hiệu quả, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong việc quản lý bất động sản, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và quản lý tài sản bất động sản.', 
'negative', 0);

-- THIÊN PHỦ tại Điền Trạch
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_DIEN_TRACH_MIEU', 
'Thiên Phủ miếu địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Điền Trạch tạo nên xu hướng nổi bật về khả năng tích lũy và quản lý tài sản bất động sản một cách có hệ thống, có khả năng tạo được nền tảng vững chắc trong việc quản lý tài sản. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong việc quản lý tài sản. Người có Thiên Phủ miếu địa tại Điền Trạch thường có xu hướng tích lũy tài sản bất động sản tốt, với khả năng tạo được nền tảng vững chắc và tích lũy giá trị một cách có hệ thống. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự ổn định và tin cậy trong việc quản lý tài sản. Họ có xu hướng xây dựng và duy trì tài sản bất động sản một cách bền vững, với khả năng quản lý và tổ chức việc tích lũy tài sản một cách có hệ thống. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy, đồng thời có khả năng tạo dựng và duy trì tài sản bất động sản một cách bền vững.', 
'positive', 0),

('THIEN_PHU_DIEN_TRACH_VUONG', 
'Thiên Phủ vượng địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Điền Trạch tạo nên xu hướng tích cực về khả năng tích lũy và quản lý tài sản bất động sản một cách có hệ thống, có khả năng tạo được nền tảng vững chắc trong việc quản lý tài sản. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong việc quản lý tài sản một cách hiệu quả. Người có Thiên Phủ vượng địa tại Điền Trạch thường có xu hướng phát triển tốt trong việc tích lũy tài sản, với khả năng tạo được nền tảng vững chắc và tích lũy giá trị một cách hiệu quả. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự ổn định và tin cậy trong việc quản lý tài sản. Họ có xu hướng xây dựng và duy trì tài sản bất động sản một cách bền vững, với khả năng quản lý và tổ chức việc tích lũy tài sản một cách hiệu quả. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy, đồng thời có khả năng tạo dựng và duy trì tài sản bất động sản một cách bền vững.', 
'positive', 0),

('THIEN_PHU_DIEN_TRACH_DAC', 
'Thiên Phủ đắc địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản và cách thể hiện trong việc quản lý tài sản. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Điền Trạch tạo nên xu hướng thuận lợi về khả năng tích lũy và quản lý tài sản bất động sản một cách có hệ thống. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong việc quản lý tài sản. Người có Thiên Phủ đắc địa tại Điền Trạch thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tích lũy và quản lý tài sản bất động sản một cách có hệ thống. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự ổn định và tin cậy trong việc quản lý tài sản, với xu hướng xây dựng và duy trì tài sản bất động sản một cách có hệ thống. Họ có xu hướng đạt được vị thế trung bình đến tốt trong việc tích lũy tài sản, với khả năng quản lý và tổ chức việc tích lũy tài sản một cách có hệ thống. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng tích lũy và duy trì tài sản bất động sản một cách hiệu quả.', 
'positive', 0),

('THIEN_PHU_DIEN_TRACH_BINH', 
'Thiên Phủ bình địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Điền Trạch tạo nên xu hướng trung hòa về khả năng tích lũy và quản lý tài sản bất động sản. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong việc quản lý tài sản. Người có Thiên Phủ bình địa tại Điền Trạch thường có xu hướng thể hiện tính cách trung hòa, có thể quản lý tài sản ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý tài sản cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Họ có xu hướng duy trì tài sản ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay quản lý tài sản bất động sản.', 
'neutral', 0),

('THIEN_PHU_DIEN_TRACH_HAM', 
'Thiên Phủ hãm địa tại cung Điền Trạch thể hiện vai trò của sao này trong việc định hình tài sản bất động sản, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Điền Trạch tạo nên xu hướng khó khăn về khả năng tích lũy và quản lý tài sản bất động sản. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong việc quản lý tài sản. Người có Thiên Phủ hãm địa tại Điền Trạch thường gặp khó khăn trong việc tích lũy tài sản bất động sản, khó khăn trong việc tạo được nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự ổn định và tin cậy trong việc quản lý tài sản, với xu hướng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc xây dựng và duy trì tài sản bất động sản, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ tiếp cận việc quản lý tài sản, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và quản lý tài sản bất động sản.', 
'negative', 0);

-- ============================
-- PHU_MAU (Phụ Mẫu - Parents Palace)
-- ============================

-- TỬ VI tại Phụ Mẫu
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_PHU_MAU_MIEU', 
'Tử Vi miếu địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Phụ Mẫu tạo nên xu hướng nổi bật về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ, có khả năng thể hiện quyền uy và tự chủ trong việc xây dựng mối quan hệ gia đình. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong mối quan hệ với cha mẹ. Người có Tử Vi miếu địa tại Phụ Mẫu thường có xu hướng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ, với khả năng thể hiện quyền uy và tự chủ một cách tích cực. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc xây dựng mối quan hệ với cha mẹ, có xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ gia đình. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến cha mẹ, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến gia đình. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với cha mẹ.', 
'positive', 0),

('TU_VI_PHU_MAU_VUONG', 
'Tử Vi vượng địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Phụ Mẫu tạo nên xu hướng tích cực về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ, có khả năng thể hiện quyền uy và tự chủ trong việc xây dựng mối quan hệ gia đình. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong mối quan hệ với cha mẹ. Người có Tử Vi vượng địa tại Phụ Mẫu thường có xu hướng phát triển tốt trong mối quan hệ với cha mẹ, với khả năng tạo được vị thế và ảnh hưởng. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc xây dựng mối quan hệ, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ gia đình. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến cha mẹ, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với cha mẹ.', 
'positive', 0),

('TU_VI_PHU_MAU_DAC', 
'Tử Vi đắc địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Phụ Mẫu tạo nên xu hướng thuận lợi về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong mối quan hệ với cha mẹ. Người có Tử Vi đắc địa tại Phụ Mẫu thường có xu hướng thể hiện tính cách tự chủ, có khả năng tạo được vị thế và ảnh hưởng ở mức độ phù hợp trong mối quan hệ với cha mẹ. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xử lý các vấn đề trong mối quan hệ một cách hiệu quả, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ gia đình. Họ có xu hướng đạt được vị thế trung bình đến tốt trong mối quan hệ với cha mẹ, với khả năng tạo được ảnh hưởng đến gia đình. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với cha mẹ.', 
'positive', 0),

('TU_VI_PHU_MAU_BINH', 
'Tử Vi bình địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Phụ Mẫu tạo nên xu hướng trung hòa về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong mối quan hệ với cha mẹ. Người có Tử Vi bình địa tại Phụ Mẫu thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về khả năng tạo được vị thế hay ảnh hưởng trong mối quan hệ với cha mẹ nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể duy trì mối quan hệ cơ bản nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đạt được vị thế đặc biệt. Họ có xu hướng duy trì mối quan hệ với cha mẹ ở mức độ cơ bản, với khả năng xử lý các vấn đề trong mối quan hệ ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tạo được vị thế hay ảnh hưởng.', 
'neutral', 0),

('TU_VI_PHU_MAU_HAM', 
'Tử Vi hãm địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Phụ Mẫu tạo nên xu hướng khó khăn về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với cha mẹ. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong mối quan hệ với cha mẹ. Người có Tử Vi hãm địa tại Phụ Mẫu thường gặp khó khăn trong việc tạo được vị thế hoặc ảnh hưởng trong mối quan hệ với cha mẹ, khó khăn trong việc thể hiện quyền uy và tự chủ. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xử lý các vấn đề trong mối quan hệ một cách hiệu quả, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong mối quan hệ gia đình, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng xây dựng và duy trì mối quan hệ với cha mẹ.', 
'negative', 0);

-- THIÊN PHỦ tại Phụ Mẫu
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_PHU_MAU_MIEU', 
'Thiên Phủ miếu địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Phụ Mẫu tạo nên xu hướng nổi bật về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ, có khả năng xây dựng và duy trì nền tảng vững chắc trong mối quan hệ gia đình. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong mối quan hệ với cha mẹ. Người có Thiên Phủ miếu địa tại Phụ Mẫu thường có xu hướng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ, với khả năng xây dựng và duy trì nền tảng vững chắc. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ gia đình. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với cha mẹ, với khả năng quản lý và tổ chức các hoạt động gia đình một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với cha mẹ.', 
'positive', 0),

('THIEN_PHU_PHU_MAU_VUONG', 
'Thiên Phủ vượng địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Phụ Mẫu tạo nên xu hướng tích cực về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ, có khả năng xây dựng và duy trì nền tảng vững chắc trong mối quan hệ gia đình. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong mối quan hệ với cha mẹ một cách hiệu quả. Người có Thiên Phủ vượng địa tại Phụ Mẫu thường có xu hướng phát triển tốt trong mối quan hệ với cha mẹ, với khả năng tạo được sự ổn định và tin cậy. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ gia đình. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với cha mẹ, với khả năng quản lý và tổ chức các hoạt động gia đình một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với cha mẹ.', 
'positive', 0),

('THIEN_PHU_PHU_MAU_DAC', 
'Thiên Phủ đắc địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Phụ Mẫu tạo nên xu hướng thuận lợi về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong mối quan hệ với cha mẹ. Người có Thiên Phủ đắc địa tại Phụ Mẫu thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ gia đình, với xu hướng xây dựng và duy trì các mối quan hệ tốt với cha mẹ. Họ có xu hướng đạt được vị thế trung bình đến tốt trong mối quan hệ với cha mẹ, với khả năng quản lý và tổ chức các hoạt động gia đình một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với cha mẹ.', 
'positive', 0),

('THIEN_PHU_PHU_MAU_BINH', 
'Thiên Phủ bình địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Phụ Mẫu tạo nên xu hướng trung hòa về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong mối quan hệ với cha mẹ. Người có Thiên Phủ bình địa tại Phụ Mẫu thường có xu hướng thể hiện tính cách trung hòa, có thể duy trì mối quan hệ ổn định ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động gia đình cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Họ có xu hướng duy trì mối quan hệ với cha mẹ ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo ảnh hưởng.', 
'neutral', 0),

('THIEN_PHU_PHU_MAU_HAM', 
'Thiên Phủ hãm địa tại cung Phụ Mẫu thể hiện vai trò của sao này trong việc định hình quan hệ với cha mẹ, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Phụ Mẫu tạo nên xu hướng khó khăn về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với cha mẹ. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong mối quan hệ với cha mẹ. Người có Thiên Phủ hãm địa tại Phụ Mẫu thường gặp khó khăn trong việc tạo được sự ổn định hoặc tin cậy trong mối quan hệ với cha mẹ, khó khăn trong việc xây dựng và duy trì nền tảng vững chắc. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong mối quan hệ gia đình, với xu hướng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc xây dựng và duy trì mối quan hệ tốt với cha mẹ, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ đối xử với cha mẹ, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng xây dựng và duy trì mối quan hệ với cha mẹ.', 
'negative', 0);

-- ============================
-- HUYNH_DE (Huynh Đệ - Siblings Palace)
-- ============================

-- TỬ VI tại Huynh Đệ
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_HUYNH_DE_MIEU', 
'Tử Vi miếu địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Huynh Đệ tạo nên xu hướng nổi bật về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em, có khả năng thể hiện quyền uy và tự chủ trong việc xây dựng mối quan hệ. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong mối quan hệ với anh chị em. Người có Tử Vi miếu địa tại Huynh Đệ thường có xu hướng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em, với khả năng thể hiện quyền uy và tự chủ một cách tích cực. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc xây dựng mối quan hệ, có xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với anh chị em. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến anh chị em, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng liên quan đến gia đình. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với anh chị em.', 
'positive', 0),

('TU_VI_HUYNH_DE_VUONG', 
'Tử Vi vượng địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Huynh Đệ tạo nên xu hướng tích cực về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em, có khả năng thể hiện quyền uy và tự chủ trong việc xây dựng mối quan hệ. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong mối quan hệ với anh chị em. Người có Tử Vi vượng địa tại Huynh Đệ thường có xu hướng phát triển tốt trong mối quan hệ với anh chị em, với khả năng tạo được vị thế và ảnh hưởng. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong việc xây dựng mối quan hệ, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với anh chị em. Họ có khả năng tạo được sự tôn trọng và ảnh hưởng đến anh chị em, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với anh chị em.', 
'positive', 0),

('TU_VI_HUYNH_DE_DAC', 
'Tử Vi đắc địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Huynh Đệ tạo nên xu hướng thuận lợi về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong mối quan hệ với anh chị em. Người có Tử Vi đắc địa tại Huynh Đệ thường có xu hướng thể hiện tính cách tự chủ, có khả năng tạo được vị thế và ảnh hưởng ở mức độ phù hợp trong mối quan hệ với anh chị em. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng xử lý các vấn đề trong mối quan hệ một cách hiệu quả, với xu hướng tạo dựng và duy trì cấu trúc trong mối quan hệ với anh chị em. Họ có xu hướng đạt được vị thế trung bình đến tốt trong mối quan hệ với anh chị em, với khả năng tạo được ảnh hưởng đến gia đình. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp, đồng thời có khả năng xây dựng và duy trì mối quan hệ tích cực với anh chị em.', 
'positive', 0),

('TU_VI_HUYNH_DE_BINH', 
'Tử Vi bình địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Huynh Đệ tạo nên xu hướng trung hòa về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong mối quan hệ với anh chị em. Người có Tử Vi bình địa tại Huynh Đệ thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về khả năng tạo được vị thế hay ảnh hưởng trong mối quan hệ với anh chị em nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể duy trì mối quan hệ cơ bản nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đạt được vị thế đặc biệt. Họ có xu hướng duy trì mối quan hệ với anh chị em ở mức độ cơ bản, với khả năng xử lý các vấn đề trong mối quan hệ ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tạo được vị thế hay ảnh hưởng.', 
'neutral', 0),

('TU_VI_HUYNH_DE_HAM', 
'Tử Vi hãm địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Huynh Đệ tạo nên xu hướng khó khăn về khả năng tạo được vị thế và ảnh hưởng trong mối quan hệ với anh chị em. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong mối quan hệ với anh chị em. Người có Tử Vi hãm địa tại Huynh Đệ thường gặp khó khăn trong việc tạo được vị thế hoặc ảnh hưởng trong mối quan hệ với anh chị em, khó khăn trong việc thể hiện quyền uy và tự chủ. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc xử lý các vấn đề trong mối quan hệ một cách hiệu quả, với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Họ có xu hướng gặp trở ngại trong việc tạo dựng và duy trì cấu trúc trong mối quan hệ với anh chị em, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng xây dựng và duy trì mối quan hệ với anh chị em.', 
'negative', 0);

-- THIÊN PHỦ tại Huynh Đệ
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_HUYNH_DE_MIEU', 
'Thiên Phủ miếu địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Huynh Đệ tạo nên xu hướng nổi bật về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em, có khả năng xây dựng và duy trì nền tảng vững chắc trong mối quan hệ. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong mối quan hệ với anh chị em. Người có Thiên Phủ miếu địa tại Huynh Đệ thường có xu hướng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em, với khả năng xây dựng và duy trì nền tảng vững chắc. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ với anh chị em. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với anh chị em, với khả năng quản lý và tổ chức các hoạt động gia đình một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với anh chị em.', 
'positive', 0),

('THIEN_PHU_HUYNH_DE_VUONG', 
'Thiên Phủ vượng địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Huynh Đệ tạo nên xu hướng tích cực về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em, có khả năng xây dựng và duy trì nền tảng vững chắc trong mối quan hệ. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong mối quan hệ với anh chị em một cách hiệu quả. Người có Thiên Phủ vượng địa tại Huynh Đệ thường có xu hướng phát triển tốt trong mối quan hệ với anh chị em, với khả năng tạo được sự ổn định và tin cậy. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ với anh chị em. Họ có xu hướng xây dựng và duy trì các mối quan hệ tốt với anh chị em, với khả năng quản lý và tổ chức các hoạt động gia đình một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với anh chị em.', 
'positive', 0),

('THIEN_PHU_HUYNH_DE_DAC', 
'Thiên Phủ đắc địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em và cách thể hiện trong mối quan hệ gia đình. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Huynh Đệ tạo nên xu hướng thuận lợi về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong mối quan hệ với anh chị em. Người có Thiên Phủ đắc địa tại Huynh Đệ thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ với anh chị em, với xu hướng xây dựng và duy trì các mối quan hệ tốt với anh chị em. Họ có xu hướng đạt được vị thế trung bình đến tốt trong mối quan hệ với anh chị em, với khả năng quản lý và tổ chức các hoạt động gia đình một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng tạo được sự tin cậy và ổn định ở mức độ phù hợp, đồng thời có khả năng xây dựng và duy trì mối quan hệ bền vững với anh chị em.', 
'positive', 0),

('THIEN_PHU_HUYNH_DE_BINH', 
'Thiên Phủ bình địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Huynh Đệ tạo nên xu hướng trung hòa về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong mối quan hệ với anh chị em. Người có Thiên Phủ bình địa tại Huynh Đệ thường có xu hướng thể hiện tính cách trung hòa, có thể duy trì mối quan hệ ổn định ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động gia đình cơ bản nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Họ có xu hướng duy trì mối quan hệ với anh chị em ở mức độ vừa phải, với khả năng tạo được sự ổn định cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo ảnh hưởng.', 
'neutral', 0),

('THIEN_PHU_HUYNH_DE_HAM', 
'Thiên Phủ hãm địa tại cung Huynh Đệ thể hiện vai trò của sao này trong việc định hình quan hệ với anh chị em, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Huynh Đệ tạo nên xu hướng khó khăn về khả năng tạo được sự ổn định và tin cậy trong mối quan hệ với anh chị em. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong mối quan hệ với anh chị em. Người có Thiên Phủ hãm địa tại Huynh Đệ thường gặp khó khăn trong việc tạo được sự ổn định hoặc tin cậy trong mối quan hệ với anh chị em, khó khăn trong việc xây dựng và duy trì nền tảng vững chắc. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong mối quan hệ với anh chị em, với xu hướng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Họ có xu hướng gặp trở ngại trong việc xây dựng và duy trì mối quan hệ tốt với anh chị em, với khả năng bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc duy trì sự ổn định. Tính cách này thể hiện qua cách họ đối xử với anh chị em, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng xây dựng và duy trì mối quan hệ với anh chị em.', 
'negative', 0);
