-- ============================================================
-- DETAILED INTERPRETATION FRAGMENTS: CÁC CUNG
-- Giải luận dài, chi tiết (120-200 từ) cho các cung quan trọng
-- Dựa trên Tử Vi Đẩu Số Bắc phái truyền thống
-- Format: {STAR_CODE}_{PALACE_CODE}_{BRIGHTNESS}
-- Priority: 0 (long detailed fragments)
-- ============================================================

-- ============================
-- QUAN_LOC (Quan Lộc - Career Palace)
-- ============================

-- TỬ VI tại Quan Lộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_QUAN_LOC_MIEU', 
'Tử Vi miếu địa tại cung Quan Lộc thể hiện xu hướng nắm giữ vị trí lãnh đạo trong công việc. Sao này chủ về quyền uy và địa vị, khi ở miếu địa tại cung Quan Lộc tạo nên sức ảnh hưởng mạnh mẽ trong môi trường nghề nghiệp. Người có Tử Vi miếu địa tại Quan Lộc thường có khả năng điều hành, quản lý và chỉ đạo người khác, dễ dàng đạt được vị trí cao trong cơ quan hoặc doanh nghiệp. Tính cách cương nghị, quyết đoán giúp họ vượt qua các thách thức trong công việc và tạo dựng uy tín. Trong thực tế, họ thường được tin tưởng giao phó trách nhiệm quan trọng, có khả năng tạo ảnh hưởng đến môi trường làm việc và định hướng phát triển cho tổ chức. Sự tự tin và khả năng ra quyết định nhanh chóng là đặc điểm nổi bật trong cách làm việc.', 
'positive', 0),

('TU_VI_QUAN_LOC_VUONG', 
'Tử Vi vượng địa tại cung Quan Lộc mang lại tiềm năng phát triển sự nghiệp tốt với khả năng đạt được địa vị và uy quyền trong nghề nghiệp. Vượng địa cho thấy Tử Vi ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực công việc. Người có Tử Vi vượng địa tại Quan Lộc thường có khả năng chỉ huy và điều phối công việc hiệu quả, dễ dàng nhận được sự tín nhiệm từ cấp trên và đồng nghiệp. Họ có xu hướng nắm bắt cơ hội thăng tiến và không ngại đối mặt với thách thức trong công việc. Trong môi trường làm việc, họ thường thể hiện tính cách độc lập, có khả năng đưa ra quyết định quan trọng và chịu trách nhiệm với kết quả. Sự nghiệp của họ có xu hướng phát triển ổn định, từng bước tiến lên các vị trí cao hơn với sự công nhận về năng lực và đóng góp.', 
'positive', 0),

('TU_VI_QUAN_LOC_DAC', 
'Tử Vi đắc địa tại cung Quan Lộc cho thấy khả năng thể hiện năng lực lãnh đạo trong công việc, mặc dù không mạnh bằng miếu hay vượng địa. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực trong lĩnh vực nghề nghiệp. Người có Tử Vi đắc địa tại Quan Lộc thường có khả năng tổ chức công việc, quản lý nhân sự và điều phối các hoạt động trong môi trường làm việc. Họ có xu hướng đạt được vị trí trung bình đến cao trong sự nghiệp, với sự công nhận về năng lực từ đồng nghiệp và cấp trên. Trong thực tế công việc, họ thể hiện tính cách tự chủ, có khả năng ra quyết định và chịu trách nhiệm, mặc dù đôi khi cần thời gian để phát triển và củng cố vị thế. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với khả năng đạt được thành tựu và địa vị nhất định trong lĩnh vực chuyên môn của mình.', 
'positive', 0),

('TU_VI_QUAN_LOC_BINH', 
'Tử Vi bình địa tại cung Quan Lộc thể hiện khả năng công việc ở mức độ trung bình, không có sự nổi bật đặc biệt về địa vị hay quyền uy. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó trong lĩnh vực nghề nghiệp. Người có Tử Vi bình địa tại Quan Lộc thường có khả năng làm việc ổn định, hoàn thành các nhiệm vụ được giao nhưng ít có cơ hội thăng tiến nhanh chóng. Trong môi trường làm việc, họ thể hiện tính cách trung hòa, không quá nổi bật nhưng cũng không yếu kém, có thể làm việc độc lập hoặc theo nhóm tùy theo yêu cầu công việc. Sự nghiệp của họ có xu hướng phát triển chậm và ổn định, ít có biến động lớn, cần nhiều thời gian và nỗ lực để đạt được vị trí cao hơn. Họ cần chủ động tìm kiếm cơ hội và phát triển kỹ năng để cải thiện vị thế trong công việc.', 
'neutral', 0),

('TU_VI_QUAN_LOC_HAM', 
'Tử Vi hãm địa tại cung Quan Lộc cho thấy khó khăn trong việc thể hiện năng lực lãnh đạo và đạt được địa vị trong công việc. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, thậm chí có thể gây ra những trở ngại. Người có Tử Vi hãm địa tại Quan Lộc thường gặp khó khăn trong việc nắm giữ quyền lực hoặc đạt được vị trí lãnh đạo, dễ bị chi phối hoặc ảnh hưởng bởi người khác trong môi trường làm việc. Họ có xu hướng thiếu tự tin khi ra quyết định quan trọng, khó khăn trong việc thể hiện quyền uy và ảnh hưởng đến đồng nghiệp. Trong thực tế công việc, họ có thể gặp trở ngại trong việc thăng tiến, dễ bị bỏ qua các cơ hội hoặc không được tin tưởng giao phó trách nhiệm lớn. Sự nghiệp của họ có xu hướng phát triển chậm, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn và từng bước cải thiện vị thế.', 
'negative', 0);

-- THIÊN PHỦ tại Quan Lộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_QUAN_LOC_MIEU', 
'Thiên Phủ miếu địa tại cung Quan Lộc thể hiện khả năng tích lũy và quản lý tài nguyên trong công việc, đồng thời có xu hướng đạt được địa vị ổn định và được tin tưởng trong môi trường nghề nghiệp. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại Quan Lộc tạo nên khả năng quản lý hiệu quả và xây dựng nền tảng vững chắc cho sự nghiệp. Người có Thiên Phủ miếu địa tại Quan Lộc thường có khả năng tổ chức và điều hành công việc một cách có hệ thống, dễ dàng tạo dựng uy tín và nhận được sự tin cậy từ đồng nghiệp và cấp trên. Tính cách khoan hòa, nhân từ giúp họ xây dựng mối quan hệ tốt trong môi trường làm việc và tạo được sự ổn định lâu dài. Trong thực tế, họ thường được giao phó các vị trí quản lý hoặc điều hành, có khả năng xây dựng và duy trì hệ thống làm việc hiệu quả. Sự nghiệp của họ có xu hướng phát triển ổn định, từng bước tiến lên với nền tảng vững chắc và sự công nhận về năng lực quản lý.', 
'positive', 0),

('THIEN_PHU_QUAN_LOC_VUONG', 
'Thiên Phủ vượng địa tại cung Quan Lộc mang lại tiềm năng phát triển sự nghiệp tốt với khả năng tích lũy thành tựu và đạt được vị trí ổn định trong nghề nghiệp. Vượng địa cho thấy Thiên Phủ ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực công việc, đặc biệt về khả năng quản lý và tổ chức. Người có Thiên Phủ vượng địa tại Quan Lộc thường có khả năng xây dựng và phát triển sự nghiệp một cách bền vững, dễ dàng tạo dựng uy tín và nhận được sự tin tưởng. Họ có xu hướng đạt được vị trí quản lý hoặc điều hành, với khả năng tổ chức công việc và quản lý tài nguyên hiệu quả. Trong môi trường làm việc, họ thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được mối quan hệ tốt với đồng nghiệp và cấp trên. Sự nghiệp của họ có xu hướng phát triển ổn định, từng bước tích lũy kinh nghiệm và thành tựu, tạo nền tảng vững chắc cho sự phát triển lâu dài.', 
'positive', 0),

('THIEN_PHU_QUAN_LOC_DAC', 
'Thiên Phủ đắc địa tại cung Quan Lộc cho thấy khả năng quản lý và tổ chức công việc ở mức độ tốt, với xu hướng đạt được vị trí ổn định trong sự nghiệp. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, đặc biệt về khả năng tích lũy và quản lý. Người có Thiên Phủ đắc địa tại Quan Lộc thường có khả năng làm việc ổn định, tổ chức công việc có hệ thống và xây dựng được nền tảng vững chắc cho sự nghiệp. Họ có xu hướng đạt được vị trí trung bình đến cao, với sự công nhận về năng lực quản lý từ đồng nghiệp và cấp trên. Trong thực tế công việc, họ thể hiện tính cách hòa nhã, có khả năng tạo được mối quan hệ tốt trong môi trường làm việc và duy trì sự ổn định. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tiến lên các vị trí cao hơn thông qua sự kiên trì và nỗ lực.', 
'positive', 0),

('THIEN_PHU_QUAN_LOC_BINH', 
'Thiên Phủ bình địa tại cung Quan Lộc thể hiện khả năng công việc ở mức độ trung bình, không có sự nổi bật đặc biệt về quản lý hay tổ chức. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó trong lĩnh vực nghề nghiệp. Người có Thiên Phủ bình địa tại Quan Lộc thường có khả năng làm việc ổn định, hoàn thành các nhiệm vụ được giao nhưng ít có khả năng tích lũy thành tựu nổi bật. Trong môi trường làm việc, họ thể hiện tính cách trung hòa, có thể quản lý công việc ở mức độ cơ bản nhưng khó đạt được vị trí cao hoặc tạo được ảnh hưởng lớn. Sự nghiệp của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được vị trí tốt hơn. Họ cần chủ động phát triển kỹ năng quản lý và tổ chức để cải thiện vị thế trong công việc.', 
'neutral', 0),

('THIEN_PHU_QUAN_LOC_HAM', 
'Thiên Phủ hãm địa tại cung Quan Lộc cho thấy khó khăn trong việc quản lý và tổ chức công việc, đồng thời dễ gặp trở ngại trong việc đạt được vị trí ổn định trong sự nghiệp. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, thậm chí có thể gây ra những khó khăn về quản lý và tổ chức. Người có Thiên Phủ hãm địa tại Quan Lộc thường gặp khó khăn trong việc xây dựng và duy trì nền tảng vững chắc cho sự nghiệp, dễ bị hao tán tài nguyên hoặc không thể tích lũy thành tựu. Họ có xu hướng thiếu khả năng quản lý hiệu quả, khó khăn trong việc tổ chức công việc và tạo được sự ổn định trong môi trường làm việc. Trong thực tế công việc, họ có thể gặp trở ngại trong việc đạt được vị trí quản lý, dễ bị bỏ qua các cơ hội hoặc không được tin tưởng giao phó trách nhiệm quan trọng. Sự nghiệp của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn.', 
'negative', 0);

-- THAM LANG tại Quan Lộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THAM_LANG_QUAN_LOC_MIEU', 
'Tham Lang miếu địa tại cung Quan Lộc thể hiện khả năng kinh doanh và thương mại trong công việc, với xu hướng đạt được thành công thông qua khả năng giao tiếp và đàm phán. Tham Lang chủ về thông minh và tài trí, khi ở miếu địa tại Quan Lộc tạo nên khả năng phát triển sự nghiệp trong các lĩnh vực liên quan đến buôn bán, kinh doanh hoặc giao dịch. Người có Tham Lang miếu địa tại Quan Lộc thường có khả năng nắm bắt cơ hội kinh doanh, có tài trí trong việc tính toán và đưa ra quyết định, dễ dàng tạo được mối quan hệ hợp tác trong công việc. Tính cách linh hoạt, thông minh giúp họ thích ứng nhanh với các thay đổi trong môi trường làm việc và tận dụng tốt các cơ hội phát triển. Trong thực tế, họ thường thành công trong các công việc liên quan đến bán hàng, marketing, đàm phán hoặc các lĩnh vực đòi hỏi khả năng giao tiếp và thương lượng. Sự nghiệp của họ có xu hướng phát triển thông qua các mối quan hệ và khả năng nắm bắt cơ hội.', 
'positive', 0),

('THAM_LANG_QUAN_LOC_VUONG', 
'Tham Lang vượng địa tại cung Quan Lộc mang lại tiềm năng phát triển sự nghiệp tốt trong các lĩnh vực kinh doanh và thương mại, với khả năng đạt được thành công thông qua tài trí và khả năng giao tiếp. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực công việc, đặc biệt về khả năng kinh doanh và đàm phán. Người có Tham Lang vượng địa tại Quan Lộc thường có khả năng phát triển sự nghiệp nhanh chóng, dễ dàng nắm bắt cơ hội và tạo được các mối quan hệ hợp tác có lợi. Họ có xu hướng thành công trong các công việc đòi hỏi khả năng thương lượng, giao tiếp hoặc tính toán, với khả năng tạo ra giá trị thông qua các hoạt động kinh doanh. Trong môi trường làm việc, họ thể hiện tính cách lanh lợi, thông minh, có khả năng thích ứng nhanh và tận dụng tốt các tình huống. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với nhiều cơ hội và khả năng đạt được thành tựu trong các lĩnh vực liên quan đến kinh doanh.', 
'positive', 0),

('THAM_LANG_QUAN_LOC_DAC', 
'Tham Lang đắc địa tại cung Quan Lộc cho thấy khả năng phát triển sự nghiệp trong các lĩnh vực liên quan đến kinh doanh và giao tiếp, với xu hướng đạt được thành công thông qua tài trí và khả năng thương lượng. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, đặc biệt về khả năng giao tiếp và đàm phán. Người có Tham Lang đắc địa tại Quan Lộc thường có khả năng làm việc hiệu quả trong các công việc đòi hỏi khả năng giao tiếp, có tài trí trong việc tính toán và đưa ra quyết định. Họ có xu hướng đạt được thành công trong các hoạt động liên quan đến bán hàng, marketing hoặc đàm phán, với khả năng tạo được mối quan hệ hợp tác. Trong thực tế công việc, họ thể hiện tính cách linh hoạt, thông minh, có khả năng thích ứng và tận dụng tốt các cơ hội. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tiến lên thông qua sự nỗ lực và khả năng nắm bắt cơ hội.', 
'positive', 0),

('THAM_LANG_QUAN_LOC_BINH', 
'Tham Lang bình địa tại cung Quan Lộc thể hiện khả năng công việc ở mức độ trung bình trong các lĩnh vực liên quan đến kinh doanh và giao tiếp. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất của nó trong lĩnh vực nghề nghiệp. Người có Tham Lang bình địa tại Quan Lộc thường có khả năng làm việc ổn định trong các công việc đòi hỏi giao tiếp, nhưng ít có khả năng tạo ra đột phá hoặc đạt được thành công nổi bật. Trong môi trường làm việc, họ thể hiện tính cách trung hòa, có thể thực hiện các nhiệm vụ cơ bản nhưng khó khăn trong việc tạo được ảnh hưởng lớn hoặc nắm bắt các cơ hội quan trọng. Sự nghiệp của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được vị trí tốt hơn. Họ cần chủ động phát triển kỹ năng giao tiếp và kinh doanh để cải thiện vị thế trong công việc.', 
'neutral', 0),

('THAM_LANG_QUAN_LOC_HAM', 
'Tham Lang hãm địa tại cung Quan Lộc cho thấy khó khăn trong việc phát triển sự nghiệp, đặc biệt trong các lĩnh vực liên quan đến kinh doanh và giao tiếp. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, thậm chí có thể gây ra những khó khăn về tài trí và khả năng giao tiếp. Người có Tham Lang hãm địa tại Quan Lộc thường gặp khó khăn trong việc nắm bắt cơ hội kinh doanh, khó khăn trong việc tạo được mối quan hệ hợp tác hoặc đàm phán thành công. Họ có xu hướng thiếu khả năng tính toán và đưa ra quyết định đúng đắn, dễ bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc thích ứng với các thay đổi. Trong thực tế công việc, họ có thể gặp trở ngại trong việc phát triển sự nghiệp, dễ bỏ lỡ các cơ hội hoặc không thể tận dụng tốt các tình huống. Sự nghiệp của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn.', 
'negative', 0);

-- THẤT SÁT tại Quan Lộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THAT_SAT_QUAN_LOC_MIEU', 
'Thất Sát miếu địa tại cung Quan Lộc thể hiện khả năng đảm nhận các công việc đòi hỏi quyền lực và quyết đoán, với xu hướng đạt được thành công thông qua khả năng xử lý tình huống khó khăn. Thất Sát chủ về quyền uy và quyết đoán, khi ở miếu địa tại Quan Lộc tạo nên khả năng nắm giữ vị trí có trách nhiệm và ảnh hưởng trong môi trường nghề nghiệp. Người có Thất Sát miếu địa tại Quan Lộc thường có khả năng đối mặt với các thách thức, có quyết đoán trong việc ra quyết định và xử lý các tình huống phức tạp. Tính cách cương nghị, mạnh mẽ giúp họ vượt qua các khó khăn trong công việc và đạt được mục tiêu. Trong thực tế, họ thường được giao phó các công việc quan trọng, có trách nhiệm hoặc liên quan đến việc quản lý rủi ro, với khả năng xử lý hiệu quả các tình huống khẩn cấp. Sự nghiệp của họ có xu hướng phát triển thông qua khả năng đảm nhận trách nhiệm và xử lý các thách thức.', 
'positive', 0),

('THAT_SAT_QUAN_LOC_VUONG', 
'Thất Sát vượng địa tại cung Quan Lộc mang lại tiềm năng phát triển sự nghiệp tốt với khả năng đạt được vị trí có quyền lực và trách nhiệm trong nghề nghiệp. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực công việc, đặc biệt về khả năng quyết đoán và xử lý tình huống. Người có Thất Sát vượng địa tại Quan Lộc thường có khả năng phát triển sự nghiệp nhanh chóng, dễ dàng đạt được vị trí có trách nhiệm và ảnh hưởng. Họ có xu hướng thành công trong các công việc đòi hỏi quyền lực, quyết đoán hoặc xử lý các tình huống khó khăn, với khả năng đối mặt với thách thức và đạt được mục tiêu. Trong môi trường làm việc, họ thể hiện tính cách mạnh mẽ, cương nghị, có khả năng ra quyết định nhanh chóng và chịu trách nhiệm với kết quả. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với nhiều cơ hội đạt được vị trí cao và có ảnh hưởng trong tổ chức.', 
'positive', 0),

('THAT_SAT_QUAN_LOC_DAC', 
'Thất Sát đắc địa tại cung Quan Lộc cho thấy khả năng đảm nhận các công việc có trách nhiệm và quyền lực, với xu hướng đạt được thành công thông qua khả năng quyết đoán. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, đặc biệt về khả năng xử lý tình huống và ra quyết định. Người có Thất Sát đắc địa tại Quan Lộc thường có khả năng làm việc hiệu quả trong các công việc đòi hỏi quyền lực, có quyết đoán trong việc xử lý các vấn đề và đạt được mục tiêu. Họ có xu hướng đạt được vị trí trung bình đến cao, với khả năng đảm nhận trách nhiệm và xử lý các tình huống phức tạp. Trong thực tế công việc, họ thể hiện tính cách mạnh mẽ, có khả năng đối mặt với thách thức và vượt qua khó khăn. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tiến lên các vị trí cao hơn thông qua sự quyết đoán và khả năng xử lý tình huống.', 
'positive', 0),

('THAT_SAT_QUAN_LOC_BINH', 
'Thất Sát bình địa tại cung Quan Lộc thể hiện khả năng công việc ở mức độ trung bình, không có sự nổi bật đặc biệt về quyền lực hay quyết đoán. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất của nó trong lĩnh vực nghề nghiệp. Người có Thất Sát bình địa tại Quan Lộc thường có khả năng làm việc ổn định, có thể đảm nhận các nhiệm vụ cơ bản nhưng ít có khả năng đạt được vị trí có quyền lực hoặc ảnh hưởng lớn. Trong môi trường làm việc, họ thể hiện tính cách trung hòa, có thể xử lý các tình huống thông thường nhưng khó khăn trong việc đối mặt với các thách thức lớn hoặc ra quyết định quan trọng. Sự nghiệp của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được vị trí tốt hơn. Họ cần chủ động phát triển kỹ năng quyết đoán và xử lý tình huống để cải thiện vị thế trong công việc.', 
'neutral', 0),

('THAT_SAT_QUAN_LOC_HAM', 
'Thất Sát hãm địa tại cung Quan Lộc cho thấy khó khăn trong việc đạt được vị trí có quyền lực hoặc trách nhiệm trong công việc. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, thậm chí có thể gây ra những khó khăn về quyết đoán và xử lý tình huống. Người có Thất Sát hãm địa tại Quan Lộc thường gặp khó khăn trong việc đảm nhận trách nhiệm, khó khăn trong việc ra quyết định hoặc xử lý các tình huống phức tạp. Họ có xu hướng thiếu quyết đoán, dễ bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc đối mặt với thách thức. Trong thực tế công việc, họ có thể gặp trở ngại trong việc phát triển sự nghiệp, dễ bị bỏ qua các cơ hội hoặc không được tin tưởng giao phó trách nhiệm quan trọng. Sự nghiệp của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn.', 
'negative', 0);

-- PHÁ QUÂN tại Quan Lộc
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('PHA_QUAN_QUAN_LOC_MIEU', 
'Phá Quân miếu địa tại cung Quan Lộc thể hiện khả năng thay đổi và đổi mới trong công việc, với xu hướng đạt được thành công thông qua khả năng phá vỡ các quy tắc cũ và tạo ra cách làm việc mới. Phá Quân chủ về thay đổi và cách mạng, khi ở miếu địa tại Quan Lộc tạo nên khả năng phát triển sự nghiệp trong các lĩnh vực đòi hỏi sự đổi mới và sáng tạo. Người có Phá Quân miếu địa tại Quan Lộc thường có khả năng tạo ra những thay đổi tích cực trong môi trường làm việc, có tư duy sáng tạo và dám đối mặt với rủi ro để đạt được mục tiêu. Tính cách độc lập, quyết đoán giúp họ vượt qua các trở ngại và tạo ra những đột phá trong công việc. Trong thực tế, họ thường thành công trong các công việc liên quan đến đổi mới, khởi nghiệp hoặc các lĩnh vực đòi hỏi sự sáng tạo và thay đổi. Sự nghiệp của họ có xu hướng phát triển thông qua khả năng tạo ra những thay đổi và đạt được thành tựu mới.', 
'positive', 0),

('PHA_QUAN_QUAN_LOC_VUONG', 
'Phá Quân vượng địa tại cung Quan Lộc mang lại tiềm năng phát triển sự nghiệp tốt với khả năng đạt được thành công thông qua sự đổi mới và thay đổi. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực công việc, đặc biệt về khả năng tạo ra những thay đổi tích cực. Người có Phá Quân vượng địa tại Quan Lộc thường có khả năng phát triển sự nghiệp nhanh chóng, dễ dàng tạo ra những đột phá và đạt được thành tựu mới. Họ có xu hướng thành công trong các công việc đòi hỏi sự sáng tạo, đổi mới hoặc khởi nghiệp, với khả năng phá vỡ các quy tắc cũ và tạo ra cách làm việc hiệu quả hơn. Trong môi trường làm việc, họ thể hiện tính cách độc lập, quyết đoán, có khả năng đối mặt với rủi ro và tận dụng tốt các cơ hội. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với nhiều cơ hội tạo ra những thay đổi và đạt được thành tựu đáng kể.', 
'positive', 0),

('PHA_QUAN_QUAN_LOC_DAC', 
'Phá Quân đắc địa tại cung Quan Lộc cho thấy khả năng phát triển sự nghiệp thông qua sự đổi mới và thay đổi, với xu hướng đạt được thành công trong các lĩnh vực đòi hỏi sáng tạo. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, đặc biệt về khả năng tạo ra những thay đổi. Người có Phá Quân đắc địa tại Quan Lộc thường có khả năng làm việc hiệu quả trong các công việc đòi hỏi sự sáng tạo, có tư duy đổi mới và dám thử nghiệm các phương pháp mới. Họ có xu hướng đạt được thành công trong các hoạt động liên quan đến đổi mới hoặc khởi nghiệp, với khả năng tạo ra những giá trị mới. Trong thực tế công việc, họ thể hiện tính cách độc lập, có khả năng đối mặt với thách thức và tận dụng tốt các cơ hội. Sự nghiệp của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tiến lên thông qua sự đổi mới và khả năng tạo ra những thay đổi.', 
'positive', 0),

('PHA_QUAN_QUAN_LOC_BINH', 
'Phá Quân bình địa tại cung Quan Lộc thể hiện khả năng công việc ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới hay thay đổi. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất của nó trong lĩnh vực nghề nghiệp. Người có Phá Quân bình địa tại Quan Lộc thường có khả năng làm việc ổn định, có thể thực hiện các nhiệm vụ cơ bản nhưng ít có khả năng tạo ra đột phá hoặc đổi mới đáng kể. Trong môi trường làm việc, họ thể hiện tính cách trung hòa, có thể thích ứng với các thay đổi nhưng khó khăn trong việc tạo ra những thay đổi lớn hoặc đạt được thành tựu nổi bật. Sự nghiệp của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được vị trí tốt hơn. Họ cần chủ động phát triển kỹ năng sáng tạo và đổi mới để cải thiện vị thế trong công việc.', 
'neutral', 0),

('PHA_QUAN_QUAN_LOC_HAM', 
'Phá Quân hãm địa tại cung Quan Lộc cho thấy khó khăn trong việc phát triển sự nghiệp, đặc biệt trong việc tạo ra những thay đổi tích cực. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong lĩnh vực nghề nghiệp, thậm chí có thể gây ra những khó khăn về sự ổn định và phát triển. Người có Phá Quân hãm địa tại Quan Lộc thường gặp khó khăn trong việc tạo ra những thay đổi tích cực, khó khăn trong việc đổi mới hoặc đạt được thành tựu mới. Họ có xu hướng thiếu khả năng đổi mới, dễ bị mắc kẹt trong các quy tắc cũ và khó khăn trong việc tạo ra những giá trị mới. Trong thực tế công việc, họ có thể gặp trở ngại trong việc phát triển sự nghiệp, dễ bỏ lỡ các cơ hội hoặc không thể tận dụng tốt các tình huống. Sự nghiệp của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn.', 
'negative', 0);

-- ============================
-- TAI_BACH (Tài Bạch - Wealth Palace)
-- ============================

-- TỬ VI tại Tài Bạch
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_TAI_BACH_MIEU', 
'Tử Vi miếu địa tại cung Tài Bạch thể hiện khả năng tích lũy tài sản và quản lý tài chính một cách có quyền uy và địa vị. Sao này chủ về quyền uy và địa vị, khi ở miếu địa tại cung Tài Bạch tạo nên khả năng tạo dựng và duy trì của cải thông qua vị thế và ảnh hưởng trong xã hội. Người có Tử Vi miếu địa tại Tài Bạch thường có khả năng kiểm soát tài chính, có xu hướng tích lũy tài sản thông qua các hoạt động liên quan đến quyền lực và địa vị. Tính cách cương nghị, quyết đoán giúp họ đưa ra các quyết định tài chính đúng đắn và tạo dựng nền tảng tài chính vững chắc. Trong thực tế, họ thường có khả năng tạo ra thu nhập từ các nguồn liên quan đến địa vị, chức vụ hoặc các hoạt động kinh doanh có uy tín. Tài sản của họ có xu hướng tăng trưởng ổn định, với khả năng quản lý và bảo vệ của cải một cách hiệu quả. Họ có xu hướng tiêu dùng có kế hoạch và đầu tư thận trọng để duy trì và phát triển tài sản.', 
'positive', 0),

('TU_VI_TAI_BACH_VUONG', 
'Tử Vi vượng địa tại cung Tài Bạch mang lại tiềm năng tích lũy tài sản tốt với khả năng tạo dựng và phát triển của cải thông qua quyền uy và địa vị. Vượng địa cho thấy Tử Vi ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực tài chính, đặc biệt về khả năng kiểm soát và quản lý tài sản. Người có Tử Vi vượng địa tại Tài Bạch thường có khả năng phát triển tài chính nhanh chóng, dễ dàng tạo ra thu nhập từ các nguồn liên quan đến địa vị và ảnh hưởng. Họ có xu hướng tích lũy tài sản thông qua các hoạt động kinh doanh hoặc đầu tư có uy tín, với khả năng tạo dựng nền tảng tài chính vững chắc. Trong thực tế, họ thường có khả năng quản lý tài chính hiệu quả, có quyết đoán trong các quyết định đầu tư và tạo ra giá trị từ tài sản. Tài sản của họ có xu hướng tăng trưởng theo hướng tích cực, với khả năng duy trì và phát triển của cải lâu dài.', 
'positive', 0),

('TU_VI_TAI_BACH_DAC', 
'Tử Vi đắc địa tại cung Tài Bạch cho thấy khả năng tích lũy và quản lý tài sản ở mức độ tốt, với xu hướng tạo dựng của cải thông qua quyền uy và địa vị. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực trong lĩnh vực tài chính, đặc biệt về khả năng kiểm soát và quản lý. Người có Tử Vi đắc địa tại Tài Bạch thường có khả năng làm việc ổn định để tích lũy tài sản, có xu hướng tạo ra thu nhập từ các nguồn liên quan đến địa vị hoặc các hoạt động kinh doanh. Họ có xu hướng đạt được mức độ tài chính trung bình đến cao, với khả năng quản lý và bảo vệ của cải. Trong thực tế, họ thể hiện tính cách tự chủ trong quản lý tài chính, có khả năng đưa ra quyết định đầu tư và tạo ra giá trị từ tài sản. Tài sản của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tích lũy và phát triển của cải thông qua sự kiên trì và nỗ lực.', 
'positive', 0),

('TU_VI_TAI_BACH_BINH', 
'Tử Vi bình địa tại cung Tài Bạch thể hiện khả năng tài chính ở mức độ trung bình, không có sự nổi bật đặc biệt về tích lũy hay quản lý tài sản. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó trong lĩnh vực tài chính. Người có Tử Vi bình địa tại Tài Bạch thường có khả năng quản lý tài chính ổn định, có thể tích lũy tài sản ở mức độ cơ bản nhưng ít có khả năng tạo ra đột phá về tài chính. Trong thực tế, họ thể hiện tính cách trung hòa trong quản lý tài chính, có thể tiết kiệm và chi tiêu hợp lý nhưng khó khăn trong việc tích lũy lớn hoặc đầu tư hiệu quả. Tài sản của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được mức độ tài chính tốt hơn. Họ cần chủ động phát triển kỹ năng quản lý tài chính và tìm kiếm cơ hội để cải thiện tình hình tài chính.', 
'neutral', 0),

('TU_VI_TAI_BACH_HAM', 
'Tử Vi hãm địa tại cung Tài Bạch cho thấy khó khăn trong việc tích lũy và quản lý tài sản, đồng thời dễ gặp trở ngại trong việc tạo dựng của cải. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực trong lĩnh vực tài chính, thậm chí có thể gây ra những khó khăn về quản lý và tích lũy tài sản. Người có Tử Vi hãm địa tại Tài Bạch thường gặp khó khăn trong việc tạo ra thu nhập từ các nguồn liên quan đến địa vị, khó khăn trong việc kiểm soát tài chính hoặc tích lũy tài sản. Họ có xu hướng thiếu quyết đoán trong các quyết định tài chính, dễ bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc tạo dựng nền tảng tài chính vững chắc. Trong thực tế, họ có thể gặp trở ngại trong việc phát triển tài chính, dễ bị hao tán tài sản hoặc không thể tận dụng tốt các cơ hội. Tài sản của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn và từng bước cải thiện tình hình tài chính.', 
'negative', 0);

-- THIÊN PHỦ tại Tài Bạch  
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_TAI_BACH_MIEU', 
'Thiên Phủ miếu địa tại cung Tài Bạch thể hiện khả năng tích lũy và quản lý tài sản một cách có hệ thống, với xu hướng đạt được sự giàu có và ổn định về tài chính. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Tài Bạch tạo nên khả năng tích lũy tài sản hiệu quả và xây dựng nền tảng tài chính vững chắc. Người có Thiên Phủ miếu địa tại Tài Bạch thường có khả năng quản lý tài chính tốt, có xu hướng tích lũy tài sản thông qua các hoạt động kinh doanh hoặc đầu tư có hệ thống. Tính cách khoan hòa, nhân từ giúp họ xây dựng mối quan hệ tốt trong các hoạt động tài chính và tạo được sự ổn định lâu dài. Trong thực tế, họ thường có khả năng tích lũy tài sản một cách bền vững, có xu hướng đầu tư thận trọng và quản lý tài chính có kế hoạch. Tài sản của họ có xu hướng tăng trưởng ổn định, với khả năng bảo vệ và phát triển của cải một cách hiệu quả. Họ có xu hướng tiêu dùng có kế hoạch và tích lũy tài sản để tạo nền tảng vững chắc cho tương lai.', 
'positive', 0),

('THIEN_PHU_TAI_BACH_VUONG', 
'Thiên Phủ vượng địa tại cung Tài Bạch mang lại tiềm năng tích lũy tài sản tốt với khả năng đạt được sự giàu có và ổn định về tài chính. Vượng địa cho thấy Thiên Phủ ở trạng thái mạnh, có thể phát huy đầy đủ tính chất của sao này trong lĩnh vực tài chính, đặc biệt về khả năng tích lũy và quản lý. Người có Thiên Phủ vượng địa tại Tài Bạch thường có khả năng phát triển tài chính nhanh chóng, dễ dàng tích lũy tài sản thông qua các hoạt động kinh doanh hoặc đầu tư hiệu quả. Họ có xu hướng đạt được sự giàu có, với khả năng quản lý tài chính có hệ thống và xây dựng nền tảng tài chính vững chắc. Trong thực tế, họ thường có khả năng tích lũy tài sản một cách bền vững, có xu hướng đầu tư thận trọng và tạo ra giá trị từ tài sản. Tài sản của họ có xu hướng tăng trưởng theo hướng tích cực, với khả năng duy trì và phát triển của cải lâu dài. Họ có xu hướng tiêu dùng hợp lý và tích lũy tài sản để tạo nền tảng vững chắc cho sự phát triển tài chính.', 
'positive', 0),

('THIEN_PHU_TAI_BACH_DAC', 
'Thiên Phủ đắc địa tại cung Tài Bạch cho thấy khả năng tích lũy và quản lý tài sản ở mức độ tốt, với xu hướng đạt được sự ổn định về tài chính. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực trong lĩnh vực tài chính, đặc biệt về khả năng tích lũy và quản lý. Người có Thiên Phủ đắc địa tại Tài Bạch thường có khả năng làm việc ổn định để tích lũy tài sản, có xu hướng tích lũy tài sản thông qua các hoạt động kinh doanh hoặc đầu tư có hệ thống. Họ có xu hướng đạt được mức độ tài chính trung bình đến cao, với khả năng quản lý và bảo vệ của cải. Trong thực tế, họ thể hiện tính cách hòa nhã trong quản lý tài chính, có khả năng tích lũy tài sản một cách bền vững và tạo ra giá trị từ tài sản. Tài sản của họ có xu hướng phát triển theo hướng tích cực, với khả năng từng bước tích lũy và phát triển của cải thông qua sự kiên trì và nỗ lực. Họ có xu hướng tiêu dùng có kế hoạch và tích lũy tài sản để tạo nền tảng vững chắc.', 
'positive', 0),

('THIEN_PHU_TAI_BACH_BINH', 
'Thiên Phủ bình địa tại cung Tài Bạch thể hiện khả năng tài chính ở mức độ trung bình, không có sự nổi bật đặc biệt về tích lũy hay quản lý tài sản. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó trong lĩnh vực tài chính. Người có Thiên Phủ bình địa tại Tài Bạch thường có khả năng quản lý tài chính ổn định, có thể tích lũy tài sản ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc đạt được sự giàu có. Trong thực tế, họ thể hiện tính cách trung hòa trong quản lý tài chính, có thể tiết kiệm và chi tiêu hợp lý nhưng khó khăn trong việc tích lũy đáng kể hoặc đầu tư hiệu quả. Tài sản của họ có xu hướng phát triển chậm và ổn định, cần nhiều thời gian và nỗ lực để đạt được mức độ tài chính tốt hơn. Họ cần chủ động phát triển kỹ năng quản lý tài chính và tìm kiếm cơ hội để cải thiện tình hình tài chính.', 
'neutral', 0),

('THIEN_PHU_TAI_BACH_HAM', 
'Thiên Phủ hãm địa tại cung Tài Bạch cho thấy khó khăn trong việc tích lũy và quản lý tài sản, đồng thời dễ gặp trở ngại trong việc đạt được sự ổn định về tài chính. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực trong lĩnh vực tài chính, thậm chí có thể gây ra những khó khăn về tích lũy và quản lý tài sản. Người có Thiên Phủ hãm địa tại Tài Bạch thường gặp khó khăn trong việc tích lũy tài sản, khó khăn trong việc quản lý tài chính hiệu quả hoặc dễ bị hao tán tài sản. Họ có xu hướng thiếu khả năng quản lý tài chính có hệ thống, dễ bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc xây dựng nền tảng tài chính vững chắc. Trong thực tế, họ có thể gặp trở ngại trong việc phát triển tài chính, dễ bị hao tán tài sản hoặc không thể tận dụng tốt các cơ hội. Tài sản của họ có xu hướng phát triển chậm và không ổn định, cần nhiều nỗ lực và kiên trì để vượt qua các khó khăn và từng bước cải thiện tình hình tài chính.', 
'negative', 0);

-- ============================
-- PHU_THE (Phu Thê - Spouse Palace)
-- ============================

-- TỬ VI tại Phu Thê
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_PHU_THE_MIEU', 
'Tử Vi miếu địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Phu Thê tạo nên xu hướng nổi bật về địa vị và ảnh hưởng trong mối quan hệ hôn nhân. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện quyền uy và tự chủ trong quan hệ hôn phối. Người có Tử Vi miếu địa tại Phu Thê thường có xu hướng đóng vai trò chủ đạo hoặc có ảnh hưởng lớn trong mối quan hệ, với khả năng tự chủ cao và không dễ bị chi phối. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong các quyết định liên quan đến gia đình, có xu hướng tạo dựng và duy trì cấu trúc trong quan hệ hôn nhân. Họ có khả năng tạo được vị thế và ảnh hưởng đến đối tác, thường có xu hướng đảm nhận trách nhiệm và quyết định các vấn đề quan trọng trong gia đình. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tôn trọng và ảnh hưởng thông qua sự tự chủ và quyết đoán.', 
'positive', 0),

('TU_VI_PHU_THE_VUONG', 
'Tử Vi vượng địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Phu Thê tạo nên xu hướng tích cực về địa vị và ảnh hưởng trong mối quan hệ hôn nhân. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ trong quan hệ hôn phối. Người có Tử Vi vượng địa tại Phu Thê thường có xu hướng phát triển tốt trong mối quan hệ, với khả năng tự chủ và tạo được ảnh hưởng đến đối tác. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng ra quyết định và chịu trách nhiệm trong các vấn đề gia đình. Họ có xu hướng tạo dựng và duy trì cấu trúc trong quan hệ hôn nhân, với khả năng đảm nhận trách nhiệm và tạo được vị thế trong mối quan hệ. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tin tưởng và ảnh hưởng thông qua sự tự chủ và quyết đoán.', 
'positive', 0),

('TU_VI_PHU_THE_DAC', 
'Tử Vi đắc địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Phu Thê tạo nên xu hướng thuận lợi về địa vị và ảnh hưởng trong mối quan hệ hôn nhân. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện quyền uy và tự chủ ở mức độ tốt trong quan hệ hôn phối. Người có Tử Vi đắc địa tại Phu Thê thường có xu hướng thể hiện tính cách tự chủ, có khả năng ra quyết định và đảm nhận trách nhiệm trong mối quan hệ. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng tạo dựng và duy trì cấu trúc trong quan hệ hôn nhân. Họ có xu hướng đạt được vị thế trung bình đến tốt trong mối quan hệ, với khả năng tạo được ảnh hưởng đến đối tác thông qua sự tự chủ và quyết đoán. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tôn trọng và ảnh hưởng ở mức độ phù hợp.', 
'positive', 0),

('TU_VI_PHU_THE_BINH', 
'Tử Vi bình địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Phu Thê tạo nên xu hướng trung hòa về địa vị và ảnh hưởng trong mối quan hệ hôn nhân. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện quyền uy và tự chủ ở mức độ trung bình trong quan hệ hôn phối. Người có Tử Vi bình địa tại Phu Thê thường có xu hướng thể hiện tính cách trung hòa, không quá nổi bật về quyền uy hay tự chủ nhưng cũng không thiếu hoàn toàn. Trong thực tế, họ thường thể hiện tính cách ổn định, có thể đảm nhận các trách nhiệm cơ bản trong mối quan hệ nhưng ít có khả năng tạo được ảnh hưởng lớn hoặc đóng vai trò chủ đạo. Họ có xu hướng duy trì cấu trúc trong quan hệ hôn nhân ở mức độ cơ bản, với khả năng ra quyết định và chịu trách nhiệm ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về quyền uy hay tự chủ.', 
'neutral', 0),

('TU_VI_PHU_THE_HAM', 
'Tử Vi hãm địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Phu Thê tạo nên xu hướng khó khăn về địa vị và ảnh hưởng trong mối quan hệ hôn nhân. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện quyền uy và tự chủ trong quan hệ hôn phối. Người có Tử Vi hãm địa tại Phu Thê thường gặp khó khăn trong việc thể hiện tính cách tự chủ, khó khăn trong việc ra quyết định hoặc đảm nhận trách nhiệm trong mối quan hệ. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, dễ bị chi phối hoặc ảnh hưởng bởi đối tác, với xu hướng khó khăn trong việc tạo dựng và duy trì cấu trúc trong quan hệ hôn nhân. Họ có xu hướng gặp trở ngại trong việc đạt được vị thế trong mối quan hệ, với khả năng bị ảnh hưởng nhiều hơn là tạo ảnh hưởng. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng thiếu quyết đoán và dễ bị chi phối, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện vị thế trong mối quan hệ.', 
'negative', 0);

-- THIÊN PHỦ tại Phu Thê
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THIEN_PHU_PHU_THE_MIEU', 
'Thiên Phủ miếu địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Thiên Phủ chủ về phú có và tích trữ, khi ở miếu địa tại cung Phu Thê tạo nên xu hướng nổi bật về khả năng tạo dựng và duy trì sự ổn định trong mối quan hệ hôn nhân. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất của nó, tạo nên khả năng tích lũy và quản lý các giá trị trong quan hệ hôn phối. Người có Thiên Phủ miếu địa tại Phu Thê thường có xu hướng tạo dựng mối quan hệ bền vững, với khả năng tích lũy và duy trì các giá trị tinh thần và vật chất trong gia đình. Trong thực tế, họ thường thể hiện tính cách khoan hòa, nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ. Họ có xu hướng xây dựng nền tảng vững chắc cho gia đình, với khả năng quản lý và tổ chức các hoạt động trong quan hệ hôn nhân một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị.', 
'positive', 0),

('THIEN_PHU_PHU_THE_VUONG', 
'Thiên Phủ vượng địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Thiên Phủ chủ về phú có và tích trữ, khi ở vượng địa tại cung Phu Thê tạo nên xu hướng tích cực về khả năng tạo dựng và duy trì sự ổn định trong mối quan hệ hôn nhân. Vượng địa là trạng thái mạnh, cho phép Thiên Phủ phát huy tốt các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị trong quan hệ hôn phối. Người có Thiên Phủ vượng địa tại Phu Thê thường có xu hướng phát triển tốt trong mối quan hệ, với khả năng tạo dựng mối quan hệ bền vững và tích lũy các giá trị. Trong thực tế, họ thường thể hiện tính cách nhân từ, khoan hòa, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ. Họ có xu hướng xây dựng nền tảng vững chắc cho gia đình, với khả năng quản lý và tổ chức các hoạt động một cách hiệu quả. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị.', 
'positive', 0),

('THIEN_PHU_PHU_THE_DAC', 
'Thiên Phủ đắc địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối và cách thể hiện trong đời sống vợ chồng. Thiên Phủ chủ về phú có và tích trữ, khi ở đắc địa tại cung Phu Thê tạo nên xu hướng thuận lợi về khả năng tạo dựng và duy trì sự ổn định trong mối quan hệ hôn nhân. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực, tạo nên khả năng tích lũy và quản lý các giá trị ở mức độ tốt trong quan hệ hôn phối. Người có Thiên Phủ đắc địa tại Phu Thê thường có xu hướng thể hiện tính cách hòa nhã, có khả năng tạo dựng mối quan hệ ổn định và tích lũy các giá trị. Trong thực tế, họ thường thể hiện tính cách nhân từ, có khả năng tạo được sự hòa hợp và ổn định trong mối quan hệ. Họ có xu hướng xây dựng nền tảng vững chắc cho gia đình, với khả năng quản lý và tổ chức các hoạt động một cách có hệ thống. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng tạo được sự tin cậy và ổn định thông qua sự nhân từ và khả năng tích lũy giá trị ở mức độ phù hợp.', 
'positive', 0),

('THIEN_PHU_PHU_THE_BINH', 
'Thiên Phủ bình địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối, mặc dù không ở mức độ nổi bật. Thiên Phủ chủ về phú có và tích trữ, khi ở bình địa tại cung Phu Thê tạo nên xu hướng trung hòa về khả năng tạo dựng và duy trì sự ổn định trong mối quan hệ hôn nhân. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng tích lũy và quản lý các giá trị ở mức độ trung bình trong quan hệ hôn phối. Người có Thiên Phủ bình địa tại Phu Thê thường có xu hướng thể hiện tính cách trung hòa, có thể tạo dựng mối quan hệ ổn định ở mức độ cơ bản nhưng ít có khả năng tích lũy lớn hoặc tạo được ảnh hưởng đáng kể. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có thể quản lý các hoạt động cơ bản trong mối quan hệ nhưng khó khăn trong việc tạo dựng nền tảng vững chắc hoặc tích lũy giá trị đáng kể. Họ có xu hướng duy trì sự ổn định ở mức độ vừa phải, với khả năng tạo được sự hòa hợp cơ bản nhưng không nổi bật. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tích lũy hay tạo dựng ổn định.', 
'neutral', 0),

('THIEN_PHU_PHU_THE_HAM', 
'Thiên Phủ hãm địa tại cung Phu Thê thể hiện vai trò của sao này trong việc định hình quan hệ hôn phối, mặc dù gặp khó khăn trong việc phát huy tính chất. Thiên Phủ chủ về phú có và tích trữ, khi ở hãm địa tại cung Phu Thê tạo nên xu hướng khó khăn về khả năng tạo dựng và duy trì sự ổn định trong mối quan hệ hôn nhân. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc tích lũy và quản lý các giá trị trong quan hệ hôn phối. Người có Thiên Phủ hãm địa tại Phu Thê thường gặp khó khăn trong việc tạo dựng mối quan hệ bền vững, khó khăn trong việc tích lũy và duy trì các giá trị trong gia đình. Trong thực tế, họ thường thể hiện tính cách thiếu khả năng quản lý, khó khăn trong việc tạo được sự hòa hợp và ổn định trong mối quan hệ. Họ có xu hướng gặp trở ngại trong việc xây dựng nền tảng vững chắc cho gia đình, với khả năng dễ bị hao tán giá trị hoặc không thể tích lũy được các giá trị cần thiết. Tính cách này thể hiện qua cách họ đối xử với đối tác, với xu hướng thiếu khả năng tạo được sự tin cậy và ổn định, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng tích lũy và quản lý trong mối quan hệ.', 
'negative', 0);

-- ============================
-- TAT_ACH (Tật Ách - Health Palace)
-- ============================

-- TỬ VI tại Tật Ách
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('TU_VI_TAT_ACH_MIEU', 
'Tử Vi miếu địa tại cung Tật Ách thể hiện vai trò của sao này trong việc định hình thể trạng và xu hướng sức khỏe. Tử Vi chủ về quyền uy và tự chủ, khi ở miếu địa tại cung Tật Ách tạo nên xu hướng nổi bật về khả năng duy trì và kiểm soát thể trạng một cách tự chủ. Miếu địa là trạng thái mạnh nhất, cho phép Tử Vi phát huy đầy đủ tính chất của nó, tạo nên khả năng thể hiện sức mạnh và khả năng tự chủ trong việc duy trì sức khỏe. Người có Tử Vi miếu địa tại Tật Ách thường có xu hướng thể trạng tốt, với khả năng tự chủ cao trong việc chăm sóc và duy trì sức khỏe. Trong thực tế, họ thường thể hiện tính cách cương nghị, quyết đoán trong việc duy trì thể trạng, có xu hướng có khả năng chịu đựng tốt và phục hồi nhanh. Họ có khả năng kiểm soát và quản lý sức khỏe một cách hiệu quả, thường có xu hướng đảm nhận trách nhiệm trong việc chăm sóc bản thân và duy trì thể trạng. Tính cách này thể hiện qua cách họ đối mặt với các vấn đề sức khỏe, với xu hướng có khả năng tự chủ và quyết đoán trong việc xử lý và duy trì sức khỏe.', 
'positive', 0),

('TU_VI_TAT_ACH_VUONG', 
'Tử Vi vượng địa tại cung Tật Ách thể hiện vai trò của sao này trong việc định hình thể trạng và xu hướng sức khỏe. Tử Vi chủ về quyền uy và tự chủ, khi ở vượng địa tại cung Tật Ách tạo nên xu hướng tích cực về khả năng duy trì và kiểm soát thể trạng một cách tự chủ. Vượng địa là trạng thái mạnh, cho phép Tử Vi phát huy tốt các mặt tích cực, tạo nên khả năng thể hiện sức mạnh và khả năng tự chủ trong việc duy trì sức khỏe. Người có Tử Vi vượng địa tại Tật Ách thường có xu hướng thể trạng tốt, với khả năng phát triển và duy trì sức khỏe một cách tích cực. Trong thực tế, họ thường thể hiện tính cách độc lập, có khả năng tự chủ trong việc chăm sóc và duy trì sức khỏe, với xu hướng có khả năng chịu đựng tốt và phục hồi nhanh. Họ có khả năng kiểm soát và quản lý sức khỏe hiệu quả, thường có xu hướng đảm nhận trách nhiệm trong việc chăm sóc bản thân. Tính cách này thể hiện qua cách họ đối mặt với các vấn đề sức khỏe, với xu hướng có khả năng tự chủ và quyết đoán trong việc xử lý và duy trì sức khỏe.', 
'positive', 0),

('TU_VI_TAT_ACH_DAC', 
'Tử Vi đắc địa tại cung Tật Ách thể hiện vai trò của sao này trong việc định hình thể trạng và xu hướng sức khỏe. Tử Vi chủ về quyền uy và tự chủ, khi ở đắc địa tại cung Tật Ách tạo nên xu hướng thuận lợi về khả năng duy trì và kiểm soát thể trạng một cách tự chủ. Đắc địa là trạng thái thuận lợi, cho phép Tử Vi phát huy các mặt tích cực, tạo nên khả năng thể hiện sức mạnh và khả năng tự chủ ở mức độ tốt trong việc duy trì sức khỏe. Người có Tử Vi đắc địa tại Tật Ách thường có xu hướng thể trạng tốt, với khả năng tự chủ trong việc chăm sóc và duy trì sức khỏe. Trong thực tế, họ thường thể hiện tính cách tự chủ, có khả năng duy trì thể trạng và xử lý các vấn đề sức khỏe một cách hiệu quả. Họ có xu hướng đạt được thể trạng trung bình đến tốt, với khả năng kiểm soát và quản lý sức khỏe ở mức độ phù hợp. Tính cách này thể hiện qua cách họ đối mặt với các vấn đề sức khỏe, với xu hướng có khả năng tự chủ và quyết đoán ở mức độ phù hợp trong việc xử lý và duy trì sức khỏe.', 
'positive', 0),

('TU_VI_TAT_ACH_BINH', 
'Tử Vi bình địa tại cung Tật Ách thể hiện vai trò của sao này trong việc định hình thể trạng và xu hướng sức khỏe, mặc dù không ở mức độ nổi bật. Tử Vi chủ về quyền uy và tự chủ, khi ở bình địa tại cung Tật Ách tạo nên xu hướng trung hòa về khả năng duy trì và kiểm soát thể trạng. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tử Vi không thể phát huy đầy đủ tính chất của nó, dẫn đến khả năng thể hiện sức mạnh và khả năng tự chủ ở mức độ trung bình trong việc duy trì sức khỏe. Người có Tử Vi bình địa tại Tật Ách thường có xu hướng thể trạng trung bình, với khả năng tự chủ ở mức độ vừa phải trong việc chăm sóc và duy trì sức khỏe. Trong thực tế, họ thường thể hiện tính cách trung hòa, có thể duy trì thể trạng ở mức độ cơ bản nhưng ít có khả năng tạo được sự nổi bật về sức khỏe hoặc khả năng phục hồi đặc biệt. Họ có xu hướng duy trì sức khỏe ở mức độ ổn định, với khả năng kiểm soát và quản lý sức khỏe ở mức độ vừa phải. Tính cách này thể hiện qua cách họ đối mặt với các vấn đề sức khỏe, với xu hướng cân bằng và ít có sự nổi bật đặc biệt về khả năng tự chủ hay sức mạnh trong việc duy trì sức khỏe.', 
'neutral', 0),

('TU_VI_TAT_ACH_HAM', 
'Tử Vi hãm địa tại cung Tật Ách thể hiện vai trò của sao này trong việc định hình thể trạng và xu hướng sức khỏe, mặc dù gặp khó khăn trong việc phát huy tính chất. Tử Vi chủ về quyền uy và tự chủ, khi ở hãm địa tại cung Tật Ách tạo nên xu hướng khó khăn về khả năng duy trì và kiểm soát thể trạng. Hãm địa là trạng thái bất lợi, khiến Tử Vi không thể phát huy các mặt tích cực, dẫn đến khó khăn trong việc thể hiện sức mạnh và khả năng tự chủ trong việc duy trì sức khỏe. Người có Tử Vi hãm địa tại Tật Ách thường gặp khó khăn trong việc duy trì thể trạng tốt, khó khăn trong việc tự chủ trong việc chăm sóc và duy trì sức khỏe. Trong thực tế, họ thường thể hiện tính cách thiếu tự tin, khó khăn trong việc duy trì thể trạng và xử lý các vấn đề sức khỏe một cách hiệu quả. Họ có xu hướng gặp trở ngại trong việc kiểm soát và quản lý sức khỏe, với khả năng dễ bị ảnh hưởng bởi các yếu tố bên ngoài và khó khăn trong việc phục hồi. Tính cách này thể hiện qua cách họ đối mặt với các vấn đề sức khỏe, với xu hướng thiếu khả năng tự chủ và quyết đoán, cần nhiều nỗ lực để vượt qua các khó khăn và từng bước cải thiện khả năng duy trì và quản lý sức khỏe.', 
'negative', 0);

-- (Lưu ý: Do độ dài lớn, file này chứa các fragments cho QUAN_LOC, TAI_BACH, PHU_THE, TAT_ACH. 
-- Các cung khác (TU_TUC, PHUC_DUC, THIEN_DI, NO_BOC, DIEN_TRACH, PHU_MAU, HUYNH_DE) sẽ được tạo trong phần tiếp theo)
