-- ============================================================
-- DETAILED FRAGMENTS: THAT_SAT, PHA_QUAN, THAM_LANG
-- Cho 9 cung: TAT_ACH, DIEN_TRACH, PHU_THE, TU_TUC, PHUC_DUC, THIEN_DI, NO_BOC, PHU_MAU, HUYNH_DE
-- 5 brightness levels: MIEU, VUONG, DAC, BINH, HAM
-- Total: 3 stars × 9 palaces × 5 brightness = 135 fragments
-- ============================================================

-- ============================
-- THAT_SAT (Thất Sát)
-- ============================

-- THAT_SAT tại TAT_ACH
INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES
('THAT_SAT_TAT_ACH_MIEU', 'Thất Sát miếu địa tại cung Tật Ách thể hiện khả năng kiểm soát và quản lý sức khỏe một cách quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Tật Ách tạo nên xu hướng có thể trạng ổn định với khả năng đối mặt hiệu quả với các vấn đề sức khỏe. Miếu địa là trạng thái mạnh nhất, cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc duy trì và bảo vệ sức khỏe. Thể trạng có xu hướng ổn định với khả năng phục hồi nhanh và khả năng chịu đựng tốt. Tuy nhiên, tính chất quyết đoán mạnh mẽ có thể dẫn đến xu hướng không chú ý đầy đủ đến các dấu hiệu cảnh báo sớm, hoặc có thể đối mặt với các thách thức sức khỏe một cách quá mạnh mẽ mà không cân nhắc đầy đủ.', 'positive', 0),
('THAT_SAT_TAT_ACH_VUONG', 'Thất Sát vượng địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ tốt với tính quyết đoán và mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì thể trạng và đối mặt với các vấn đề sức khỏe. Thể trạng có xu hướng ổn định với khả năng đối phó hiệu quả với các thách thức. Tính chất quyết đoán giúp có khả năng xử lý các vấn đề sức khỏe một cách nhanh chóng và hiệu quả. Tuy nhiên, xu hướng mạnh mẽ quá mức có thể dẫn đến việc bỏ qua các dấu hiệu cảnh báo hoặc không chú ý đầy đủ đến việc phòng ngừa. Cần cân bằng giữa sự quyết đoán và sự cẩn trọng trong việc chăm sóc sức khỏe.', 'positive', 0),
('THAT_SAT_TAT_ACH_DAC', 'Thất Sát đắc địa tại cung Tật Ách cho thấy khả năng quản lý sức khỏe ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng đối mặt với các vấn đề sức khỏe một cách hiệu quả. Tính quyết đoán ở mức độ vừa phải giúp có khả năng xử lý các tình huống liên quan đến sức khỏe mà không quá cứng nhắc. Có khả năng duy trì thể trạng ổn định với sự chú ý hợp lý đến việc chăm sóc sức khỏe. Tuy nhiên, cần chú ý để không bỏ qua các dấu hiệu cảnh báo do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_TAT_ACH_BINH', 'Thất Sát bình địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc duy trì thể trạng. Thể trạng có xu hướng ở mức độ trung bình với khả năng đối mặt với các vấn đề sức khỏe ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc xử lý các vấn đề sức khỏe một cách chậm chạp hoặc không đủ quyết liệt. Cần chú ý nhiều hơn đến việc chăm sóc và duy trì thể trạng. Có thể cần thời gian và nỗ lực để cải thiện tình trạng sức khỏe do tính quyết đoán không được phát huy đầy đủ.', 'neutral', 0),
('THAT_SAT_TAT_ACH_HAM', 'Thất Sát hãm địa tại cung Tật Ách cho thấy khó khăn trong việc quản lý và duy trì sức khỏe. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc duy trì thể trạng, thậm chí có thể gây ra những khó khăn. Thể trạng có xu hướng không ổn định với khả năng đối mặt với các vấn đề sức khỏe bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề sức khỏe hoặc bỏ qua các dấu hiệu quan trọng. Khó khăn trong việc duy trì thể trạng ổn định với xu hướng dễ bị ảnh hưởng bởi các yếu tố bên ngoài. Cần nhiều nỗ lực và chú ý đặc biệt để cải thiện và duy trì tình trạng sức khỏe.', 'negative', 0),

-- THAT_SAT tại DIEN_TRACH
('THAT_SAT_DIEN_TRACH_MIEU', 'Thất Sát miếu địa tại cung Điền Trạch thể hiện khả năng quản lý và phát triển tài sản, bất động sản một cách quyết đoán và hiệu quả. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Điền Trạch tạo nên xu hướng có khả năng tích lũy và phát triển tài sản bất động sản ổn định. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư vào đất đai, nhà cửa. Có xu hướng đạt được tài sản bất động sản với khả năng quyết đoán trong các quyết định đầu tư và quản lý. Tính chất mạnh mẽ giúp có khả năng xử lý các vấn đề liên quan đến bất động sản một cách hiệu quả. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến các quyết định đầu tư thiếu cân nhắc hoặc không đủ thận trọng trong việc quản lý tài sản.', 'positive', 0),
('THAT_SAT_DIEN_TRACH_VUONG', 'Thất Sát vượng địa tại cung Điền Trạch mang lại khả năng phát triển tài sản bất động sản ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tài sản đất đai, nhà cửa. Có xu hướng đạt được tài sản bất động sản ổn định với khả năng đưa ra các quyết định đầu tư hiệu quả. Tính quyết đoán giúp có khả năng xử lý nhanh chóng các cơ hội đầu tư và quản lý tài sản. Có khả năng phát triển và duy trì tài sản bất động sản với sự quản lý hiệu quả. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự thận trọng để tránh các quyết định đầu tư rủi ro.', 'positive', 0),
('THAT_SAT_DIEN_TRACH_DAC', 'Thất Sát đắc địa tại cung Điền Trạch cho thấy khả năng quản lý tài sản bất động sản ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc tích lũy và quản lý đất đai, nhà cửa. Có xu hướng đạt được tài sản bất động sản ở mức độ trung bình đến tốt với khả năng quản lý hợp lý. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đưa ra các quyết định đầu tư cân nhắc. Có khả năng duy trì và phát triển tài sản bất động sản với sự quản lý ổn định. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng quyết đoán không đủ mạnh.', 'neutral', 0),
('THAT_SAT_DIEN_TRACH_BINH', 'Thất Sát bình địa tại cung Điền Trạch thể hiện khả năng quản lý tài sản bất động sản ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý đất đai, nhà cửa. Tài sản bất động sản có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc bỏ lỡ các cơ hội đầu tư hoặc không quản lý tài sản một cách hiệu quả. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài sản bất động sản. Có thể cần cải thiện khả năng quyết đoán trong việc quản lý tài sản.', 'neutral', 0),
('THAT_SAT_DIEN_TRACH_HAM', 'Thất Sát hãm địa tại cung Điền Trạch cho thấy khó khăn trong việc tích lũy và quản lý tài sản bất động sản. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc phát triển đất đai, nhà cửa, thậm chí có thể gây ra những khó khăn. Tài sản bất động sản có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến các quyết định đầu tư sai lầm hoặc không xử lý kịp thời các vấn đề liên quan đến tài sản. Khó khăn trong việc tích lũy và duy trì tài sản bất động sản với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài sản bất động sản.', 'negative', 0),

-- THAT_SAT tại PHU_THE
('THAT_SAT_PHU_THE_MIEU', 'Thất Sát miếu địa tại cung Phu Thê thể hiện tính cách quyết đoán và mạnh mẽ trong mối quan hệ hôn nhân. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Phu Thê tạo nên xu hướng đóng vai trò chủ đạo hoặc có ảnh hưởng lớn trong quan hệ hôn nhân. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc xây dựng và duy trì mối quan hệ. Quan hệ hôn nhân có xu hướng ổn định với sự quyết đoán và mạnh mẽ trong việc giải quyết các vấn đề. Tính chất cương nghị giúp có khả năng đối mặt và xử lý các thách thức trong quan hệ một cách hiệu quả. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng độc đoán hoặc không đủ linh hoạt trong việc thỏa hiệp với đối tác.', 'positive', 0),
('THAT_SAT_PHU_THE_VUONG', 'Thất Sát vượng địa tại cung Phu Thê mang lại khả năng xây dựng quan hệ hôn nhân ổn định với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì và phát triển mối quan hệ. Quan hệ hôn nhân có xu hướng ổn định với khả năng giải quyết các vấn đề một cách quyết đoán và hiệu quả. Tính chất mạnh mẽ giúp có khả năng đối mặt với các thách thức và đưa ra quyết định quan trọng trong quan hệ. Có xu hướng tạo được sự ổn định và cấu trúc trong quan hệ hôn nhân. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự linh hoạt để tránh xu hướng độc đoán.', 'positive', 0),
('THAT_SAT_PHU_THE_DAC', 'Thất Sát đắc địa tại cung Phu Thê cho thấy khả năng duy trì quan hệ hôn nhân ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ổn định với khả năng giải quyết các vấn đề một cách cân nhắc. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đưa ra quyết định quan trọng mà không quá cứng nhắc. Có khả năng duy trì và phát triển mối quan hệ với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của đối tác do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_PHU_THE_BINH', 'Thất Sát bình địa tại cung Phu Thê thể hiện khả năng duy trì quan hệ hôn nhân ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ở mức độ trung bình với khả năng giải quyết các vấn đề ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không đưa ra quyết định kịp thời hoặc thiếu sự quyết liệt trong việc xử lý các vấn đề quan hệ. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ. Có thể cần cải thiện khả năng quyết đoán trong việc giải quyết các vấn đề quan hệ.', 'neutral', 0),
('THAT_SAT_PHU_THE_HAM', 'Thất Sát hãm địa tại cung Phu Thê cho thấy khó khăn trong việc duy trì và phát triển quan hệ hôn nhân. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn. Quan hệ hôn nhân có xu hướng không ổn định với khả năng giải quyết các vấn đề bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề quan hệ hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc duy trì và phát triển mối quan hệ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ hôn nhân.', 'negative', 0),

-- THAT_SAT tại TU_TUC
('THAT_SAT_TU_TUC_MIEU', 'Thất Sát miếu địa tại cung Tử Tức thể hiện khả năng giáo dục và quản lý con cái một cách quyết đoán và nghiêm khắc. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Tử Tức tạo nên xu hướng có khả năng định hướng và giáo dục con cái một cách hiệu quả. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ổn định với sự quyết đoán và nghiêm khắc hợp lý trong việc giáo dục. Tính chất mạnh mẽ giúp có khả năng đặt ra kỷ luật và định hướng rõ ràng cho con cái. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng nghiêm khắc quá mức hoặc không đủ linh hoạt trong cách tiếp cận giáo dục.', 'positive', 0),
('THAT_SAT_TU_TUC_VUONG', 'Thất Sát vượng địa tại cung Tử Tức mang lại khả năng giáo dục và quản lý con cái ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ổn định với khả năng giáo dục và định hướng một cách hiệu quả. Tính quyết đoán giúp có khả năng đặt ra kỷ luật và quy tắc rõ ràng cho con cái. Có xu hướng tạo được sự kỷ luật và cấu trúc trong việc giáo dục con cái. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự linh hoạt để tránh xu hướng nghiêm khắc quá mức.', 'positive', 0),
('THAT_SAT_TU_TUC_DAC', 'Thất Sát đắc địa tại cung Tử Tức cho thấy khả năng giáo dục con cái ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ổn định với khả năng giáo dục và định hướng một cách cân nhắc. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đặt ra kỷ luật hợp lý mà không quá cứng nhắc. Có khả năng duy trì và phát triển mối quan hệ với con cái với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu cảm xúc của con cái do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_TU_TUC_BINH', 'Thất Sát bình địa tại cung Tử Tức thể hiện khả năng giáo dục con cái ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ở mức độ trung bình với khả năng giáo dục ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không đặt ra kỷ luật đủ rõ ràng hoặc thiếu sự quyết liệt trong việc giáo dục. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với con cái. Có thể cần cải thiện khả năng quyết đoán trong việc giáo dục con cái.', 'neutral', 0),
('THAT_SAT_TU_TUC_HAM', 'Thất Sát hãm địa tại cung Tử Tức cho thấy khó khăn trong việc giáo dục và quản lý con cái. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái, thậm chí có thể gây ra những khó khăn. Quan hệ với con cái có xu hướng không ổn định với khả năng giáo dục và định hướng bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề liên quan đến con cái hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc duy trì và phát triển mối quan hệ với con cái với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với con cái.', 'negative', 0),

-- THAT_SAT tại PHUC_DUC
('THAT_SAT_PHUC_DUC_MIEU', 'Thất Sát miếu địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức thông qua hành động quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Phúc Đức tạo nên xu hướng có khả năng tạo dựng phúc đức thông qua các hành động quyết đoán và đúng đắn. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy ổn định với khả năng đưa ra các quyết định đúng đắn và hành động có trách nhiệm. Tính chất mạnh mẽ giúp có khả năng đối mặt với các thách thức và vượt qua khó khăn một cách quyết đoán. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng hành động thiếu cân nhắc hoặc không đủ nhân từ trong một số tình huống.', 'positive', 0),
('THAT_SAT_PHUC_DUC_VUONG', 'Thất Sát vượng địa tại cung Phúc Đức mang lại khả năng tích lũy phúc đức ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tạo dựng và tích lũy phúc đức. Phúc đức có xu hướng tích lũy ổn định với khả năng đưa ra các quyết định đúng đắn và hành động có trách nhiệm. Tính quyết đoán giúp có khả năng đối mặt với các thách thức và vượt qua khó khăn một cách hiệu quả. Có xu hướng tạo được phúc đức thông qua các hành động quyết đoán và đúng đắn. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự nhân từ để tránh xu hướng hành động thiếu cân nhắc.', 'positive', 0),
('THAT_SAT_PHUC_DUC_DAC', 'Thất Sát đắc địa tại cung Phúc Đức cho thấy khả năng tích lũy phúc đức ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc tạo dựng phúc đức. Phúc đức có xu hướng tích lũy ổn định với khả năng đưa ra các quyết định cân nhắc và hành động có trách nhiệm. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đối mặt với các thách thức mà không quá cứng nhắc. Có khả năng duy trì và phát triển phúc đức với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội tích lũy phúc đức do xu hướng quyết đoán không đủ mạnh.', 'neutral', 0),
('THAT_SAT_PHUC_DUC_BINH', 'Thất Sát bình địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy ở mức độ trung bình với khả năng hành động ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không đưa ra quyết định kịp thời hoặc thiếu sự quyết liệt trong việc hành động tích cực. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển phúc đức. Có thể cần cải thiện khả năng quyết đoán trong việc tạo dựng phúc đức.', 'neutral', 0),
('THAT_SAT_PHUC_DUC_HAM', 'Thất Sát hãm địa tại cung Phúc Đức cho thấy khó khăn trong việc tích lũy và phát triển phúc đức. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc tạo dựng phúc đức, thậm chí có thể gây ra những khó khăn. Phúc đức có xu hướng tích lũy chậm hoặc không ổn định với khả năng hành động tích cực bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các cơ hội tích lũy phúc đức hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc tích lũy và duy trì phúc đức với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng phúc đức.', 'negative', 0),

-- THAT_SAT tại THIEN_DI
('THAT_SAT_THIEN_DI_MIEU', 'Thất Sát miếu địa tại cung Thiên Di thể hiện khả năng thích ứng và phát triển trong môi trường mới một cách quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Thiên Di tạo nên xu hướng có khả năng đối mặt với các thay đổi và thách thức trong môi trường mới một cách hiệu quả. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc thích ứng và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với sự quyết đoán và mạnh mẽ trong việc đối mặt với thay đổi. Tính chất cương nghị giúp có khả năng xử lý các tình huống mới và đưa ra quyết định nhanh chóng. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng thay đổi quá nhanh hoặc không đủ thận trọng trong việc đánh giá môi trường mới.', 'positive', 0),
('THAT_SAT_THIEN_DI_VUONG', 'Thất Sát vượng địa tại cung Thiên Di mang lại khả năng thích ứng với môi trường mới ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc đối mặt với thay đổi và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với sự quyết đoán và mạnh mẽ. Tính quyết đoán giúp có khả năng xử lý nhanh chóng các tình huống mới và đưa ra quyết định hiệu quả. Có xu hướng tạo được sự ổn định và phát triển trong môi trường mới. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự thận trọng để tránh xu hướng thay đổi quá nhanh.', 'positive', 0),
('THAT_SAT_THIEN_DI_DAC', 'Thất Sát đắc địa tại cung Thiên Di cho thấy khả năng thích ứng với môi trường mới ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ổn định với sự quyết đoán vừa phải. Tính quyết đoán ở mức độ vừa phải giúp có khả năng xử lý các tình huống mới một cách cân nhắc. Có khả năng duy trì và phát triển trong môi trường mới với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng quyết đoán không đủ mạnh.', 'neutral', 0),
('THAT_SAT_THIEN_DI_BINH', 'Thất Sát bình địa tại cung Thiên Di thể hiện khả năng thích ứng với môi trường mới ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ở mức độ trung bình với sự quyết đoán không đủ mạnh. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không xử lý kịp thời các tình huống mới hoặc thiếu sự quyết liệt trong việc thích ứng. Cần nhiều thời gian và nỗ lực để thích ứng và phát triển trong môi trường mới. Có thể cần cải thiện khả năng quyết đoán trong việc đối mặt với thay đổi.', 'neutral', 0),
('THAT_SAT_THIEN_DI_HAM', 'Thất Sát hãm địa tại cung Thiên Di cho thấy khó khăn trong việc thích ứng và phát triển trong môi trường mới. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc đối mặt với thay đổi, thậm chí có thể gây ra những khó khăn. Khả năng thích ứng với môi trường mới có xu hướng kém với sự quyết đoán bị suy giảm. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các tình huống mới hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc thích ứng và phát triển trong môi trường mới với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện khả năng thích ứng với môi trường mới.', 'negative', 0),

-- THAT_SAT tại NO_BOC
('THAT_SAT_NO_BOC_MIEU', 'Thất Sát miếu địa tại cung Nô Bộc thể hiện khả năng quản lý và điều hành người dưới quyền một cách quyết đoán và hiệu quả. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Nô Bộc tạo nên xu hướng có khả năng quản lý và điều hành người dưới quyền một cách có kỷ luật và hiệu quả. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc quản lý quan hệ với người dưới quyền. Quan hệ với người dưới quyền có xu hướng ổn định với sự quyết đoán và nghiêm khắc hợp lý trong việc quản lý. Tính chất mạnh mẽ giúp có khả năng đặt ra quy tắc và kỷ luật rõ ràng. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng nghiêm khắc quá mức hoặc không đủ linh hoạt trong cách quản lý.', 'positive', 0),
('THAT_SAT_NO_BOC_VUONG', 'Thất Sát vượng địa tại cung Nô Bộc mang lại khả năng quản lý người dưới quyền ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng ổn định với khả năng quản lý và điều hành một cách hiệu quả. Tính quyết đoán giúp có khả năng đặt ra quy tắc và kỷ luật rõ ràng cho người dưới quyền. Có xu hướng tạo được sự kỷ luật và cấu trúc trong việc quản lý. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự linh hoạt để tránh xu hướng nghiêm khắc quá mức.', 'positive', 0),
('THAT_SAT_NO_BOC_DAC', 'Thất Sát đắc địa tại cung Nô Bộc cho thấy khả năng quản lý người dưới quyền ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng ổn định với khả năng quản lý một cách cân nhắc. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đặt ra quy tắc hợp lý mà không quá cứng nhắc. Có khả năng duy trì và phát triển quan hệ với người dưới quyền với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của người dưới quyền do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_NO_BOC_BINH', 'Thất Sát bình địa tại cung Nô Bộc thể hiện khả năng quản lý người dưới quyền ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc quản lý và điều hành. Quan hệ với người dưới quyền có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không đặt ra quy tắc đủ rõ ràng hoặc thiếu sự quyết liệt trong việc quản lý. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển quan hệ với người dưới quyền. Có thể cần cải thiện khả năng quyết đoán trong việc quản lý.', 'neutral', 0),
('THAT_SAT_NO_BOC_HAM', 'Thất Sát hãm địa tại cung Nô Bộc cho thấy khó khăn trong việc quản lý và điều hành người dưới quyền. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc quản lý, thậm chí có thể gây ra những khó khăn. Quan hệ với người dưới quyền có xu hướng không ổn định với khả năng quản lý và điều hành bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề liên quan đến người dưới quyền hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc duy trì và phát triển quan hệ với người dưới quyền với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quản lý.', 'negative', 0),

-- THAT_SAT tại PHU_MAU
('THAT_SAT_PHU_MAU_MIEU', 'Thất Sát miếu địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ có tính chất quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Phụ Mẫu tạo nên xu hướng có mối quan hệ với cha mẹ với sự quyết đoán và ảnh hưởng rõ ràng. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ổn định với sự quyết đoán và mạnh mẽ trong việc đối mặt với các vấn đề. Tính chất cương nghị giúp có khả năng xử lý các tình huống liên quan đến cha mẹ một cách hiệu quả. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng độc lập quá mức hoặc không đủ linh hoạt trong việc thỏa hiệp với cha mẹ.', 'positive', 0),
('THAT_SAT_PHU_MAU_VUONG', 'Thất Sát vượng địa tại cung Phụ Mẫu mang lại mối quan hệ với cha mẹ ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ổn định với sự quyết đoán và mạnh mẽ. Tính quyết đoán giúp có khả năng xử lý các vấn đề liên quan đến cha mẹ một cách hiệu quả. Có xu hướng tạo được sự ổn định và cấu trúc trong mối quan hệ với cha mẹ. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự linh hoạt để tránh xu hướng độc lập quá mức.', 'positive', 0),
('THAT_SAT_PHU_MAU_DAC', 'Thất Sát đắc địa tại cung Phụ Mẫu cho thấy mối quan hệ với cha mẹ ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ổn định với sự quyết đoán vừa phải. Tính quyết đoán ở mức độ vừa phải giúp có khả năng xử lý các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với cha mẹ với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của cha mẹ do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_PHU_MAU_BINH', 'Thất Sát bình địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không xử lý kịp thời các vấn đề liên quan đến cha mẹ hoặc thiếu sự quyết liệt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với cha mẹ. Có thể cần cải thiện khả năng quyết đoán trong việc xử lý các vấn đề liên quan đến cha mẹ.', 'neutral', 0),
('THAT_SAT_PHU_MAU_HAM', 'Thất Sát hãm địa tại cung Phụ Mẫu cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn. Mối quan hệ với cha mẹ có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với cha mẹ.', 'negative', 0),

-- THAT_SAT tại HUYNH_DE
('THAT_SAT_HUYNH_DE_MIEU', 'Thất Sát miếu địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em có tính chất quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Huynh Đệ tạo nên xu hướng có mối quan hệ với anh chị em với sự quyết đoán và ảnh hưởng rõ ràng. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ổn định với sự quyết đoán và mạnh mẽ trong việc đối mặt với các vấn đề. Tính chất cương nghị giúp có khả năng xử lý các tình huống liên quan đến anh chị em một cách hiệu quả. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến xu hướng cạnh tranh quá mức hoặc không đủ linh hoạt trong việc thỏa hiệp với anh chị em.', 'positive', 0),
('THAT_SAT_HUYNH_DE_VUONG', 'Thất Sát vượng địa tại cung Huynh Đệ mang lại mối quan hệ với anh chị em ở mức độ tốt với tính quyết đoán mạnh mẽ. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ổn định với sự quyết đoán và mạnh mẽ. Tính quyết đoán giúp có khả năng xử lý các vấn đề liên quan đến anh chị em một cách hiệu quả. Có xu hướng tạo được sự ổn định và cấu trúc trong mối quan hệ với anh chị em. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự linh hoạt để tránh xu hướng cạnh tranh quá mức.', 'positive', 0),
('THAT_SAT_HUYNH_DE_DAC', 'Thất Sát đắc địa tại cung Huynh Đệ cho thấy mối quan hệ với anh chị em ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ổn định với sự quyết đoán vừa phải. Tính quyết đoán ở mức độ vừa phải giúp có khả năng xử lý các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với anh chị em với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của anh chị em do xu hướng quyết đoán.', 'neutral', 0),
('THAT_SAT_HUYNH_DE_BINH', 'Thất Sát bình địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em ở mức độ trung bình, không có sự nổi bật đặc biệt. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không xử lý kịp thời các vấn đề liên quan đến anh chị em hoặc thiếu sự quyết liệt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với anh chị em. Có thể cần cải thiện khả năng quyết đoán trong việc xử lý các vấn đề liên quan đến anh chị em.', 'neutral', 0),
('THAT_SAT_HUYNH_DE_HAM', 'Thất Sát hãm địa tại cung Huynh Đệ cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn. Mối quan hệ với anh chị em có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các vấn đề hoặc thiếu sự quyết liệt cần thiết. Khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với anh chị em.', 'negative', 0),

-- ============================
-- PHA_QUAN (Phá Quân)
-- ============================

-- PHA_QUAN tại TAT_ACH
('PHA_QUAN_TAT_ACH_MIEU', 'Phá Quân miếu địa tại cung Tật Ách thể hiện khả năng thay đổi và đổi mới trong việc quản lý sức khỏe. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Tật Ách tạo nên xu hướng có khả năng đối mặt với các vấn đề sức khỏe một cách sáng tạo và linh hoạt. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc duy trì và cải thiện thể trạng. Thể trạng có xu hướng ổn định với khả năng thích ứng và đổi mới trong cách chăm sóc sức khỏe. Tính chất đổi mới giúp có khả năng tìm ra các phương pháp mới để duy trì sức khỏe. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không kiên định trong việc chăm sóc sức khỏe hoặc thay đổi phương pháp quá thường xuyên.', 'positive', 0),
('PHA_QUAN_TAT_ACH_VUONG', 'Phá Quân vượng địa tại cung Tật Ách mang lại khả năng quản lý sức khỏe với tính đổi mới và linh hoạt ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng thích ứng và đổi mới trong cách tiếp cận sức khỏe. Tính chất đổi mới giúp có khả năng tìm ra các giải pháp hiệu quả cho các vấn đề sức khỏe. Có xu hướng tạo được sự linh hoạt trong việc chăm sóc và duy trì sức khỏe. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự kiên định để tránh xu hướng thay đổi quá thường xuyên.', 'positive', 0),
('PHA_QUAN_TAT_ACH_DAC', 'Phá Quân đắc địa tại cung Tật Ách cho thấy khả năng quản lý sức khỏe ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng thích ứng và đổi mới một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng cải thiện cách chăm sóc sức khỏe mà không quá bất ổn. Có khả năng duy trì thể trạng với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các phương pháp truyền thống đã hiệu quả do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_TAT_ACH_BINH', 'Phá Quân bình địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc duy trì thể trạng. Thể trạng có xu hướng ở mức độ trung bình với khả năng chăm sóc sức khỏe ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra các phương pháp mới hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện tình trạng sức khỏe. Có thể cần cải thiện khả năng đổi mới trong việc chăm sóc sức khỏe.', 'neutral', 0),
('PHA_QUAN_TAT_ACH_HAM', 'Phá Quân hãm địa tại cung Tật Ách cho thấy khó khăn trong việc quản lý và duy trì sức khỏe. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc duy trì thể trạng, thậm chí có thể gây ra những khó khăn về sự ổn định. Thể trạng có xu hướng không ổn định với khả năng chăm sóc sức khỏe bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc không tìm ra giải pháp hiệu quả hoặc thay đổi phương pháp một cách thiếu cân nhắc. Khó khăn trong việc duy trì thể trạng ổn định với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng sức khỏe.', 'negative', 0),

-- PHA_QUAN tại DIEN_TRACH
('PHA_QUAN_DIEN_TRACH_MIEU', 'Phá Quân miếu địa tại cung Điền Trạch thể hiện khả năng thay đổi và đổi mới trong việc quản lý tài sản bất động sản. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Điền Trạch tạo nên xu hướng có khả năng tích lũy và phát triển tài sản bất động sản thông qua các phương pháp đổi mới. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư vào đất đai, nhà cửa. Tài sản bất động sản có xu hướng phát triển với khả năng đổi mới và sáng tạo trong các quyết định đầu tư. Tính chất cách mạng giúp có khả năng tận dụng các cơ hội mới và phá vỡ các quy tắc cũ. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến các quyết định đầu tư thiếu ổn định hoặc thay đổi phương hướng quá thường xuyên.', 'positive', 0),
('PHA_QUAN_DIEN_TRACH_VUONG', 'Phá Quân vượng địa tại cung Điền Trạch mang lại khả năng phát triển tài sản bất động sản với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tài sản. Tài sản bất động sản có xu hướng phát triển với khả năng đổi mới và sáng tạo. Tính chất đổi mới giúp có khả năng tận dụng tốt các cơ hội đầu tư mới. Có xu hướng tạo được sự phát triển thông qua các phương pháp đổi mới. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh các quyết định đầu tư rủi ro.', 'positive', 0),
('PHA_QUAN_DIEN_TRACH_DAC', 'Phá Quân đắc địa tại cung Điền Trạch cho thấy khả năng quản lý tài sản bất động sản ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc tích lũy và quản lý đất đai, nhà cửa. Tài sản bất động sản có xu hướng ổn định với khả năng đổi mới một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng tận dụng các cơ hội mà không quá bất ổn. Có khả năng duy trì và phát triển tài sản với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các phương pháp truyền thống đã hiệu quả do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_DIEN_TRACH_BINH', 'Phá Quân bình địa tại cung Điền Trạch thể hiện khả năng quản lý tài sản bất động sản ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý tài sản. Tài sản bất động sản có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc bỏ lỡ các cơ hội đầu tư mới hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài sản. Có thể cần cải thiện khả năng đổi mới trong việc quản lý tài sản.', 'neutral', 0),
('PHA_QUAN_DIEN_TRACH_HAM', 'Phá Quân hãm địa tại cung Điền Trạch cho thấy khó khăn trong việc tích lũy và quản lý tài sản bất động sản. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc phát triển đất đai, nhà cửa, thậm chí có thể gây ra những khó khăn về sự ổn định. Tài sản bất động sản có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến các quyết định đầu tư sai lầm hoặc thay đổi phương hướng một cách thiếu cân nhắc. Khó khăn trong việc tích lũy và duy trì tài sản với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài sản bất động sản.', 'negative', 0),

-- PHA_QUAN tại PHU_THE
('PHA_QUAN_PHU_THE_MIEU', 'Phá Quân miếu địa tại cung Phu Thê thể hiện tính cách đổi mới và thay đổi trong mối quan hệ hôn nhân. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Phu Thê tạo nên xu hướng có khả năng xây dựng quan hệ hôn nhân với sự linh hoạt và đổi mới. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc xây dựng và duy trì mối quan hệ. Quan hệ hôn nhân có xu hướng phát triển với khả năng thích ứng và đổi mới trong cách tiếp cận. Tính chất cách mạng giúp có khả năng phá vỡ các quy tắc cũ và tạo ra cách thức mới trong quan hệ. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không ổn định trong quan hệ hoặc thay đổi phương cách quá thường xuyên.', 'positive', 0),
('PHA_QUAN_PHU_THE_VUONG', 'Phá Quân vượng địa tại cung Phu Thê mang lại khả năng xây dựng quan hệ hôn nhân với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì và phát triển mối quan hệ. Quan hệ hôn nhân có xu hướng phát triển với khả năng thích ứng và đổi mới. Tính chất đổi mới giúp có khả năng giải quyết các vấn đề một cách sáng tạo. Có xu hướng tạo được sự linh hoạt và phát triển trong quan hệ. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh xu hướng bất ổn.', 'positive', 0),
('PHA_QUAN_PHU_THE_DAC', 'Phá Quân đắc địa tại cung Phu Thê cho thấy khả năng duy trì quan hệ hôn nhân ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ổn định với khả năng thích ứng và đổi mới một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng giải quyết các vấn đề mà không quá bất ổn. Có khả năng duy trì và phát triển mối quan hệ với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các giá trị truyền thống đã ổn định do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_PHU_THE_BINH', 'Phá Quân bình địa tại cung Phu Thê thể hiện khả năng duy trì quan hệ hôn nhân ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ở mức độ trung bình với khả năng giải quyết các vấn đề ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra cách thức mới hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ. Có thể cần cải thiện khả năng đổi mới trong việc giải quyết các vấn đề quan hệ.', 'neutral', 0),
('PHA_QUAN_PHU_THE_HAM', 'Phá Quân hãm địa tại cung Phu Thê cho thấy khó khăn trong việc duy trì và phát triển quan hệ hôn nhân. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự ổn định. Quan hệ hôn nhân có xu hướng không ổn định với khả năng giải quyết các vấn đề bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi phương cách một cách thiếu cân nhắc hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ hôn nhân.', 'negative', 0),

-- PHA_QUAN tại TU_TUC
('PHA_QUAN_TU_TUC_MIEU', 'Phá Quân miếu địa tại cung Tử Tức thể hiện khả năng giáo dục con cái với tính đổi mới và sáng tạo. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Tử Tức tạo nên xu hướng có khả năng giáo dục con cái với phương pháp đổi mới và linh hoạt. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng phát triển với khả năng thích ứng và đổi mới trong cách giáo dục. Tính chất cách mạng giúp có khả năng phá vỡ các quy tắc giáo dục cũ và tạo ra phương pháp mới. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không kiên định trong việc giáo dục hoặc thay đổi phương pháp quá thường xuyên.', 'positive', 0),
('PHA_QUAN_TU_TUC_VUONG', 'Phá Quân vượng địa tại cung Tử Tức mang lại khả năng giáo dục con cái với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng phát triển với khả năng giáo dục và định hướng một cách sáng tạo. Tính chất đổi mới giúp có khả năng tìm ra các phương pháp giáo dục hiệu quả. Có xu hướng tạo được sự linh hoạt và phát triển trong việc giáo dục. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự kiên định để tránh xu hướng bất ổn trong giáo dục.', 'positive', 0),
('PHA_QUAN_TU_TUC_DAC', 'Phá Quân đắc địa tại cung Tử Tức cho thấy khả năng giáo dục con cái ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ổn định với khả năng giáo dục một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng áp dụng phương pháp mới mà không quá bất ổn. Có khả năng duy trì và phát triển mối quan hệ với con cái với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các phương pháp giáo dục truyền thống đã hiệu quả do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_TU_TUC_BINH', 'Phá Quân bình địa tại cung Tử Tức thể hiện khả năng giáo dục con cái ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ở mức độ trung bình với khả năng giáo dục ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra phương pháp giáo dục hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với con cái. Có thể cần cải thiện khả năng đổi mới trong việc giáo dục con cái.', 'neutral', 0),
('PHA_QUAN_TU_TUC_HAM', 'Phá Quân hãm địa tại cung Tử Tức cho thấy khó khăn trong việc giáo dục và quản lý con cái. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái, thậm chí có thể gây ra những khó khăn về sự ổn định. Quan hệ với con cái có xu hướng không ổn định với khả năng giáo dục và định hướng bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi phương pháp giáo dục một cách thiếu cân nhắc hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với con cái với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với con cái.', 'negative', 0),

-- PHA_QUAN tại PHUC_DUC
('PHA_QUAN_PHUC_DUC_MIEU', 'Phá Quân miếu địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức thông qua hành động đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Phúc Đức tạo nên xu hướng có khả năng tạo dựng phúc đức thông qua các hành động đổi mới và sáng tạo. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy với khả năng tạo ra những thay đổi tích cực. Tính chất cách mạng giúp có khả năng phá vỡ các quy tắc cũ và tạo ra cách thức mới trong việc tích lũy phúc đức. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không kiên định trong việc hành động tích cực hoặc thay đổi phương hướng quá thường xuyên.', 'positive', 0),
('PHA_QUAN_PHUC_DUC_VUONG', 'Phá Quân vượng địa tại cung Phúc Đức mang lại khả năng tích lũy phúc đức với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tạo dựng và tích lũy phúc đức. Phúc đức có xu hướng tích lũy với khả năng tạo ra những thay đổi tích cực. Tính chất đổi mới giúp có khả năng tìm ra các cách thức mới để tích lũy phúc đức. Có xu hướng tạo được phúc đức thông qua các hành động đổi mới. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự kiên định để tránh xu hướng không ổn định.', 'positive', 0),
('PHA_QUAN_PHUC_DUC_DAC', 'Phá Quân đắc địa tại cung Phúc Đức cho thấy khả năng tích lũy phúc đức ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc tạo dựng phúc đức. Phúc đức có xu hướng tích lũy ổn định với khả năng hành động một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng tạo ra thay đổi tích cực mà không quá bất ổn. Có khả năng duy trì và phát triển phúc đức với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cách thức truyền thống đã hiệu quả do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_PHUC_DUC_BINH', 'Phá Quân bình địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy ở mức độ trung bình với khả năng hành động ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra cách thức mới để tích lũy phúc đức hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển phúc đức. Có thể cần cải thiện khả năng đổi mới trong việc tạo dựng phúc đức.', 'neutral', 0),
('PHA_QUAN_PHUC_DUC_HAM', 'Phá Quân hãm địa tại cung Phúc Đức cho thấy khó khăn trong việc tích lũy và phát triển phúc đức. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc tạo dựng phúc đức, thậm chí có thể gây ra những khó khăn về sự ổn định. Phúc đức có xu hướng tích lũy chậm hoặc không ổn định với khả năng hành động tích cực bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi phương hướng một cách thiếu cân nhắc hoặc không tìm ra cách thức hiệu quả. Khó khăn trong việc tích lũy và duy trì phúc đức với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng phúc đức.', 'negative', 0),

-- PHA_QUAN tại THIEN_DI
('PHA_QUAN_THIEN_DI_MIEU', 'Phá Quân miếu địa tại cung Thiên Di thể hiện khả năng thích ứng và phát triển trong môi trường mới với tính đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Thiên Di tạo nên xu hướng có khả năng đối mặt với các thay đổi và thách thức trong môi trường mới một cách sáng tạo. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc thích ứng và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với tính đổi mới và linh hoạt. Tính chất cách mạng giúp có khả năng phá vỡ các rào cản và tạo ra cơ hội mới. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không ổn định trong môi trường mới hoặc thay đổi quá thường xuyên.', 'positive', 0),
('PHA_QUAN_THIEN_DI_VUONG', 'Phá Quân vượng địa tại cung Thiên Di mang lại khả năng thích ứng với môi trường mới với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc đối mặt với thay đổi và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với tính đổi mới và linh hoạt. Tính chất đổi mới giúp có khả năng xử lý nhanh chóng các tình huống mới. Có xu hướng tạo được sự phát triển trong môi trường mới. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh xu hướng bất ổn.', 'positive', 0),
('PHA_QUAN_THIEN_DI_DAC', 'Phá Quân đắc địa tại cung Thiên Di cho thấy khả năng thích ứng với môi trường mới ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ổn định với tính đổi mới vừa phải. Tính đổi mới ở mức độ vừa phải giúp có khả năng xử lý các tình huống mới một cách cân nhắc. Có khả năng duy trì và phát triển trong môi trường mới với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng đổi mới không đủ mạnh.', 'neutral', 0),
('PHA_QUAN_THIEN_DI_BINH', 'Phá Quân bình địa tại cung Thiên Di thể hiện khả năng thích ứng với môi trường mới ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ở mức độ trung bình với tính đổi mới không đủ mạnh. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không xử lý kịp thời các tình huống mới hoặc thiếu sự linh hoạt. Cần nhiều thời gian và nỗ lực để thích ứng và phát triển trong môi trường mới. Có thể cần cải thiện khả năng đổi mới trong việc đối mặt với thay đổi.', 'neutral', 0),
('PHA_QUAN_THIEN_DI_HAM', 'Phá Quân hãm địa tại cung Thiên Di cho thấy khó khăn trong việc thích ứng và phát triển trong môi trường mới. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc đối mặt với thay đổi, thậm chí có thể gây ra những khó khăn về sự ổn định. Khả năng thích ứng với môi trường mới có xu hướng kém với tính đổi mới bị suy giảm. Tính đổi mới bị suy giảm, có thể dẫn đến việc không xử lý kịp thời các tình huống mới hoặc thay đổi một cách thiếu cân nhắc. Khó khăn trong việc thích ứng và phát triển trong môi trường mới với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện khả năng thích ứng với môi trường mới.', 'negative', 0),

-- PHA_QUAN tại NO_BOC
('PHA_QUAN_NO_BOC_MIEU', 'Phá Quân miếu địa tại cung Nô Bộc thể hiện khả năng quản lý người dưới quyền với tính đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Nô Bộc tạo nên xu hướng có khả năng quản lý và điều hành người dưới quyền với phương pháp đổi mới và linh hoạt. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc quản lý quan hệ với người dưới quyền. Quan hệ với người dưới quyền có xu hướng phát triển với khả năng thích ứng và đổi mới trong cách quản lý. Tính chất cách mạng giúp có khả năng phá vỡ các quy tắc quản lý cũ và tạo ra phương pháp mới. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không kiên định trong việc quản lý hoặc thay đổi phương pháp quá thường xuyên.', 'positive', 0),
('PHA_QUAN_NO_BOC_VUONG', 'Phá Quân vượng địa tại cung Nô Bộc mang lại khả năng quản lý người dưới quyền với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng phát triển với khả năng quản lý một cách sáng tạo. Tính chất đổi mới giúp có khả năng tìm ra các phương pháp quản lý hiệu quả. Có xu hướng tạo được sự linh hoạt và phát triển trong việc quản lý. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh xu hướng bất ổn trong quản lý.', 'positive', 0),
('PHA_QUAN_NO_BOC_DAC', 'Phá Quân đắc địa tại cung Nô Bộc cho thấy khả năng quản lý người dưới quyền ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng ổn định với khả năng quản lý một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng áp dụng phương pháp mới mà không quá bất ổn. Có khả năng duy trì và phát triển quan hệ với người dưới quyền với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các phương pháp quản lý truyền thống đã hiệu quả do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_NO_BOC_BINH', 'Phá Quân bình địa tại cung Nô Bộc thể hiện khả năng quản lý người dưới quyền ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc quản lý và điều hành. Quan hệ với người dưới quyền có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra phương pháp quản lý hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển quan hệ với người dưới quyền. Có thể cần cải thiện khả năng đổi mới trong việc quản lý.', 'neutral', 0),
('PHA_QUAN_NO_BOC_HAM', 'Phá Quân hãm địa tại cung Nô Bộc cho thấy khó khăn trong việc quản lý và điều hành người dưới quyền. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc quản lý, thậm chí có thể gây ra những khó khăn về sự ổn định. Quan hệ với người dưới quyền có xu hướng không ổn định với khả năng quản lý và điều hành bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi phương pháp quản lý một cách thiếu cân nhắc hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển quan hệ với người dưới quyền với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quản lý.', 'negative', 0),

-- PHA_QUAN tại PHU_MAU
('PHA_QUAN_PHU_MAU_MIEU', 'Phá Quân miếu địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ có tính đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Phụ Mẫu tạo nên xu hướng có mối quan hệ với cha mẹ với sự linh hoạt và đổi mới. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng phát triển với khả năng thích ứng và đổi mới trong cách tiếp cận. Tính chất cách mạng giúp có khả năng phá vỡ các quy tắc truyền thống và tạo ra cách thức mới. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không ổn định trong quan hệ hoặc xung đột do sự khác biệt về quan điểm.', 'positive', 0),
('PHA_QUAN_PHU_MAU_VUONG', 'Phá Quân vượng địa tại cung Phụ Mẫu mang lại mối quan hệ với cha mẹ với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng phát triển với tính đổi mới và linh hoạt. Tính chất đổi mới giúp có khả năng giải quyết các vấn đề một cách sáng tạo. Có xu hướng tạo được sự linh hoạt và phát triển trong mối quan hệ. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự tôn trọng truyền thống để tránh xung đột.', 'positive', 0),
('PHA_QUAN_PHU_MAU_DAC', 'Phá Quân đắc địa tại cung Phụ Mẫu cho thấy mối quan hệ với cha mẹ ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ổn định với tính đổi mới vừa phải. Tính đổi mới ở mức độ vừa phải giúp có khả năng giải quyết các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với cha mẹ với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các giá trị truyền thống do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_PHU_MAU_BINH', 'Phá Quân bình địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra cách thức mới hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với cha mẹ. Có thể cần cải thiện khả năng đổi mới trong việc xử lý các vấn đề liên quan đến cha mẹ.', 'neutral', 0),
('PHA_QUAN_PHU_MAU_HAM', 'Phá Quân hãm địa tại cung Phụ Mẫu cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự ổn định. Mối quan hệ với cha mẹ có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi cách tiếp cận một cách thiếu cân nhắc hoặc xung đột do sự khác biệt. Khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với cha mẹ.', 'negative', 0),

-- PHA_QUAN tại HUYNH_DE
('PHA_QUAN_HUYNH_DE_MIEU', 'Phá Quân miếu địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em có tính đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Huynh Đệ tạo nên xu hướng có mối quan hệ với anh chị em với sự linh hoạt và đổi mới. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng phát triển với khả năng thích ứng và đổi mới trong cách tiếp cận. Tính chất cách mạng giúp có khả năng phá vỡ các rào cản và tạo ra cách thức mới trong quan hệ. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không ổn định trong quan hệ hoặc cạnh tranh quá mức.', 'positive', 0),
('PHA_QUAN_HUYNH_DE_VUONG', 'Phá Quân vượng địa tại cung Huynh Đệ mang lại mối quan hệ với anh chị em với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng phát triển với tính đổi mới và linh hoạt. Tính chất đổi mới giúp có khả năng giải quyết các vấn đề một cách sáng tạo. Có xu hướng tạo được sự linh hoạt và phát triển trong mối quan hệ. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh xu hướng cạnh tranh quá mức.', 'positive', 0),
('PHA_QUAN_HUYNH_DE_DAC', 'Phá Quân đắc địa tại cung Huynh Đệ cho thấy mối quan hệ với anh chị em ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ổn định với tính đổi mới vừa phải. Tính đổi mới ở mức độ vừa phải giúp có khả năng giải quyết các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với anh chị em với sự linh hoạt hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các giá trị gia đình do xu hướng đổi mới.', 'neutral', 0),
('PHA_QUAN_HUYNH_DE_BINH', 'Phá Quân bình địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra cách thức mới hiệu quả hoặc thiếu sự linh hoạt. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với anh chị em. Có thể cần cải thiện khả năng đổi mới trong việc xử lý các vấn đề liên quan đến anh chị em.', 'neutral', 0),
('PHA_QUAN_HUYNH_DE_HAM', 'Phá Quân hãm địa tại cung Huynh Đệ cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự ổn định. Mối quan hệ với anh chị em có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến việc thay đổi cách tiếp cận một cách thiếu cân nhắc hoặc cạnh tranh không lành mạnh. Khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với anh chị em.', 'negative', 0),

-- ============================
-- THAM_LANG (Tham Lang)
-- ============================

-- THAM_LANG tại TAT_ACH
('THAM_LANG_TAT_ACH_MIEU', 'Tham Lang miếu địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Tật Ách tạo nên xu hướng có khả năng hiểu biết và quản lý sức khỏe một cách thông minh và linh hoạt. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc duy trì và bảo vệ thể trạng. Thể trạng có xu hướng ổn định với khả năng tìm hiểu và áp dụng các phương pháp chăm sóc sức khỏe hiệu quả. Tính chất thông minh giúp có khả năng nhận biết các dấu hiệu sớm và xử lý các vấn đề sức khỏe một cách nhanh chóng. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng phân tán sự chú ý hoặc thay đổi phương pháp quá thường xuyên do tìm hiểu quá nhiều.', 'positive', 0),
('THAM_LANG_TAT_ACH_VUONG', 'Tham Lang vượng địa tại cung Tật Ách mang lại khả năng quản lý sức khỏe với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng tìm hiểu và áp dụng các phương pháp chăm sóc sức khỏe hiệu quả. Tính chất thông minh giúp có khả năng nhận biết và xử lý các vấn đề sức khỏe một cách nhanh chóng. Có xu hướng tạo được sự hiểu biết sâu sắc về các vấn đề sức khỏe. Tuy nhiên, cần cân bằng giữa sự thông minh và sự kiên định để tránh xu hướng phân tán hoặc thay đổi quá thường xuyên.', 'positive', 0),
('THAM_LANG_TAT_ACH_DAC', 'Tham Lang đắc địa tại cung Tật Ách cho thấy khả năng quản lý sức khỏe ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng hiểu biết và quản lý sức khỏe một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng tìm hiểu và áp dụng phương pháp hiệu quả mà không quá phân tán. Có khả năng duy trì thể trạng với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các dấu hiệu quan trọng do xu hướng phân tán sự chú ý.', 'neutral', 0),
('THAM_LANG_TAT_ACH_BINH', 'Tham Lang bình địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc duy trì thể trạng. Thể trạng có xu hướng ở mức độ trung bình với khả năng chăm sóc sức khỏe ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không tìm hiểu đủ sâu về các vấn đề sức khỏe hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện tình trạng sức khỏe. Có thể cần cải thiện khả năng tìm hiểu và hiểu biết về các vấn đề sức khỏe.', 'neutral', 0),
('THAM_LANG_TAT_ACH_HAM', 'Tham Lang hãm địa tại cung Tật Ách cho thấy khó khăn trong việc quản lý và duy trì sức khỏe. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc duy trì thể trạng, thậm chí có thể gây ra những khó khăn về sự nhạy bén. Thể trạng có xu hướng không ổn định với khả năng hiểu biết và quản lý sức khỏe bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không nhận biết kịp thời các dấu hiệu hoặc không tìm ra phương pháp hiệu quả. Khó khăn trong việc duy trì thể trạng ổn định với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và chú ý đặc biệt để cải thiện và duy trì tình trạng sức khỏe.', 'negative', 0),

-- THAM_LANG tại DIEN_TRACH
('THAM_LANG_DIEN_TRACH_MIEU', 'Tham Lang miếu địa tại cung Điền Trạch thể hiện khả năng quản lý tài sản bất động sản với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Điền Trạch tạo nên xu hướng có khả năng tích lũy và phát triển tài sản bất động sản thông qua sự thông minh và tính toán. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư vào đất đai, nhà cửa. Tài sản bất động sản có xu hướng phát triển với khả năng tính toán và đưa ra quyết định đầu tư thông minh. Tính chất tài trí giúp có khả năng nắm bắt các cơ hội đầu tư và quản lý tài sản một cách hiệu quả. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tham lam hoặc phân tán đầu tư vào quá nhiều nơi.', 'positive', 0),
('THAM_LANG_DIEN_TRACH_VUONG', 'Tham Lang vượng địa tại cung Điền Trạch mang lại khả năng phát triển tài sản bất động sản với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tài sản. Tài sản bất động sản có xu hướng phát triển với khả năng tính toán và đưa ra quyết định đầu tư thông minh. Tính chất tài trí giúp có khả năng nắm bắt và tận dụng tốt các cơ hội đầu tư. Có xu hướng tạo được sự phát triển thông qua sự thông minh và tính toán. Tuy nhiên, cần cân bằng giữa sự thông minh và sự thận trọng để tránh xu hướng tham lam hoặc đầu tư rủi ro.', 'positive', 0),
('THAM_LANG_DIEN_TRACH_DAC', 'Tham Lang đắc địa tại cung Điền Trạch cho thấy khả năng quản lý tài sản bất động sản ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc tích lũy và quản lý đất đai, nhà cửa. Tài sản bất động sản có xu hướng ổn định với khả năng tính toán và quản lý một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng đưa ra quyết định đầu tư hợp lý mà không quá tham lam. Có khả năng duy trì và phát triển tài sản với sự tính toán hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng thông minh không đủ mạnh.', 'neutral', 0),
('THAM_LANG_DIEN_TRACH_BINH', 'Tham Lang bình địa tại cung Điền Trạch thể hiện khả năng quản lý tài sản bất động sản ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý tài sản. Tài sản bất động sản có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không tính toán đủ kỹ các quyết định đầu tư hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài sản. Có thể cần cải thiện khả năng tính toán và nhạy bén trong việc quản lý tài sản.', 'neutral', 0),
('THAM_LANG_DIEN_TRACH_HAM', 'Tham Lang hãm địa tại cung Điền Trạch cho thấy khó khăn trong việc tích lũy và quản lý tài sản bất động sản. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc phát triển đất đai, nhà cửa, thậm chí có thể gây ra những khó khăn về tính toán. Tài sản bất động sản có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến các quyết định đầu tư thiếu tính toán hoặc không nắm bắt được cơ hội. Khó khăn trong việc tích lũy và duy trì tài sản với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài sản bất động sản.', 'negative', 0),

-- THAM_LANG tại PHU_THE
('THAM_LANG_PHU_THE_MIEU', 'Tham Lang miếu địa tại cung Phu Thê thể hiện tính cách thông minh và tài trí trong mối quan hệ hôn nhân. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Phu Thê tạo nên xu hướng có khả năng xây dựng quan hệ hôn nhân với sự thông minh và linh hoạt. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc xây dựng và duy trì mối quan hệ. Quan hệ hôn nhân có xu hướng phát triển với khả năng hiểu biết và xử lý các vấn đề một cách thông minh. Tính chất tài trí giúp có khả năng đưa ra các giải pháp sáng tạo cho các vấn đề trong quan hệ. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tính toán quá mức trong quan hệ hoặc thiếu sự chân thành.', 'positive', 0),
('THAM_LANG_PHU_THE_VUONG', 'Tham Lang vượng địa tại cung Phu Thê mang lại khả năng xây dựng quan hệ hôn nhân với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì và phát triển mối quan hệ. Quan hệ hôn nhân có xu hướng phát triển với khả năng hiểu biết và xử lý các vấn đề một cách thông minh. Tính chất tài trí giúp có khả năng đưa ra các giải pháp hiệu quả. Có xu hướng tạo được sự hiểu biết và phát triển trong quan hệ. Tuy nhiên, cần cân bằng giữa sự thông minh và sự chân thành để tránh xu hướng tính toán quá mức.', 'positive', 0),
('THAM_LANG_PHU_THE_DAC', 'Tham Lang đắc địa tại cung Phu Thê cho thấy khả năng duy trì quan hệ hôn nhân ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ổn định với khả năng hiểu biết và xử lý các vấn đề một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng đưa ra giải pháp hợp lý mà không quá tính toán. Có khả năng duy trì và phát triển mối quan hệ với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu cảm xúc do xu hướng tính toán.', 'neutral', 0),
('THAM_LANG_PHU_THE_BINH', 'Tham Lang bình địa tại cung Phu Thê thể hiện khả năng duy trì quan hệ hôn nhân ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Quan hệ hôn nhân có xu hướng ở mức độ trung bình với khả năng giải quyết các vấn đề ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các vấn đề quan hệ hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc giải quyết các vấn đề quan hệ.', 'neutral', 0),
('THAM_LANG_PHU_THE_HAM', 'Tham Lang hãm địa tại cung Phu Thê cho thấy khó khăn trong việc duy trì và phát triển quan hệ hôn nhân. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Quan hệ hôn nhân có xu hướng không ổn định với khả năng giải quyết các vấn đề bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các vấn đề hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ hôn nhân.', 'negative', 0),

-- THAM_LANG tại TU_TUC
('THAM_LANG_TU_TUC_MIEU', 'Tham Lang miếu địa tại cung Tử Tức thể hiện khả năng giáo dục con cái với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Tử Tức tạo nên xu hướng có khả năng giáo dục con cái với sự thông minh và linh hoạt. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng phát triển với khả năng hiểu biết và giáo dục một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các phương pháp giáo dục hiệu quả và phù hợp. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng kỳ vọng quá cao hoặc thay đổi phương pháp giáo dục quá thường xuyên.', 'positive', 0),
('THAM_LANG_TU_TUC_VUONG', 'Tham Lang vượng địa tại cung Tử Tức mang lại khả năng giáo dục con cái với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng phát triển với khả năng giáo dục và định hướng một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các phương pháp giáo dục hiệu quả. Có xu hướng tạo được sự hiểu biết và phát triển trong việc giáo dục. Tuy nhiên, cần cân bằng giữa sự thông minh và sự kiên nhẫn để tránh xu hướng kỳ vọng quá cao.', 'positive', 0),
('THAM_LANG_TU_TUC_DAC', 'Tham Lang đắc địa tại cung Tử Tức cho thấy khả năng giáo dục con cái ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ổn định với khả năng giáo dục một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng áp dụng phương pháp giáo dục hợp lý mà không quá kỳ vọng. Có khả năng duy trì và phát triển mối quan hệ với con cái với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu cảm xúc của con cái do xu hướng tính toán.', 'neutral', 0),
('THAM_LANG_TU_TUC_BINH', 'Tham Lang bình địa tại cung Tử Tức thể hiện khả năng giáo dục con cái ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ với con cái. Quan hệ với con cái có xu hướng ở mức độ trung bình với khả năng giáo dục ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các nhu cầu của con cái hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với con cái. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc giáo dục con cái.', 'neutral', 0),
('THAM_LANG_TU_TUC_HAM', 'Tham Lang hãm địa tại cung Tử Tức cho thấy khó khăn trong việc giáo dục và quản lý con cái. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ với con cái, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Quan hệ với con cái có xu hướng không ổn định với khả năng giáo dục và định hướng bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các nhu cầu của con cái hoặc không tìm ra phương pháp giáo dục hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với con cái với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với con cái.', 'negative', 0),

-- THAM_LANG tại PHUC_DUC
('THAM_LANG_PHUC_DUC_MIEU', 'Tham Lang miếu địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức thông qua hành động thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Phúc Đức tạo nên xu hướng có khả năng tạo dựng phúc đức thông qua các hành động thông minh và tính toán. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy với khả năng hiểu biết và hành động một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các cách thức hiệu quả để tích lũy phúc đức. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tính toán quá mức trong việc hành động tích cực hoặc thiếu sự tự nhiên.', 'positive', 0),
('THAM_LANG_PHUC_DUC_VUONG', 'Tham Lang vượng địa tại cung Phúc Đức mang lại khả năng tích lũy phúc đức với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tạo dựng và tích lũy phúc đức. Phúc đức có xu hướng tích lũy với khả năng hiểu biết và hành động một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các cách thức hiệu quả để tích lũy phúc đức. Có xu hướng tạo được phúc đức thông qua các hành động thông minh. Tuy nhiên, cần cân bằng giữa sự thông minh và sự tự nhiên để tránh xu hướng tính toán quá mức.', 'positive', 0),
('THAM_LANG_PHUC_DUC_DAC', 'Tham Lang đắc địa tại cung Phúc Đức cho thấy khả năng tích lũy phúc đức ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc tạo dựng phúc đức. Phúc đức có xu hướng tích lũy ổn định với khả năng hành động một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng tìm ra cách thức hiệu quả mà không quá tính toán. Có khả năng duy trì và phát triển phúc đức với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội tích lũy phúc đức do xu hướng tính toán không đủ mạnh.', 'neutral', 0),
('THAM_LANG_PHUC_DUC_BINH', 'Tham Lang bình địa tại cung Phúc Đức thể hiện khả năng tích lũy phúc đức ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc tích lũy phúc đức. Phúc đức có xu hướng tích lũy ở mức độ trung bình với khả năng hành động ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các cách thức tích lũy phúc đức hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển phúc đức. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc tạo dựng phúc đức.', 'neutral', 0),
('THAM_LANG_PHUC_DUC_HAM', 'Tham Lang hãm địa tại cung Phúc Đức cho thấy khó khăn trong việc tích lũy và phát triển phúc đức. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc tạo dựng phúc đức, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Phúc đức có xu hướng tích lũy chậm hoặc không ổn định với khả năng hành động tích cực bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các cách thức tích lũy phúc đức hoặc không tìm ra phương pháp hiệu quả. Khó khăn trong việc tích lũy và duy trì phúc đức với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng phúc đức.', 'negative', 0),

-- THAM_LANG tại THIEN_DI
('THAM_LANG_THIEN_DI_MIEU', 'Tham Lang miếu địa tại cung Thiên Di thể hiện khả năng thích ứng và phát triển trong môi trường mới với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Thiên Di tạo nên xu hướng có khả năng đối mặt với các thay đổi và thách thức trong môi trường mới một cách thông minh. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc thích ứng và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với tính thông minh và linh hoạt. Tính chất tài trí giúp có khả năng nắm bắt và tận dụng tốt các cơ hội trong môi trường mới. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng phân tán sự chú ý hoặc thay đổi quá thường xuyên do tìm hiểu quá nhiều.', 'positive', 0),
('THAM_LANG_THIEN_DI_VUONG', 'Tham Lang vượng địa tại cung Thiên Di mang lại khả năng thích ứng với môi trường mới với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc đối mặt với thay đổi và phát triển. Khả năng thích ứng với môi trường mới có xu hướng tốt với tính thông minh và linh hoạt. Tính chất tài trí giúp có khả năng nắm bắt và xử lý nhanh chóng các tình huống mới. Có xu hướng tạo được sự phát triển trong môi trường mới. Tuy nhiên, cần cân bằng giữa sự thông minh và sự ổn định để tránh xu hướng phân tán hoặc thay đổi quá thường xuyên.', 'positive', 0),
('THAM_LANG_THIEN_DI_DAC', 'Tham Lang đắc địa tại cung Thiên Di cho thấy khả năng thích ứng với môi trường mới ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ổn định với tính thông minh vừa phải. Tính thông minh ở mức độ vừa phải giúp có khả năng xử lý các tình huống mới một cách cân nhắc. Có khả năng duy trì và phát triển trong môi trường mới với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng phân tán sự chú ý.', 'neutral', 0),
('THAM_LANG_THIEN_DI_BINH', 'Tham Lang bình địa tại cung Thiên Di thể hiện khả năng thích ứng với môi trường mới ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc đối mặt với thay đổi. Khả năng thích ứng với môi trường mới có xu hướng ở mức độ trung bình với tính thông minh không đủ mạnh. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không nắm bắt kịp thời các cơ hội hoặc thiếu sự nhạy bén. Cần nhiều thời gian và nỗ lực để thích ứng và phát triển trong môi trường mới. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc đối mặt với thay đổi.', 'neutral', 0),
('THAM_LANG_THIEN_DI_HAM', 'Tham Lang hãm địa tại cung Thiên Di cho thấy khó khăn trong việc thích ứng và phát triển trong môi trường mới. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc đối mặt với thay đổi, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Khả năng thích ứng với môi trường mới có xu hướng kém với tính thông minh bị suy giảm. Tính thông minh bị suy giảm, có thể dẫn đến việc không nắm bắt kịp thời các tình huống mới hoặc không tìm ra cách thức hiệu quả. Khó khăn trong việc thích ứng và phát triển trong môi trường mới với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện khả năng thích ứng với môi trường mới.', 'negative', 0),

-- THAM_LANG tại NO_BOC
('THAM_LANG_NO_BOC_MIEU', 'Tham Lang miếu địa tại cung Nô Bộc thể hiện khả năng quản lý người dưới quyền với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Nô Bộc tạo nên xu hướng có khả năng quản lý và điều hành người dưới quyền với sự thông minh và linh hoạt. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc quản lý quan hệ với người dưới quyền. Quan hệ với người dưới quyền có xu hướng phát triển với khả năng hiểu biết và quản lý một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các phương pháp quản lý hiệu quả và phù hợp. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tính toán quá mức trong quản lý hoặc thiếu sự chân thành.', 'positive', 0),
('THAM_LANG_NO_BOC_VUONG', 'Tham Lang vượng địa tại cung Nô Bộc mang lại khả năng quản lý người dưới quyền với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng phát triển với khả năng quản lý một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các phương pháp quản lý hiệu quả. Có xu hướng tạo được sự hiểu biết và phát triển trong việc quản lý. Tuy nhiên, cần cân bằng giữa sự thông minh và sự công bằng để tránh xu hướng tính toán quá mức.', 'positive', 0),
('THAM_LANG_NO_BOC_DAC', 'Tham Lang đắc địa tại cung Nô Bộc cho thấy khả năng quản lý người dưới quyền ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc điều hành và quản lý. Quan hệ với người dưới quyền có xu hướng ổn định với khả năng quản lý một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng áp dụng phương pháp quản lý hợp lý mà không quá tính toán. Có khả năng duy trì và phát triển quan hệ với người dưới quyền với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của người dưới quyền do xu hướng tính toán.', 'neutral', 0),
('THAM_LANG_NO_BOC_BINH', 'Tham Lang bình địa tại cung Nô Bộc thể hiện khả năng quản lý người dưới quyền ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc quản lý và điều hành. Quan hệ với người dưới quyền có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các nhu cầu của người dưới quyền hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển quan hệ với người dưới quyền. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc quản lý.', 'neutral', 0),
('THAM_LANG_NO_BOC_HAM', 'Tham Lang hãm địa tại cung Nô Bộc cho thấy khó khăn trong việc quản lý và điều hành người dưới quyền. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc quản lý, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Quan hệ với người dưới quyền có xu hướng không ổn định với khả năng quản lý và điều hành bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các nhu cầu của người dưới quyền hoặc không tìm ra phương pháp quản lý hiệu quả. Khó khăn trong việc duy trì và phát triển quan hệ với người dưới quyền với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quản lý.', 'negative', 0),

-- THAM_LANG tại PHU_MAU
('THAM_LANG_PHU_MAU_MIEU', 'Tham Lang miếu địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ có tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Phụ Mẫu tạo nên xu hướng có mối quan hệ với cha mẹ với sự thông minh và hiểu biết. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng phát triển với khả năng hiểu biết và xử lý các vấn đề một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các giải pháp sáng tạo cho các vấn đề liên quan đến cha mẹ. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tính toán quá mức trong quan hệ hoặc thiếu sự chân thành.', 'positive', 0),
('THAM_LANG_PHU_MAU_VUONG', 'Tham Lang vượng địa tại cung Phụ Mẫu mang lại mối quan hệ với cha mẹ với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng phát triển với tính thông minh và hiểu biết. Tính chất tài trí giúp có khả năng xử lý các vấn đề một cách hiệu quả. Có xu hướng tạo được sự hiểu biết và phát triển trong mối quan hệ. Tuy nhiên, cần cân bằng giữa sự thông minh và sự chân thành để tránh xu hướng tính toán quá mức.', 'positive', 0),
('THAM_LANG_PHU_MAU_DAC', 'Tham Lang đắc địa tại cung Phụ Mẫu cho thấy mối quan hệ với cha mẹ ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ổn định với tính thông minh vừa phải. Tính thông minh ở mức độ vừa phải giúp có khả năng xử lý các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với cha mẹ với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu cảm xúc của cha mẹ do xu hướng tính toán.', 'neutral', 0),
('THAM_LANG_PHU_MAU_BINH', 'Tham Lang bình địa tại cung Phụ Mẫu thể hiện mối quan hệ với cha mẹ ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với cha mẹ có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các vấn đề liên quan đến cha mẹ hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với cha mẹ. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc xử lý các vấn đề liên quan đến cha mẹ.', 'neutral', 0),
('THAM_LANG_PHU_MAU_HAM', 'Tham Lang hãm địa tại cung Phụ Mẫu cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Mối quan hệ với cha mẹ có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các vấn đề hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với cha mẹ với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với cha mẹ.', 'negative', 0),

-- THAM_LANG tại HUYNH_DE
('THAM_LANG_HUYNH_DE_MIEU', 'Tham Lang miếu địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em có tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Huynh Đệ tạo nên xu hướng có mối quan hệ với anh chị em với sự thông minh và linh hoạt. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng phát triển với khả năng hiểu biết và xử lý các vấn đề một cách thông minh. Tính chất tài trí giúp có khả năng tìm ra các giải pháp sáng tạo cho các vấn đề liên quan đến anh chị em. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tính toán quá mức trong quan hệ hoặc cạnh tranh không lành mạnh.', 'positive', 0),
('THAM_LANG_HUYNH_DE_VUONG', 'Tham Lang vượng địa tại cung Huynh Đệ mang lại mối quan hệ với anh chị em với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng phát triển với tính thông minh và linh hoạt. Tính chất tài trí giúp có khả năng xử lý các vấn đề một cách hiệu quả. Có xu hướng tạo được sự hiểu biết và phát triển trong mối quan hệ. Tuy nhiên, cần cân bằng giữa sự thông minh và sự hòa thuận để tránh xu hướng cạnh tranh không lành mạnh.', 'positive', 0),
('THAM_LANG_HUYNH_DE_DAC', 'Tham Lang đắc địa tại cung Huynh Đệ cho thấy mối quan hệ với anh chị em ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ổn định với tính thông minh vừa phải. Tính thông minh ở mức độ vừa phải giúp có khả năng xử lý các vấn đề một cách cân nhắc. Có khả năng duy trì và phát triển mối quan hệ với anh chị em với sự hiểu biết hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các nhu cầu của anh chị em do xu hướng tính toán.', 'neutral', 0),
('THAM_LANG_HUYNH_DE_BINH', 'Tham Lang bình địa tại cung Huynh Đệ thể hiện mối quan hệ với anh chị em ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc xây dựng mối quan hệ. Mối quan hệ với anh chị em có xu hướng ở mức độ trung bình với khả năng xử lý các vấn đề ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không hiểu biết đủ sâu về các vấn đề liên quan đến anh chị em hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để cải thiện và phát triển mối quan hệ với anh chị em. Có thể cần cải thiện khả năng hiểu biết và nhạy bén trong việc xử lý các vấn đề liên quan đến anh chị em.', 'neutral', 0),
('THAM_LANG_HUYNH_DE_HAM', 'Tham Lang hãm địa tại cung Huynh Đệ cho thấy khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc xây dựng mối quan hệ, thậm chí có thể gây ra những khó khăn về sự hiểu biết. Mối quan hệ với anh chị em có xu hướng không ổn định với khả năng xử lý các vấn đề bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến việc không hiểu biết đầy đủ về các vấn đề hoặc không tìm ra giải pháp hiệu quả. Khó khăn trong việc duy trì và phát triển mối quan hệ với anh chị em với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và kiên nhẫn đặc biệt để cải thiện tình trạng quan hệ với anh chị em.', 'negative', 0);
