-- ============================================================
-- RULES CHO CHỦ THÂN (Body Master Star)
-- Format: {STAR_CODE}_CHU_THAN_{BRIGHTNESS}
-- Rule format: {"role": "CHU_THAN", "star": "<STAR_CODE>", "brightness": "<BRIGHTNESS>"}
-- Total: 14 stars × 5 brightness = 70 rules
-- ============================================================

INSERT INTO interpretation_rules (fragment_code, conditions) VALUES
('TU_VI_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "TU_VI", "brightness": "MIEU"}'),
('TU_VI_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "TU_VI", "brightness": "VUONG"}'),
('TU_VI_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "TU_VI", "brightness": "DAC"}'),
('TU_VI_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "TU_VI", "brightness": "BINH"}'),
('TU_VI_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "TU_VI", "brightness": "HAM"}'),
('THIEN_CO_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THIEN_CO", "brightness": "MIEU"}'),
('THIEN_CO_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THIEN_CO", "brightness": "VUONG"}'),
('THIEN_CO_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THIEN_CO", "brightness": "DAC"}'),
('THIEN_CO_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THIEN_CO", "brightness": "BINH"}'),
('THIEN_CO_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THIEN_CO", "brightness": "HAM"}'),
('THAI_DUONG_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THAI_DUONG", "brightness": "MIEU"}'),
('THAI_DUONG_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THAI_DUONG", "brightness": "VUONG"}'),
('THAI_DUONG_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THAI_DUONG", "brightness": "DAC"}'),
('THAI_DUONG_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THAI_DUONG", "brightness": "BINH"}'),
('THAI_DUONG_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THAI_DUONG", "brightness": "HAM"}'),
('VU_KHUC_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "VU_KHUC", "brightness": "MIEU"}'),
('VU_KHUC_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "VU_KHUC", "brightness": "VUONG"}'),
('VU_KHUC_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "VU_KHUC", "brightness": "DAC"}'),
('VU_KHUC_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "VU_KHUC", "brightness": "BINH"}'),
('VU_KHUC_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "VU_KHUC", "brightness": "HAM"}'),
('THIEN_DONG_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THIEN_DONG", "brightness": "MIEU"}'),
('THIEN_DONG_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THIEN_DONG", "brightness": "VUONG"}'),
('THIEN_DONG_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THIEN_DONG", "brightness": "DAC"}'),
('THIEN_DONG_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THIEN_DONG", "brightness": "BINH"}'),
('THIEN_DONG_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THIEN_DONG", "brightness": "HAM"}'),
('LIEM_TRINH_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "LIEM_TRINH", "brightness": "MIEU"}'),
('LIEM_TRINH_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "LIEM_TRINH", "brightness": "VUONG"}'),
('LIEM_TRINH_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "LIEM_TRINH", "brightness": "DAC"}'),
('LIEM_TRINH_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "LIEM_TRINH", "brightness": "BINH"}'),
('LIEM_TRINH_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "LIEM_TRINH", "brightness": "HAM"}'),
('THIEN_PHU_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THIEN_PHU", "brightness": "MIEU"}'),
('THIEN_PHU_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THIEN_PHU", "brightness": "VUONG"}'),
('THIEN_PHU_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THIEN_PHU", "brightness": "DAC"}'),
('THIEN_PHU_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THIEN_PHU", "brightness": "BINH"}'),
('THIEN_PHU_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THIEN_PHU", "brightness": "HAM"}'),
('THAI_AM_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THAI_AM", "brightness": "MIEU"}'),
('THAI_AM_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THAI_AM", "brightness": "VUONG"}'),
('THAI_AM_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THAI_AM", "brightness": "DAC"}'),
('THAI_AM_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THAI_AM", "brightness": "BINH"}'),
('THAI_AM_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THAI_AM", "brightness": "HAM"}'),
('THAM_LANG_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THAM_LANG", "brightness": "MIEU"}'),
('THAM_LANG_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THAM_LANG", "brightness": "VUONG"}'),
('THAM_LANG_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THAM_LANG", "brightness": "DAC"}'),
('THAM_LANG_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THAM_LANG", "brightness": "BINH"}'),
('THAM_LANG_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THAM_LANG", "brightness": "HAM"}'),
('CU_MON_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "CU_MON", "brightness": "MIEU"}'),
('CU_MON_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "CU_MON", "brightness": "VUONG"}'),
('CU_MON_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "CU_MON", "brightness": "DAC"}'),
('CU_MON_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "CU_MON", "brightness": "BINH"}'),
('CU_MON_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "CU_MON", "brightness": "HAM"}'),
('THIEN_TUONG_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THIEN_TUONG", "brightness": "MIEU"}'),
('THIEN_TUONG_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THIEN_TUONG", "brightness": "VUONG"}'),
('THIEN_TUONG_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THIEN_TUONG", "brightness": "DAC"}'),
('THIEN_TUONG_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THIEN_TUONG", "brightness": "BINH"}'),
('THIEN_TUONG_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THIEN_TUONG", "brightness": "HAM"}'),
('THIEN_LUONG_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THIEN_LUONG", "brightness": "MIEU"}'),
('THIEN_LUONG_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THIEN_LUONG", "brightness": "VUONG"}'),
('THIEN_LUONG_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THIEN_LUONG", "brightness": "DAC"}'),
('THIEN_LUONG_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THIEN_LUONG", "brightness": "BINH"}'),
('THIEN_LUONG_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THIEN_LUONG", "brightness": "HAM"}'),
('THAT_SAT_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "THAT_SAT", "brightness": "MIEU"}'),
('THAT_SAT_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "THAT_SAT", "brightness": "VUONG"}'),
('THAT_SAT_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "THAT_SAT", "brightness": "DAC"}'),
('THAT_SAT_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "THAT_SAT", "brightness": "BINH"}'),
('THAT_SAT_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "THAT_SAT", "brightness": "HAM"}'),
('PHA_QUAN_CHU_THAN_MIEU', '{"role": "CHU_THAN", "star": "PHA_QUAN", "brightness": "MIEU"}'),
('PHA_QUAN_CHU_THAN_VUONG', '{"role": "CHU_THAN", "star": "PHA_QUAN", "brightness": "VUONG"}'),
('PHA_QUAN_CHU_THAN_DAC', '{"role": "CHU_THAN", "star": "PHA_QUAN", "brightness": "DAC"}'),
('PHA_QUAN_CHU_THAN_BINH', '{"role": "CHU_THAN", "star": "PHA_QUAN", "brightness": "BINH"}'),
('PHA_QUAN_CHU_THAN_HAM', '{"role": "CHU_THAN", "star": "PHA_QUAN", "brightness": "HAM"}');
