-- ============================================================
-- FRAGMENTS BỔ SUNG CHO CÁC TRƯỜNG HỢP CÒN THIẾU
-- 1. THIEN_LUONG_MENH (5 brightness levels)
-- 2. THAI_DUONG_MENH (5 brightness levels)
-- 3. THAM_LANG_TAI_BACH (5 brightness levels)
-- Total: 15 fragments
-- ============================================================

INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES

-- ============================
-- THIEN_LUONG tại MENH
-- ============================
('THIEN_LUONG_MENH_MIEU', 'Thiên Lương miếu địa tại cung Mệnh thể hiện khả năng nhân từ và trí tuệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ và trí tuệ, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Lương miếu địa tại Mệnh thường có khả năng nhân từ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách từ bi, có khả năng giúp đỡ người khác và tạo được mối quan hệ tốt. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THIEN_LUONG_MENH_VUONG', 'Thiên Lương vượng địa tại cung Mệnh thể hiện khả năng nhân từ và trí tuệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ và trí tuệ, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Lương vượng địa tại Mệnh thường có khả năng nhân từ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách từ bi, có khả năng giúp đỡ người khác và tạo được mối quan hệ tốt. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THIEN_LUONG_MENH_DAC', 'Thiên Lương đắc địa tại cung Mệnh thể hiện khả năng nhân từ và trí tuệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ và trí tuệ, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Lương đắc địa tại Mệnh thường có khả năng nhân từ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách từ bi, có khả năng giúp đỡ người khác và tạo được mối quan hệ tốt. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THIEN_LUONG_MENH_BINH', 'Thiên Lương bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về nhân từ. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thiên Lương bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện nhân từ ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển nhân từ để nâng cao chất lượng.', 'neutral', 0),
('THIEN_LUONG_MENH_HAM', 'Thiên Lương hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy nhân từ và trí tuệ. Hãm địa là trạng thái bất lợi, khiến Thiên Lương không thể phát huy các mặt tích cực. Người có Thiên Lương hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện nhân từ, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THAI_DUONG tại MENH
-- ============================
('THAI_DUONG_MENH_MIEU', 'Thái Dương miếu địa tại cung Mệnh thể hiện khả năng nhiệt huyết và năng động trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhiệt huyết và năng động, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Dương miếu địa tại Mệnh thường có khả năng tích cực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhiệt huyết giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách năng động, có khả năng dẫn dắt và tạo được ảnh hưởng tích cực. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhiệt huyết.', 'positive', 0),
('THAI_DUONG_MENH_VUONG', 'Thái Dương vượng địa tại cung Mệnh thể hiện khả năng nhiệt huyết và năng động trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhiệt huyết và năng động, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Dương vượng địa tại Mệnh thường có khả năng tích cực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhiệt huyết giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách năng động, có khả năng dẫn dắt và tạo được ảnh hưởng tích cực. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhiệt huyết.', 'positive', 0),
('THAI_DUONG_MENH_DAC', 'Thái Dương đắc địa tại cung Mệnh thể hiện khả năng nhiệt huyết và năng động trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhiệt huyết và năng động, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Dương đắc địa tại Mệnh thường có khả năng tích cực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhiệt huyết giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách năng động, có khả năng dẫn dắt và tạo được ảnh hưởng tích cực. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhiệt huyết.', 'positive', 0),
('THAI_DUONG_MENH_BINH', 'Thái Dương bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về nhiệt huyết. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thái Dương bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện nhiệt huyết ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển nhiệt huyết để nâng cao chất lượng.', 'neutral', 0),
('THAI_DUONG_MENH_HAM', 'Thái Dương hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy nhiệt huyết và năng động. Hãm địa là trạng thái bất lợi, khiến Thái Dương không thể phát huy các mặt tích cực. Người có Thái Dương hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện nhiệt huyết, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THAM_LANG tại TAI_BACH
-- ============================
('THAM_LANG_TAI_BACH_MIEU', 'Tham Lang miếu địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính với tính thông minh và tài trí. Sao này chủ về thông minh và tài trí, khi ở miếu địa tại Tài Bạch tạo nên xu hướng có khả năng tích lũy và phát triển tài chính thông qua sự thông minh và tính toán. Miếu địa cho phép Tham Lang phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư tài chính. Tài chính có xu hướng phát triển với khả năng tính toán và đưa ra quyết định đầu tư thông minh. Tính chất tài trí giúp có khả năng nắm bắt các cơ hội đầu tư và quản lý tiền bạc một cách hiệu quả. Tuy nhiên, tính thông minh quá mức có thể dẫn đến xu hướng tham lam hoặc phân tán đầu tư vào quá nhiều nơi.', 'positive', 0),
('THAM_LANG_TAI_BACH_VUONG', 'Tham Lang vượng địa tại cung Tài Bạch mang lại khả năng phát triển tài chính với tính thông minh ở mức độ tốt. Vượng địa cho thấy Tham Lang ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng phát triển với khả năng tính toán và đưa ra quyết định đầu tư thông minh. Tính chất tài trí giúp có khả năng nắm bắt và tận dụng tốt các cơ hội đầu tư. Có xu hướng tạo được sự phát triển thông qua sự thông minh và tính toán. Tuy nhiên, cần cân bằng giữa sự thông minh và sự thận trọng để tránh xu hướng tham lam hoặc đầu tư rủi ro.', 'positive', 0),
('THAM_LANG_TAI_BACH_DAC', 'Tham Lang đắc địa tại cung Tài Bạch cho thấy khả năng quản lý tài chính ở mức độ ổn định với tính thông minh vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Tham Lang phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ổn định với khả năng tính toán và quản lý một cách cân nhắc. Tính thông minh ở mức độ vừa phải giúp có khả năng đưa ra quyết định đầu tư hợp lý mà không quá tham lam. Có khả năng duy trì và phát triển tài chính với sự tính toán hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng thông minh không đủ mạnh.', 'neutral', 0),
('THAM_LANG_TAI_BACH_BINH', 'Tham Lang bình địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính ở mức độ trung bình, không có sự nổi bật đặc biệt về thông minh. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Tham Lang không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính thông minh không được phát huy đầy đủ, có thể dẫn đến việc không tính toán đủ kỹ các quyết định đầu tư hoặc thiếu sự nhạy bén. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài chính. Có thể cần cải thiện khả năng tính toán và nhạy bén trong việc quản lý tiền bạc.', 'neutral', 0),
('THAM_LANG_TAI_BACH_HAM', 'Tham Lang hãm địa tại cung Tài Bạch cho thấy khó khăn trong việc tích lũy và quản lý tài chính. Hãm địa là trạng thái bất lợi, khiến Tham Lang không thể phát huy các mặt tích cực trong việc phát triển tài chính, thậm chí có thể gây ra những khó khăn về tính toán. Tài chính có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính thông minh bị suy giảm, có thể dẫn đến các quyết định đầu tư thiếu tính toán hoặc không nắm bắt được cơ hội. Khó khăn trong việc tích lũy và duy trì tài chính với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài chính.', 'negative', 0)
;
