-- ============================================================
-- FRAGMENTS CHO TRƯỜNG HỢP CUNG KHÔNG CÓ CHÍNH TINH
-- Chỉ có vòng Tràng Sinh (12 trạng thái)
-- Format: NO_CHINH_TINH_{TRANG_SINH_STATE}
-- ============================================================

INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES

-- TRUONG_SINH (Trường Sinh)
('NO_CHINH_TINH_TRUONG_SINH', 'Trong Tử Vi Đẩu Số, việc một cung không có Chính tinh là trường hợp hợp lệ và thường gặp, không phải lỗi an sao. Khi cung chỉ có Trường Sinh, điều này thể hiện trạng thái khởi đầu, mở đầu cho một chu kỳ phát triển trong lĩnh vực của cung đó. Trường Sinh là trạng thái đầu tiên trong vòng đời, mang ý nghĩa của sự sinh ra, bắt đầu, khởi nguồn. Trong bối cảnh cung không có Chính tinh, Trường Sinh đóng vai trò như một chỉ dấu về giai đoạn khởi đầu, sự hình thành ban đầu của các yếu tố liên quan đến cung. Tác động tổng quát lên lĩnh vực của cung thể hiện ở xu hướng khởi động, bắt đầu, nhưng cần thời gian để phát triển và định hình rõ ràng. Điểm mạnh là có tiềm năng phát triển, có khả năng khởi đầu tốt, nhưng điểm cần lưu ý là thiếu sự định hình cụ thể do không có Chính tinh làm chủ đạo, cần sự bổ trợ từ các yếu tố khác trong lá số để phát huy đầy đủ tiềm năng.', 'positive', 3),

-- MOC_DUC (Mộc Dục)
('NO_CHINH_TINH_MOC_DUC', 'Khi cung không có Chính tinh và chỉ hiện diện Mộc Dục, đây là một trạng thái đặc biệt trong vòng Tràng Sinh. Mộc Dục là trạng thái thứ hai, mang ý nghĩa của sự tắm rửa, gột rửa, thanh tẩy. Trong bối cảnh không có Chính tinh, Mộc Dục cho thấy lĩnh vực của cung đang trong giai đoạn được làm sạch, được chuẩn bị, được tinh lọc trước khi phát triển. Đây là giai đoạn chuyển tiếp từ khởi đầu sang giai đoạn phát triển tiếp theo, nơi các yếu tố không cần thiết được loại bỏ, các yếu tố cần thiết được giữ lại và chuẩn bị. Tác động tổng quát là tạo ra sự trong sáng, sự chuẩn bị kỹ lưỡng, nhưng cũng có thể mang tính chất bất ổn do đang trong quá trình chuyển đổi. Điểm tích cực là có cơ hội để làm mới, để bắt đầu lại với những yếu tố đã được thanh lọc, điểm cần lưu ý là thiếu sự ổn định và định hướng rõ ràng do không có Chính tinh dẫn dắt.', 'neutral', 3),

-- QUAN_DAI (Quán Đái)
('NO_CHINH_TINH_QUAN_DAI', 'Quán Đái là trạng thái thứ ba trong vòng Tràng Sinh, đại diện cho sự quan sát, học hỏi, tiếp thu. Khi cung không có Chính tinh và chỉ có Quán Đái, lĩnh vực của cung đang ở giai đoạn quan sát, học hỏi, tiếp thu kiến thức và kinh nghiệm, nhưng thiếu sự chủ đạo để định hướng và áp dụng những gì đã học. Quán Đái trong trường hợp không có Chính tinh cho thấy khả năng quan sát, học hỏi tốt, nhưng có thể thiếu sự chủ động và định hướng trong việc phát huy những gì đã học. Đây là giai đoạn tích lũy kiến thức và kinh nghiệm, chuẩn bị cho sự phát triển tiếp theo. Trong bối cảnh không có Chính tinh, Quán Đái có thể tạo ra sự học hỏi rộng rãi, nhưng cần có yếu tố khác để định hướng và áp dụng. Tác động tổng quát là tạo ra khả năng quan sát, học hỏi, tiếp thu, nhưng thiếu sự chủ động và định hướng rõ ràng. Điểm mạnh là có khả năng học hỏi và tích lũy kiến thức tốt, có thể quan sát và tiếp thu nhiều điều. Điểm cần lưu ý là thiếu sự chủ đạo để phát huy và áp dụng những gì đã học một cách hiệu quả, cần có yếu tố hỗ trợ để định hướng.', 'neutral', 3),

-- LAM_QUAN (Lâm Quan)
('NO_CHINH_TINH_LAM_QUAN', 'Lâm Quan là trạng thái thứ tư trong vòng Tràng Sinh, mang ý nghĩa của sự gặp gỡ, tiếp xúc, bước vào môi trường xã hội hoặc môi trường hoạt động. Khi cung chỉ có Lâm Quan mà không có Chính tinh, điều này cho thấy lĩnh vực của cung đang ở giai đoạn bắt đầu tương tác, bắt đầu có sự tiếp xúc và giao lưu, nhưng thiếu sự chủ đạo và định hướng cụ thể. Lâm Quan ở đây không có Chính tinh để "gặp gỡ" cùng, nên tác động của nó mang tính chất độc lập, tự thân vận động. Tác động tổng quát là tạo ra khả năng giao tiếp, tương tác, nhưng thiếu sự hỗ trợ mạnh mẽ từ Chính tinh để phát huy đầy đủ. Điểm mạnh là có khả năng độc lập, tự phát triển, có thể tạo ra những mối quan hệ và tương tác mới. Điểm cần lưu ý là thiếu sự chủ đạo rõ ràng, cần nhiều nỗ lực tự thân hơn so với khi có Chính tinh hỗ trợ.', 'neutral', 3),

-- DE_VUONG (Đế Vượng)
('NO_CHINH_TINH_DE_VUONG', 'Đế Vượng là trạng thái thứ năm và là trạng thái cực thịnh trong vòng Tràng Sinh. Khi cung không có Chính tinh nhưng có Đế Vượng, đây là một tình huống đặc biệt: trạng thái cực thịnh hiện diện mà không có Chính tinh làm chủ đạo. Đế Vượng trong trường hợp này thể hiện khả năng đạt đến đỉnh cao, nhưng do thiếu Chính tinh, sự cực thịnh này có thể không được định hướng rõ ràng hoặc thiếu sự ổn định lâu dài. Trong bối cảnh không có Chính tinh, Đế Vượng có thể tạo ra sự phát triển mạnh mẽ, nhưng cần được hỗ trợ từ các yếu tố khác trong lá số để duy trì và phát huy đầy đủ. Tác động tổng quát là tạo ra khả năng đạt đến đỉnh cao, có sự phát triển mạnh mẽ, nhưng có thể thiếu sự ổn định và định hướng lâu dài. Điểm mạnh là có tiềm năng đạt đến mức độ cao, có khả năng phát triển mạnh mẽ. Điểm cần lưu ý là sự cực thịnh có thể không được duy trì lâu dài do thiếu sự chủ đạo từ Chính tinh, cần có yếu tố hỗ trợ để ổn định.', 'positive', 3),

-- SUY (Suy)
('NO_CHINH_TINH_SUY', 'Suy là trạng thái thứ sáu trong vòng Tràng Sinh, bắt đầu giai đoạn suy giảm. Khi cung không có Chính tinh và chỉ có Suy, điều này thể hiện lĩnh vực của cung đang ở giai đoạn bắt đầu suy giảm, bắt đầu yếu đi, nhưng không có Chính tinh để hỗ trợ hoặc điều hòa sự suy giảm này. Suy trong trường hợp không có Chính tinh có thể tạo ra sự suy giảm nhanh hơn, hoặc sự suy giảm không được kiểm soát tốt. Tuy nhiên, cần hiểu rằng đây là một phần tự nhiên của chu kỳ, không phải là điều xấu tuyệt đối. Trong bối cảnh không có Chính tinh, Suy cho thấy lĩnh vực của cung cần được hỗ trợ từ các yếu tố khác, cần có sự điều chỉnh và cân bằng. Tác động tổng quát là tạo ra xu hướng suy giảm, yếu đi, nhưng không có sự hỗ trợ để làm chậm hoặc điều hòa quá trình này. Điểm cần lưu ý là sự suy giảm có thể diễn ra nhanh hơn, cần nhiều nỗ lực để duy trì và ổn định. Điểm tích cực là đây là giai đoạn chuẩn bị cho sự phục hồi và tái sinh tiếp theo trong chu kỳ.', 'negative', 3),

-- BENH (Bệnh)
('NO_CHINH_TINH_BENH', 'Bệnh là trạng thái thứ bảy trong vòng Tràng Sinh, thể hiện giai đoạn ốm yếu, suy nhược. Khi cung không có Chính tinh và chỉ có Bệnh, lĩnh vực của cung đang ở trạng thái yếu kém, thiếu sức sống, và không có Chính tinh để hỗ trợ hoặc chữa trị. Bệnh trong trường hợp này cho thấy lĩnh vực đang gặp khó khăn, đang trong tình trạng không khỏe mạnh, cần được chăm sóc và hỗ trợ. Trong bối cảnh không có Chính tinh, Bệnh có thể kéo dài hơn hoặc khó phục hồi hơn do thiếu sự chủ đạo và hỗ trợ mạnh mẽ. Tác động tổng quát là tạo ra sự yếu kém, thiếu sức sống, khó khăn trong phát triển, và thiếu khả năng tự phục hồi do không có Chính tinh. Điểm cần lưu ý là lĩnh vực của cung đang ở trạng thái khó khăn, cần nhiều sự hỗ trợ từ các yếu tố khác trong lá số. Điểm tích cực là đây vẫn là một giai đoạn trong chu kỳ, và sau Bệnh sẽ đến các giai đoạn khác, tạo cơ hội cho sự phục hồi và tái sinh.', 'negative', 3),

-- TU (Tử)
('NO_CHINH_TINH_TU', 'Tử là trạng thái thứ tám trong vòng Tràng Sinh, đại diện cho sự kết thúc, sự chết, sự chấm dứt. Khi cung không có Chính tinh và chỉ có Tử, lĩnh vực của cung đang ở giai đoạn kết thúc, chấm dứt, nhưng không có Chính tinh để điều hòa hoặc chuyển đổi quá trình này. Tử trong trường hợp không có Chính tinh thể hiện sự kết thúc hoàn toàn, sự chấm dứt mạnh mẽ, và có thể khó khăn trong việc chuyển đổi sang giai đoạn mới. Tuy nhiên, cần hiểu rằng trong Tử Vi, Tử không chỉ là sự kết thúc mà còn là sự chuẩn bị cho sự tái sinh, sự khởi đầu mới. Trong bối cảnh không có Chính tinh, quá trình chuyển đổi này có thể khó khăn hơn, cần nhiều thời gian hơn. Tác động tổng quát là tạo ra sự kết thúc, chấm dứt, và khó khăn trong việc duy trì hoặc phát triển tiếp. Điểm cần lưu ý là lĩnh vực của cung đang ở giai đoạn kết thúc, cần được chuẩn bị cho sự tái sinh. Điểm tích cực là sau Tử sẽ đến các giai đoạn phục hồi và tái sinh trong chu kỳ tiếp theo.', 'negative', 3),

-- MO (Mộ)
('NO_CHINH_TINH_MO', 'Mộ là trạng thái thứ chín trong vòng Tràng Sinh, đại diện cho sự chôn cất, nghỉ ngơi, ẩn giấu. Khi cung không có Chính tinh và chỉ có Mộ, lĩnh vực của cung đang ở giai đoạn ẩn giấu, nghỉ ngơi, không hoạt động mạnh mẽ. Mộ trong trường hợp không có Chính tinh cho thấy các yếu tố liên quan đến cung đang được cất giấu, đang ở trạng thái tiềm ẩn, chưa bộc lộ rõ ràng. Đây là giai đoạn tích lũy, chuẩn bị năng lượng cho các giai đoạn tiếp theo. Trong bối cảnh không có Chính tinh, Mộ có thể tạo ra sự ẩn giấu sâu hơn, khó phát hiện hơn, nhưng cũng có thể là nơi tích lũy tiềm năng. Tác động tổng quát là tạo ra sự ẩn giấu, không hoạt động rõ ràng, nhưng có tiềm năng được tích lũy. Điểm cần lưu ý là lĩnh vực của cung đang ở trạng thái tiềm ẩn, khó nhận biết hoặc phát huy ngay lập tức. Điểm tích cực là đây là giai đoạn tích lũy, chuẩn bị, và tiềm năng có thể được phát huy trong các giai đoạn tiếp theo khi có điều kiện phù hợp.', 'neutral', 3),

-- TUYET (Tuyệt)
('NO_CHINH_TINH_TUYET', 'Tuyệt là trạng thái thứ mười trong vòng Tràng Sinh, đại diện cho sự tuyệt diệt, sự không còn, sự triệt tiêu. Khi cung không có Chính tinh và chỉ có Tuyệt, lĩnh vực của cung đang ở giai đoạn cực kỳ khó khăn, gần như không còn gì, hoàn toàn thiếu vắng. Tuyệt trong trường hợp không có Chính tinh thể hiện sự thiếu vắng hoàn toàn, sự không còn, và khó khăn cực độ trong việc phát triển hoặc duy trì. Đây là giai đoạn thấp nhất trong chu kỳ, nơi mọi thứ dường như đã mất hết. Tuy nhiên, trong Tử Vi, sau Tuyệt sẽ đến Thai, tạo thành chu kỳ tái sinh. Trong bối cảnh không có Chính tinh, giai đoạn Tuyệt có thể kéo dài hơn hoặc khó khăn hơn, nhưng vẫn là một phần của chu kỳ. Tác động tổng quát là tạo ra sự thiếu vắng hoàn toàn, sự không còn, khó khăn cực độ, và không có khả năng phát triển. Điểm cần lưu ý là lĩnh vực của cung đang ở trạng thái cực kỳ khó khăn, cần rất nhiều sự hỗ trợ và thời gian. Điểm tích cực là sau Tuyệt sẽ đến Thai, bắt đầu chu kỳ mới với khả năng tái sinh và phục hồi.', 'negative', 3),

-- THAI (Thai)
('NO_CHINH_TINH_THAI', 'Thai là trạng thái thứ mười một trong vòng Tràng Sinh, đại diện cho sự thai nghén, sự chuẩn bị lại, sự hình thành mới. Khi cung không có Chính tinh và chỉ có Thai, lĩnh vực của cung đang ở giai đoạn bắt đầu hình thành lại, chuẩn bị cho sự phát triển mới sau giai đoạn Tuyệt. Thai trong trường hợp không có Chính tinh cho thấy sự khởi đầu mới, sự hình thành mới, nhưng còn ở giai đoạn sơ khai, chưa rõ ràng. Đây là giai đoạn tích cực sau những khó khăn của các giai đoạn trước, bắt đầu chu kỳ mới. Trong bối cảnh không có Chính tinh, Thai có thể phát triển chậm hơn hoặc cần nhiều thời gian hơn để định hình, nhưng vẫn mang tính chất tích cực của sự khởi đầu mới. Tác động tổng quát là tạo ra sự hình thành mới, sự chuẩn bị cho phát triển, nhưng còn ở giai đoạn sơ khai. Điểm tích cực là đây là sự khởi đầu mới sau những khó khăn, có tiềm năng phát triển. Điểm cần lưu ý là sự hình thành còn ở giai đoạn sơ khai, cần thời gian và sự hỗ trợ để phát triển đầy đủ.', 'positive', 3),

-- DUONG (Dưỡng)
('NO_CHINH_TINH_DUONG', 'Dưỡng là trạng thái thứ mười hai trong vòng Tràng Sinh, đại diện cho sự nuôi dưỡng, sự phục hồi, sự chăm sóc. Khi cung không có Chính tinh và chỉ có Dưỡng, lĩnh vực của cung đang ở giai đoạn được nuôi dưỡng, được phục hồi, được chăm sóc sau các giai đoạn khó khăn. Dưỡng trong trường hợp không có Chính tinh cho thấy sự phục hồi đang diễn ra, sự nuôi dưỡng đang được thực hiện, nhưng thiếu sự chủ đạo để phát huy đầy đủ. Đây là giai đoạn tích cực, nơi các yếu tố đang được bồi bổ và phục hồi. Trong bối cảnh không có Chính tinh, Dưỡng có thể cần nhiều thời gian hơn hoặc cần sự hỗ trợ từ các yếu tố khác để phát huy đầy đủ tác dụng. Tác động tổng quát là tạo ra sự phục hồi, sự nuôi dưỡng, sự chăm sóc, nhưng có thể chậm hoặc cần nhiều thời gian. Điểm tích cực là đây là giai đoạn phục hồi, có khả năng phát triển tốt sau khi được nuôi dưỡng đầy đủ. Điểm cần lưu ý là quá trình phục hồi có thể chậm do thiếu sự chủ đạo từ Chính tinh, cần kiên nhẫn và sự hỗ trợ.', 'positive', 3);
