-- ============================================================
-- FRAGMENTS BỔ SUNG CHO CÁC TRƯỜNG HỢP CÒN THIẾU (PHẦN CUỐI)
-- 1. THIEN_CO_MENH (5 brightness levels)
-- 2. THIEN_DONG_MENH (5 brightness levels)
-- 3. THIEN_TUONG_MENH (5 brightness levels)
-- 4. THAI_AM_MENH (5 brightness levels)
-- 5. VU_KHUC_MENH (5 brightness levels)
-- 6. CU_MON_MENH (5 brightness levels)
-- 7. LIEM_TRINH_MENH (5 brightness levels)
-- 8. THIEN_PHU_TAT_ACH (5 brightness levels)
-- 9. THAT_SAT_TAI_BACH (5 brightness levels)
-- 10. PHA_QUAN_TAI_BACH (5 brightness levels)
-- Total: 50 fragments
-- ============================================================

INSERT INTO interpretation_fragments (fragment_code, content, tone, priority) VALUES

-- ============================
-- THIEN_CO tại MENH
-- ============================
('THIEN_CO_MENH_MIEU', 'Thiên Cơ miếu địa tại cung Mệnh thể hiện khả năng trí tuệ và linh hoạt trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về trí tuệ, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Cơ miếu địa tại Mệnh thường có khả năng thông minh, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách trí tuệ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách linh hoạt, có khả năng thích ứng nhanh và xử lý các tình huống một cách thông minh. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua trí tuệ.', 'positive', 0),
('THIEN_CO_MENH_VUONG', 'Thiên Cơ vượng địa tại cung Mệnh thể hiện khả năng trí tuệ và linh hoạt trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về trí tuệ, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Cơ vượng địa tại Mệnh thường có khả năng thông minh, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách trí tuệ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách linh hoạt, có khả năng thích ứng nhanh và xử lý các tình huống một cách thông minh. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua trí tuệ.', 'positive', 0),
('THIEN_CO_MENH_DAC', 'Thiên Cơ đắc địa tại cung Mệnh thể hiện khả năng trí tuệ và linh hoạt trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về trí tuệ, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Cơ đắc địa tại Mệnh thường có khả năng thông minh, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách trí tuệ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách linh hoạt, có khả năng thích ứng nhanh và xử lý các tình huống một cách thông minh. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua trí tuệ.', 'positive', 0),
('THIEN_CO_MENH_BINH', 'Thiên Cơ bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về trí tuệ. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thiên Cơ bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện trí tuệ ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển trí tuệ để nâng cao chất lượng.', 'neutral', 0),
('THIEN_CO_MENH_HAM', 'Thiên Cơ hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy trí tuệ và linh hoạt. Hãm địa là trạng thái bất lợi, khiến Thiên Cơ không thể phát huy các mặt tích cực. Người có Thiên Cơ hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện trí tuệ, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THIEN_DONG tại MENH
-- ============================
('THIEN_DONG_MENH_MIEU', 'Thiên Đồng miếu địa tại cung Mệnh thể hiện khả năng hài hòa và lạc quan trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về hài hòa, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Đồng miếu địa tại Mệnh thường có khả năng vui vẻ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách hài hòa giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách lạc quan, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách hòa nhã. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua hài hòa.', 'positive', 0),
('THIEN_DONG_MENH_VUONG', 'Thiên Đồng vượng địa tại cung Mệnh thể hiện khả năng hài hòa và lạc quan trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về hài hòa, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Đồng vượng địa tại Mệnh thường có khả năng vui vẻ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách hài hòa giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách lạc quan, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách hòa nhã. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua hài hòa.', 'positive', 0),
('THIEN_DONG_MENH_DAC', 'Thiên Đồng đắc địa tại cung Mệnh thể hiện khả năng hài hòa và lạc quan trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về hài hòa, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Đồng đắc địa tại Mệnh thường có khả năng vui vẻ, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách hài hòa giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách lạc quan, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách hòa nhã. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua hài hòa.', 'positive', 0),
('THIEN_DONG_MENH_BINH', 'Thiên Đồng bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về hài hòa. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thiên Đồng bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện hài hòa ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển hài hòa để nâng cao chất lượng.', 'neutral', 0),
('THIEN_DONG_MENH_HAM', 'Thiên Đồng hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy hài hòa và lạc quan. Hãm địa là trạng thái bất lợi, khiến Thiên Đồng không thể phát huy các mặt tích cực. Người có Thiên Đồng hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện hài hòa, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THIEN_TUONG tại MENH
-- ============================
('THIEN_TUONG_MENH_MIEU', 'Thiên Tướng miếu địa tại cung Mệnh thể hiện khả năng ổn định và bảo vệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về ổn định, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Tướng miếu địa tại Mệnh thường có khả năng trung thành, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách ổn định giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách bảo vệ, có khả năng tạo được sự ổn định và tin cậy trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua ổn định.', 'positive', 0),
('THIEN_TUONG_MENH_VUONG', 'Thiên Tướng vượng địa tại cung Mệnh thể hiện khả năng ổn định và bảo vệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về ổn định, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Tướng vượng địa tại Mệnh thường có khả năng trung thành, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách ổn định giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách bảo vệ, có khả năng tạo được sự ổn định và tin cậy trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua ổn định.', 'positive', 0),
('THIEN_TUONG_MENH_DAC', 'Thiên Tướng đắc địa tại cung Mệnh thể hiện khả năng ổn định và bảo vệ trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về ổn định, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thiên Tướng đắc địa tại Mệnh thường có khả năng trung thành, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách ổn định giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách bảo vệ, có khả năng tạo được sự ổn định và tin cậy trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua ổn định.', 'positive', 0),
('THIEN_TUONG_MENH_BINH', 'Thiên Tướng bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về ổn định. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thiên Tướng bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện ổn định ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển ổn định để nâng cao chất lượng.', 'neutral', 0),
('THIEN_TUONG_MENH_HAM', 'Thiên Tướng hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy ổn định và bảo vệ. Hãm địa là trạng thái bất lợi, khiến Thiên Tướng không thể phát huy các mặt tích cực. Người có Thiên Tướng hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện ổn định, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THAI_AM tại MENH
-- ============================
('THAI_AM_MENH_MIEU', 'Thái Âm miếu địa tại cung Mệnh thể hiện khả năng nhân từ và hòa nhã trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Âm miếu địa tại Mệnh thường có khả năng dịu dàng, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách nhẹ nhàng. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THAI_AM_MENH_VUONG', 'Thái Âm vượng địa tại cung Mệnh thể hiện khả năng nhân từ và hòa nhã trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Âm vượng địa tại Mệnh thường có khả năng dịu dàng, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách nhẹ nhàng. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THAI_AM_MENH_DAC', 'Thái Âm đắc địa tại cung Mệnh thể hiện khả năng nhân từ và hòa nhã trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về nhân từ, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Thái Âm đắc địa tại Mệnh thường có khả năng dịu dàng, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách nhân từ giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách hòa nhã, có khả năng tạo được mối quan hệ tốt và giải quyết các vấn đề một cách nhẹ nhàng. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua nhân từ.', 'positive', 0),
('THAI_AM_MENH_BINH', 'Thái Âm bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về nhân từ. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Thái Âm bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện nhân từ ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển nhân từ để nâng cao chất lượng.', 'neutral', 0),
('THAI_AM_MENH_HAM', 'Thái Âm hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy nhân từ và hòa nhã. Hãm địa là trạng thái bất lợi, khiến Thái Âm không thể phát huy các mặt tích cực. Người có Thái Âm hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện nhân từ, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- VU_KHUC tại MENH
-- ============================
('VU_KHUC_MENH_MIEU', 'Vũ Khúc miếu địa tại cung Mệnh thể hiện khả năng tài chính và tổ chức trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về tài chính, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Vũ Khúc miếu địa tại Mệnh thường có khả năng tổ chức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách tài chính giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách kinh doanh, có khả năng quản lý tài chính và tạo dựng sự ổn định về mặt vật chất. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua tài chính.', 'positive', 0),
('VU_KHUC_MENH_VUONG', 'Vũ Khúc vượng địa tại cung Mệnh thể hiện khả năng tài chính và tổ chức trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về tài chính, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Vũ Khúc vượng địa tại Mệnh thường có khả năng tổ chức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách tài chính giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách kinh doanh, có khả năng quản lý tài chính và tạo dựng sự ổn định về mặt vật chất. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua tài chính.', 'positive', 0),
('VU_KHUC_MENH_DAC', 'Vũ Khúc đắc địa tại cung Mệnh thể hiện khả năng tài chính và tổ chức trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về tài chính, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Vũ Khúc đắc địa tại Mệnh thường có khả năng tổ chức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách tài chính giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách kinh doanh, có khả năng quản lý tài chính và tạo dựng sự ổn định về mặt vật chất. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua tài chính.', 'positive', 0),
('VU_KHUC_MENH_BINH', 'Vũ Khúc bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về tài chính. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Vũ Khúc bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện tài chính ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển tài chính để nâng cao chất lượng.', 'neutral', 0),
('VU_KHUC_MENH_HAM', 'Vũ Khúc hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy tài chính và tổ chức. Hãm địa là trạng thái bất lợi, khiến Vũ Khúc không thể phát huy các mặt tích cực. Người có Vũ Khúc hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện tài chính, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- CU_MON tại MENH
-- ============================
('CU_MON_MENH_MIEU', 'Cự Môn miếu địa tại cung Mệnh thể hiện khả năng giao tiếp và học hỏi trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về giao tiếp, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Cự Môn miếu địa tại Mệnh thường có khả năng kiến thức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách giao tiếp giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách học hỏi, có khả năng tích lũy kiến thức và tạo được mối quan hệ tốt thông qua giao tiếp. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua giao tiếp.', 'positive', 0),
('CU_MON_MENH_VUONG', 'Cự Môn vượng địa tại cung Mệnh thể hiện khả năng giao tiếp và học hỏi trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về giao tiếp, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Cự Môn vượng địa tại Mệnh thường có khả năng kiến thức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách giao tiếp giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách học hỏi, có khả năng tích lũy kiến thức và tạo được mối quan hệ tốt thông qua giao tiếp. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua giao tiếp.', 'positive', 0),
('CU_MON_MENH_DAC', 'Cự Môn đắc địa tại cung Mệnh thể hiện khả năng giao tiếp và học hỏi trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về giao tiếp, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Cự Môn đắc địa tại Mệnh thường có khả năng kiến thức, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách giao tiếp giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách học hỏi, có khả năng tích lũy kiến thức và tạo được mối quan hệ tốt thông qua giao tiếp. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua giao tiếp.', 'positive', 0),
('CU_MON_MENH_BINH', 'Cự Môn bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về giao tiếp. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Cự Môn bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện giao tiếp ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển giao tiếp để nâng cao chất lượng.', 'neutral', 0),
('CU_MON_MENH_HAM', 'Cự Môn hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy giao tiếp và học hỏi. Hãm địa là trạng thái bất lợi, khiến Cự Môn không thể phát huy các mặt tích cực. Người có Cự Môn hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện giao tiếp, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- LIEM_TRINH tại MENH
-- ============================
('LIEM_TRINH_MENH_MIEU', 'Liêm Trinh miếu địa tại cung Mệnh thể hiện khả năng thanh cao và trung thực trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về thanh cao, khi ở miếu địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Liêm Trinh miếu địa tại Mệnh thường có khả năng chính trực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách thanh cao giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách trung thực, có khả năng tạo được sự tin cậy và uy tín trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua thanh cao.', 'positive', 0),
('LIEM_TRINH_MENH_VUONG', 'Liêm Trinh vượng địa tại cung Mệnh thể hiện khả năng thanh cao và trung thực trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về thanh cao, khi ở vượng địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Liêm Trinh vượng địa tại Mệnh thường có khả năng chính trực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách thanh cao giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách trung thực, có khả năng tạo được sự tin cậy và uy tín trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua thanh cao.', 'positive', 0),
('LIEM_TRINH_MENH_DAC', 'Liêm Trinh đắc địa tại cung Mệnh thể hiện khả năng thanh cao và trung thực trong việc định hình bản chất và tính cách cơ bản. Sao này chủ về thanh cao, khi ở đắc địa tại Mệnh tạo nên khả năng phát huy đầy đủ tính chất tích cực. Người có Liêm Trinh đắc địa tại Mệnh thường có khả năng chính trực, dễ dàng đạt được sự tôn trọng và phát triển. Tính cách thanh cao giúp họ vượt qua các thách thức và tạo dựng được vị thế. Trong thực tế, họ thường thể hiện tính cách trung thực, có khả năng tạo được sự tin cậy và uy tín trong các mối quan hệ. Mệnh của họ có xu hướng phát triển tích cực, với nhiều cơ hội để thể hiện năng lực và đạt được mục tiêu thông qua thanh cao.', 'positive', 0),
('LIEM_TRINH_MENH_BINH', 'Liêm Trinh bình địa tại cung Mệnh thể hiện khả năng bản chất và tính cách ở mức độ trung bình, không có sự nổi bật đặc biệt về thanh cao. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt. Người có Liêm Trinh bình địa tại Mệnh thường có khả năng ổn định, hoàn thành các nhiệm vụ cơ bản nhưng ít có thành tựu nổi bật. Trong thực tế, họ thể hiện tính cách trung hòa, có thể thể hiện thanh cao ở mức độ cơ bản nhưng khó đạt được thành tựu lớn. Mệnh của họ có xu hướng phát triển chậm, cần nhiều thời gian và nỗ lực để cải thiện. Họ cần chủ động phát triển thanh cao để nâng cao chất lượng.', 'neutral', 0),
('LIEM_TRINH_MENH_HAM', 'Liêm Trinh hãm địa tại cung Mệnh cho thấy khó khăn trong việc phát huy thanh cao và trung thực. Hãm địa là trạng thái bất lợi, khiến Liêm Trinh không thể phát huy các mặt tích cực. Người có Liêm Trinh hãm địa tại Mệnh thường gặp khó khăn trong việc thể hiện thanh cao, dễ bị rối loạn khi đối mặt với tình huống phức tạp. Họ có xu hướng thiếu tự tin, khó khăn trong việc đạt được mục tiêu và thường cần sự hỗ trợ. Trong thực tế, họ có thể gặp trở ngại, dễ bỏ lỡ cơ hội. Mệnh của họ có xu hướng phát triển chậm, cần nhiều nỗ lực để vượt qua khó khăn.', 'negative', 0),

-- ============================
-- THIEN_PHU tại TAT_ACH
-- ============================
('THIEN_PHU_TAT_ACH_MIEU', 'Thiên Phủ miếu địa tại cung Tật Ách thể hiện khả năng phú có và tích trữ trong lĩnh vực sức khỏe, thể trạng, bệnh tật. Sao này chủ về phú có, khi ở miếu địa tại Tật Ách tạo nên xu hướng có thể trạng ổn định với khả năng tích lũy sức khỏe và duy trì thể trạng tốt. Miếu địa là trạng thái mạnh nhất, cho phép Thiên Phủ phát huy đầy đủ tính chất tích cực trong việc bảo vệ và duy trì sức khỏe. Thể trạng có xu hướng ổn định với khả năng phục hồi và tích lũy sức khỏe một cách hiệu quả. Tính chất phú có giúp có khả năng chăm sóc sức khỏe một cách đầy đủ và toàn diện. Tuy nhiên, tính chất tích trữ quá mức có thể dẫn đến xu hướng không chú ý đầy đủ đến các dấu hiệu cảnh báo hoặc tích lũy quá mức mà không cân nhắc.', 'positive', 0),
('THIEN_PHU_TAT_ACH_VUONG', 'Thiên Phủ vượng địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ tốt với tính phú có mạnh mẽ. Vượng địa cho thấy Thiên Phủ ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc duy trì thể trạng và tích lũy sức khỏe. Thể trạng có xu hướng ổn định với khả năng đối phó hiệu quả với các vấn đề sức khỏe. Tính chất phú có giúp có khả năng chăm sóc và bảo vệ sức khỏe một cách toàn diện. Có xu hướng tạo được sự ổn định về thể trạng với khả năng tích lũy và duy trì sức khỏe tốt. Tuy nhiên, cần cân bằng giữa sự tích trữ và sự chú ý đến các dấu hiệu cảnh báo để tránh xu hướng bỏ qua các vấn đề sức khỏe.', 'positive', 0),
('THIEN_PHU_TAT_ACH_DAC', 'Thiên Phủ đắc địa tại cung Tật Ách cho thấy khả năng quản lý sức khỏe ở mức độ ổn định với tính phú có vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thiên Phủ phát huy các mặt tích cực trong việc duy trì thể trạng. Thể trạng có xu hướng ổn định với khả năng tích lũy và duy trì sức khỏe một cách cân nhắc. Tính phú có ở mức độ vừa phải giúp có khả năng chăm sóc sức khỏe mà không quá tích trữ. Có khả năng duy trì thể trạng ổn định với sự chú ý hợp lý đến việc chăm sóc sức khỏe. Tuy nhiên, cần chú ý để không bỏ qua các dấu hiệu cảnh báo do xu hướng tích trữ.', 'neutral', 0),
('THIEN_PHU_TAT_ACH_BINH', 'Thiên Phủ bình địa tại cung Tật Ách thể hiện khả năng quản lý sức khỏe ở mức độ trung bình, không có sự nổi bật đặc biệt về phú có. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thiên Phủ không thể phát huy đầy đủ tính chất trong việc duy trì thể trạng. Thể trạng có xu hướng ở mức độ trung bình với khả năng chăm sóc sức khỏe ở mức độ cơ bản. Tính phú có không được phát huy đầy đủ, có thể dẫn đến việc không chăm sóc đầy đủ hoặc thiếu sự tích lũy sức khỏe. Cần nhiều nỗ lực và thời gian để cải thiện tình trạng sức khỏe. Có thể cần cải thiện khả năng chăm sóc và tích lũy sức khỏe.', 'neutral', 0),
('THIEN_PHU_TAT_ACH_HAM', 'Thiên Phủ hãm địa tại cung Tật Ách cho thấy khó khăn trong việc quản lý và duy trì sức khỏe. Hãm địa là trạng thái bất lợi, khiến Thiên Phủ không thể phát huy các mặt tích cực trong việc duy trì thể trạng, thậm chí có thể gây ra những khó khăn về sự tích lũy. Thể trạng có xu hướng không ổn định với khả năng chăm sóc và bảo vệ sức khỏe bị hạn chế. Tính phú có bị suy giảm, có thể dẫn đến việc không chăm sóc đầy đủ hoặc không tích lũy được sức khỏe. Khó khăn trong việc duy trì thể trạng ổn định với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và chú ý đặc biệt để cải thiện và duy trì tình trạng sức khỏe.', 'negative', 0),

-- ============================
-- THAT_SAT tại TAI_BACH
-- ============================
('THAT_SAT_TAI_BACH_MIEU', 'Thất Sát miếu địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính với tính quyết đoán và mạnh mẽ. Sao này chủ về quyền uy và quyết đoán, khi ở miếu địa tại Tài Bạch tạo nên xu hướng có khả năng tích lũy và phát triển tài chính một cách quyết liệt và hiệu quả. Miếu địa cho phép Thất Sát phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư tài chính. Tài chính có xu hướng phát triển với khả năng đưa ra các quyết định đầu tư quyết đoán và mạnh mẽ. Tính chất quyết đoán giúp có khả năng nắm bắt các cơ hội tài chính và quản lý tiền bạc một cách hiệu quả. Tuy nhiên, tính quyết đoán quá mức có thể dẫn đến các quyết định đầu tư thiếu cân nhắc hoặc không đủ thận trọng.', 'positive', 0),
('THAT_SAT_TAI_BACH_VUONG', 'Thất Sát vượng địa tại cung Tài Bạch mang lại khả năng phát triển tài chính với tính quyết đoán ở mức độ tốt. Vượng địa cho thấy Thất Sát ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng phát triển với khả năng đưa ra các quyết định đầu tư quyết đoán và hiệu quả. Tính chất quyết đoán giúp có khả năng nắm bắt và tận dụng tốt các cơ hội tài chính. Có xu hướng tạo được sự phát triển thông qua sự quyết đoán và mạnh mẽ. Tuy nhiên, cần cân bằng giữa sự quyết đoán và sự thận trọng để tránh các quyết định đầu tư rủi ro.', 'positive', 0),
('THAT_SAT_TAI_BACH_DAC', 'Thất Sát đắc địa tại cung Tài Bạch cho thấy khả năng quản lý tài chính ở mức độ ổn định với tính quyết đoán vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Thất Sát phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ổn định với khả năng đưa ra các quyết định đầu tư một cách cân nhắc. Tính quyết đoán ở mức độ vừa phải giúp có khả năng đưa ra quyết định hợp lý mà không quá mạnh mẽ. Có khả năng duy trì và phát triển tài chính với sự quản lý hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng quyết đoán không đủ mạnh.', 'neutral', 0),
('THAT_SAT_TAI_BACH_BINH', 'Thất Sát bình địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính ở mức độ trung bình, không có sự nổi bật đặc biệt về quyết đoán. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Thất Sát không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính quyết đoán không được phát huy đầy đủ, có thể dẫn đến việc không đưa ra quyết định kịp thời hoặc thiếu sự quyết liệt. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài chính. Có thể cần cải thiện khả năng quyết đoán trong việc quản lý tiền bạc.', 'neutral', 0),
('THAT_SAT_TAI_BACH_HAM', 'Thất Sát hãm địa tại cung Tài Bạch cho thấy khó khăn trong việc tích lũy và quản lý tài chính. Hãm địa là trạng thái bất lợi, khiến Thất Sát không thể phát huy các mặt tích cực trong việc phát triển tài chính, thậm chí có thể gây ra những khó khăn về quyết đoán. Tài chính có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính quyết đoán bị suy giảm, có thể dẫn đến các quyết định đầu tư sai lầm hoặc không đưa ra quyết định kịp thời. Khó khăn trong việc tích lũy và duy trì tài chính với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài chính.', 'negative', 0),

-- ============================
-- PHA_QUAN tại TAI_BACH
-- ============================
('PHA_QUAN_TAI_BACH_MIEU', 'Phá Quân miếu địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính với tính đổi mới và cách mạng. Sao này chủ về thay đổi và cách mạng, khi ở miếu địa tại Tài Bạch tạo nên xu hướng có khả năng tích lũy và phát triển tài chính thông qua sự đổi mới và sáng tạo. Miếu địa cho phép Phá Quân phát huy đầy đủ tính chất tích cực trong việc quản lý và đầu tư tài chính. Tài chính có xu hướng phát triển với khả năng tìm ra các cách thức mới trong quản lý và đầu tư. Tính chất đổi mới giúp có khả năng nắm bắt các cơ hội tài chính mới và quản lý tiền bạc một cách sáng tạo. Tuy nhiên, tính thay đổi quá mức có thể dẫn đến xu hướng không ổn định trong quản lý tài chính hoặc đầu tư quá rủi ro.', 'positive', 0),
('PHA_QUAN_TAI_BACH_VUONG', 'Phá Quân vượng địa tại cung Tài Bạch mang lại khả năng phát triển tài chính với tính đổi mới ở mức độ tốt. Vượng địa cho thấy Phá Quân ở trạng thái mạnh, có thể phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng phát triển với khả năng đưa ra các cách thức mới trong quản lý và đầu tư. Tính chất đổi mới giúp có khả năng nắm bắt và tận dụng tốt các cơ hội tài chính mới. Có xu hướng tạo được sự phát triển thông qua sự đổi mới và sáng tạo. Tuy nhiên, cần cân bằng giữa sự đổi mới và sự ổn định để tránh xu hướng đầu tư quá rủi ro.', 'positive', 0),
('PHA_QUAN_TAI_BACH_DAC', 'Phá Quân đắc địa tại cung Tài Bạch cho thấy khả năng quản lý tài chính ở mức độ ổn định với tính đổi mới vừa phải. Đắc địa là trạng thái thuận lợi, cho phép Phá Quân phát huy các mặt tích cực trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ổn định với khả năng tìm ra các cách thức mới một cách cân nhắc. Tính đổi mới ở mức độ vừa phải giúp có khả năng đưa ra quyết định đầu tư hợp lý mà không quá thay đổi. Có khả năng duy trì và phát triển tài chính với sự đổi mới hợp lý. Tuy nhiên, cần chú ý để không bỏ qua các cơ hội do xu hướng đổi mới không đủ mạnh.', 'neutral', 0),
('PHA_QUAN_TAI_BACH_BINH', 'Phá Quân bình địa tại cung Tài Bạch thể hiện khả năng quản lý tài chính ở mức độ trung bình, không có sự nổi bật đặc biệt về đổi mới. Bình địa là trạng thái không có lợi cũng không có hại rõ rệt, khiến Phá Quân không thể phát huy đầy đủ tính chất trong việc tích lũy và quản lý tiền bạc. Tài chính có xu hướng ở mức độ trung bình với khả năng quản lý ở mức độ cơ bản. Tính đổi mới không được phát huy đầy đủ, có thể dẫn đến việc không tìm ra cách thức mới hiệu quả hoặc thiếu sự sáng tạo. Cần nhiều nỗ lực và thời gian để tích lũy và phát triển tài chính. Có thể cần cải thiện khả năng đổi mới trong việc quản lý tiền bạc.', 'neutral', 0),
('PHA_QUAN_TAI_BACH_HAM', 'Phá Quân hãm địa tại cung Tài Bạch cho thấy khó khăn trong việc tích lũy và quản lý tài chính. Hãm địa là trạng thái bất lợi, khiến Phá Quân không thể phát huy các mặt tích cực trong việc phát triển tài chính, thậm chí có thể gây ra những khó khăn về sự ổn định. Tài chính có xu hướng không ổn định với khả năng quản lý bị hạn chế. Tính đổi mới bị suy giảm, có thể dẫn đến các quyết định đầu tư thiếu tính toán hoặc thay đổi cách quản lý một cách thiếu cân nhắc. Khó khăn trong việc tích lũy và duy trì tài chính với xu hướng dễ gặp trở ngại. Cần nhiều nỗ lực và thận trọng đặc biệt để cải thiện tình trạng tài chính.', 'negative', 0)
;
