package com.duong.lichvanien.user.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Request DTO for client-side fingerprint data.
 * This data is combined with server-side data to create a unique fingerprint.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class FingerprintRequest {

    /**
     * Canvas fingerprint hash.
     * Generated by drawing on a canvas element and hashing the result.
     */
    private String canvasHash;

    /**
     * WebGL fingerprint hash.
     * Generated from WebGL renderer info and parameters.
     */
    private String webglHash;

    /**
     * Screen size in format "widthxheight" (e.g., "1920x1080").
     */
    private String screenSize;

    /**
     * Timezone identifier (e.g., "Asia/Ho_Chi_Minh" or offset like "+07:00").
     */
    private String timezone;

    /**
     * Browser/device language (e.g., "vi-VN", "en-US").
     */
    private String language;

    /**
     * Platform identifier (android, ios, web).
     */
    private String platform;

    /**
     * Device type (mobile, desktop, tablet).
     */
    private String deviceType;

    /**
     * Additional client-side data for fingerprinting.
     */
    private String additionalData;

    /**
     * Check if fingerprint data is valid (has at least some data).
     */
    public boolean isValid() {
        return (canvasHash != null && !canvasHash.isBlank()) ||
               (webglHash != null && !webglHash.isBlank()) ||
               (screenSize != null && !screenSize.isBlank());
    }

    /**
     * Convert to JSON string for storage.
     */
    public String toJsonString() {
        StringBuilder sb = new StringBuilder("{");
        sb.append("\"canvasHash\":\"").append(canvasHash != null ? canvasHash : "").append("\",");
        sb.append("\"webglHash\":\"").append(webglHash != null ? webglHash : "").append("\",");
        sb.append("\"screenSize\":\"").append(screenSize != null ? screenSize : "").append("\",");
        sb.append("\"timezone\":\"").append(timezone != null ? timezone : "").append("\",");
        sb.append("\"language\":\"").append(language != null ? language : "").append("\",");
        sb.append("\"platform\":\"").append(platform != null ? platform : "").append("\",");
        sb.append("\"deviceType\":\"").append(deviceType != null ? deviceType : "").append("\"");
        if (additionalData != null && !additionalData.isBlank()) {
            sb.append(",\"additionalData\":\"").append(additionalData).append("\"");
        }
        sb.append("}");
        return sb.toString();
    }
}

