package com.duong.lichvanien.tuvi.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Entity for storing cycle (Đại hạn/Tiểu vận) interpretations.
 * This table caches cycle interpretations generated by Grok AI.
 */
@Entity
@Table(name = "tuvi_cycle_interpretation",
       uniqueConstraints = @UniqueConstraint(name = "uk_chart_hash_gender", columnNames = {"chart_hash", "gender"}),
       indexes = {
           @Index(name = "idx_chart_hash", columnList = "chart_hash"),
           @Index(name = "idx_gender", columnList = "gender"),
           @Index(name = "idx_generated_at", columnList = "generated_at")
       })
@Getter
@Setter
public class TuViCycleInterpretationEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "chart_hash", nullable = false, length = 64)
    private String chartHash;

    @Enumerated(EnumType.STRING)
    @Column(name = "gender", nullable = false, length = 10)
    private Gender gender;

    @Column(name = "name", length = 128)
    private String name;

    @Column(name = "birth_date")
    private LocalDate birthDate;

    /**
     * Complete cycle interpretation data stored as JSON.
     * Contains: introduction, overallCycleSummary, daiVanInterpretations, generalAdvice
     */
    @Column(name = "cycle_interpretation_data", nullable = false, columnDefinition = "JSON")
    private String cycleInterpretationData;

    @Column(name = "ai_model", length = 64)
    private String aiModel;

    @Column(name = "generated_at", nullable = false, updatable = false)
    private LocalDateTime generatedAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        if (generatedAt == null) {
            generatedAt = LocalDateTime.now();
        }
        if (updatedAt == null) {
            updatedAt = LocalDateTime.now();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    public enum Gender {
        male, female
    }
}

